/* Talk mode — French: 40 spoken dialogs, from “Bonjour” to telling a story about your first trip.
   Themes (5 levels each): greetings → café & restaurant → numbers & shopping → directions & transport
   → hotel & fixing problems → small talk (tu introduced) → plans & invitations → past, health, opinions. */
HS.talk = HS.talk || {};
HS.talk.french = {
  lang: 'fr-FR',
  levels: [
    /* ---------- 1. Greetings & introductions ---------- */
    {
      title: 'Bonjour!',
      scene: 'You walk into a small shop in France in the morning.',
      turns: [
        { them: { t: 'Bonjour!', en: 'Hello!' } },
        { you: { cue: 'Say: Hello, sir.', t: 'Bonjour, monsieur.', en: 'Hello, sir.',
          alt: ['Bonjour monsieur', 'Bonjour!'],
          gloss: 'bonjour = hello (all day long) · monsieur = sir (always add it to be polite)' } },
        { them: { t: 'Ça va?', en: 'How are you?' } },
        { you: { cue: 'Say: Fine, thanks.', t: 'Ça va, merci.', en: 'Fine, thanks.',
          alt: ['Ça va bien, merci.', 'Très bien, merci.', 'Ça va.'],
          gloss: 'ça va = it goes → “I’m fine” (the same words ask “how are you?”) · merci = thank you' } },
        { them: { t: 'Voilà, monsieur.', en: 'Here you are, sir.' } },
        { you: { cue: 'Say: Thank you very much.', t: 'Merci beaucoup.', en: 'Thank you very much.',
          alt: ['Merci bien.', 'Merci!'],
          gloss: 'merci = thank you · beaucoup = a lot, very much' } },
        { them: { t: 'Bonne journée!', en: 'Have a nice day!' } },
        { you: { cue: 'Say: Goodbye!', t: 'Au revoir!', en: 'Goodbye!',
          alt: ['Au revoir, monsieur.', 'Au revoir, bonne journée.'],
          gloss: 'au revoir = goodbye (literally “until seeing again”)' } }
      ]
    },
    {
      title: 'My name is…',
      scene: 'At a language meetup, a woman called Claire comes over to say hello.',
      turns: [
        { them: { t: 'Bonjour!', en: 'Hello!' } },
        { you: { cue: 'Say: Hello, madam.', t: 'Bonjour, madame.', en: 'Hello, madam.',
          alt: ['Bonjour madame', 'Bonjour!'],
          gloss: 'bonjour = hello · madame = madam (the polite way to address a woman)' } },
        { them: { t: 'Je m’appelle Claire. Et vous?', en: 'My name is Claire. And you?' } },
        { you: { cue: 'Say: My name is Alex.', t: 'Je m’appelle Alex.', en: 'My name is Alex.',
          alt: ['Moi, c’est Alex.', 'Je suis Alex.'],
          gloss: 'je = I · m’appelle = call myself (s’appeler, “to be called”) → “my name is”' } },
        { them: { t: 'Enchantée, Alex.', en: 'Nice to meet you, Alex.' } },
        { you: { cue: 'Say: Nice to meet you.', t: 'Enchanté.', en: 'Nice to meet you.',
          alt: ['Enchantée.', 'Enchanté, Claire.'],
          gloss: 'enchanté = delighted → “nice to meet you” (a woman writes enchantée; it sounds the same)' } },
        { them: { t: 'Ça va?', en: 'How are you?' } },
        { you: { cue: 'Say: Fine, thanks.', t: 'Ça va, merci.', en: 'Fine, thanks.',
          alt: ['Ça va bien, merci.', 'Très bien, merci.'],
          gloss: 'ça va = it goes → “I’m fine” · merci = thank you' } },
        { them: { t: 'Au revoir, Alex!', en: 'Goodbye, Alex!' } },
        { you: { cue: 'Say: Goodbye, Claire.', t: 'Au revoir, Claire.', en: 'Goodbye, Claire.',
          alt: ['Au revoir!', 'Au revoir, madame.'],
          gloss: 'au revoir = goodbye · Claire = her name' } }
      ]
    },
    {
      title: 'Sorry, I don’t understand',
      scene: 'A man in the street asks you something, very fast.',
      turns: [
        { them: { t: 'Excusez-moi, vous avez l’heure?', en: 'Excuse me, do you have the time?' } },
        { you: { cue: 'Say: Sorry? — you didn’t catch it.', t: 'Pardon?', en: 'Sorry?',
          alt: ['Pardon, monsieur?', 'Comment?'],
          gloss: 'pardon = sorry / excuse me; said rising, it means “what did you say?”' } },
        { them: { t: 'L’heure, s’il vous plaît?', en: 'The time, please?' } },
        { you: { cue: 'Say: I don’t understand.', t: 'Je ne comprends pas.', en: 'I don’t understand.',
          alt: ['Je comprends pas.', 'Désolé, je ne comprends pas.'],
          gloss: 'je = I · ne … pas = not (wraps the verb) · comprends = understand (comprendre)' } },
        { them: { t: 'Quelle… heure… est-il?', en: 'What… time… is it?' } },
        { you: { cue: 'Say: Sorry, I don’t know.', t: 'Désolé, je ne sais pas.', en: 'Sorry, I don’t know.',
          alt: ['Désolée, je ne sais pas.', 'Désolé, je sais pas.', 'Je sais pas, désolé.'],
          gloss: 'désolé = sorry (a woman writes désolée, same sound) · je = I · ne … pas = not · sais = know (savoir)' } },
        { them: { t: 'Pas de problème. Merci!', en: 'No problem. Thanks!' } },
        { you: { cue: 'Say: Thanks, have a nice day!', t: 'Merci, bonne journée!', en: 'Thanks, have a nice day!',
          alt: ['Bonne journée!', 'Merci, bonne journée, monsieur.'],
          gloss: 'merci = thank you · bonne = good (feminine) · journée = day → “have a good day”' } },
        { them: { t: 'Bonne journée!', en: 'Have a nice day!' } },
        { you: { cue: 'Say: Goodbye!', t: 'Au revoir!', en: 'Goodbye!',
          alt: ['Au revoir, monsieur.'],
          gloss: 'au revoir = goodbye' } }
      ]
    },
    {
      title: 'At the bakery',
      scene: 'At a bakery counter, the baker talks fast and you only want bread.',
      turns: [
        { them: { t: 'Bonjour! Qu’est-ce que je vous sers?', en: 'Hello! What can I get you?' } },
        { you: { cue: 'Say: Hello, madam.', t: 'Bonjour, madame.', en: 'Hello, madam.',
          alt: ['Bonjour madame', 'Bonjour!'],
          gloss: 'bonjour = hello · madame = madam' } },
        { them: { t: 'Qu’est-ce que je vous sers?', en: 'What can I get you?' } },
        { you: { cue: 'Say: More slowly, please.', t: 'Plus lentement, s’il vous plaît.', en: 'More slowly, please.',
          alt: ['Moins vite, s’il vous plaît.', 'Lentement, s’il vous plaît.'],
          gloss: 'plus = more · lentement = slowly · s’il vous plaît = please (literally “if it pleases you”)' } },
        { them: { t: 'Qu’est-ce… que… vous voulez?', en: 'What… do… you want?' } },
        { you: { cue: 'Ask: Do you speak English?', t: 'Vous parlez anglais?', en: 'Do you speak English?',
          alt: ['Parlez-vous anglais?', 'Vous parlez anglais, madame?'],
          gloss: 'vous = you (polite) · parlez = speak (parler) · anglais = English; a rising voice makes it a question' } },
        { them: { t: 'Non, désolée. Un peu.', en: 'No, sorry. A little.' } },
        { you: { cue: 'Say: A baguette, please.', t: 'Une baguette, s’il vous plaît.', en: 'A baguette, please.',
          alt: ['Une baguette, s’il vous plaît, madame.', 'Une baguette.'],
          gloss: 'une = a (feminine) · baguette = long loaf of bread · s’il vous plaît = please' } },
        { them: { t: 'Voilà. Un euro vingt.', en: 'Here you are. One euro twenty.' } },
        { you: { cue: 'Say: Thank you very much.', t: 'Merci beaucoup.', en: 'Thank you very much.',
          alt: ['Merci bien.', 'Merci, madame.'],
          gloss: 'merci = thank you · beaucoup = a lot' } }
      ]
    },
    {
      title: 'Salut! Meeting a friend of a friend',
      scene: 'At a party, your friend introduces Tom. He is your age, so he says tu, the friendly “you” — answer the same way.',
      turns: [
        { them: { t: 'Salut! Moi, c’est Tom. Et toi?', en: 'Hi! I’m Tom. And you?' } },
        { you: { cue: 'Say: Hi! I’m Alex.', t: 'Salut! Moi, c’est Alex.', en: 'Hi! I’m Alex.',
          alt: ['Salut! Je m’appelle Alex.', 'Moi, c’est Alex.'],
          gloss: 'salut = hi / bye (with friends only) · moi = me · c’est = it’s → “me, I’m Alex”' } },
        { them: { t: 'Ça va?', en: 'How’s it going?' } },
        { you: { cue: 'Say: Fine, and you? — use toi, the friendly “you”.', t: 'Ça va, et toi?', en: 'Fine, and you?',
          alt: ['Ça va bien, et toi?', 'Bien, et toi?', 'Ça va. Et toi?'],
          gloss: 'ça va = I’m fine · et = and · toi = you (friendly form; with strangers it’s vous)' } },
        { them: { t: 'Super! Tu parles français?', en: 'Great! Do you speak French?' } },
        { you: { cue: 'Say: A little.', t: 'Un peu.', en: 'A little.',
          alt: ['Oui, un peu.', 'Juste un peu.'],
          gloss: 'un peu = a little (literally “a bit”)' } },
        { them: { t: 'Tu es en vacances?', en: 'Are you on holiday?' } },
        { you: { cue: 'Say: Yes, I’m on holiday.', t: 'Oui, je suis en vacances.', en: 'Yes, I’m on holiday.',
          alt: ['Oui, en vacances.', 'Je suis en vacances.'],
          gloss: 'oui = yes · je suis = I am (être) · en vacances = on holiday' } },
        { them: { t: 'Cool! À plus tard!', en: 'Cool! See you later!' } },
        { you: { cue: 'Say: Bye, see you!', t: 'Salut, à plus!', en: 'Bye, see you!',
          alt: ['À plus!', 'À plus tard!', 'Salut!'],
          gloss: 'salut = bye (friendly) · à plus = see you (short for à plus tard, “until later”)' } }
      ]
    },

    /* ---------- 2. Café & restaurant ---------- */
    {
      title: 'A coffee, please',
      scene: 'You sit down on a café terrace and the waiter comes over.',
      turns: [
        { them: { t: 'Bonjour! Qu’est-ce que je vous sers?', en: 'Hello! What can I get you?' } },
        { you: { cue: 'Say: Hello. A coffee, please.', t: 'Bonjour. Un café, s’il vous plaît.', en: 'Hello. A coffee, please.',
          alt: ['Un café, s’il vous plaît.', 'Bonjour, un café s’il vous plaît.'],
          gloss: 'bonjour = hello · un = a (masculine) · café = coffee (a small espresso) · s’il vous plaît = please' } },
        { them: { t: 'Un café. Et avec ça?', en: 'A coffee. Anything else?' } },
        { you: { cue: 'Say: A croissant too.', t: 'Un croissant aussi.', en: 'A croissant too.',
          alt: ['Et un croissant, s’il vous plaît.', 'Un croissant, s’il vous plaît.'],
          gloss: 'un = a · croissant = croissant · aussi = too, also' } },
        { them: { t: 'Autre chose?', en: 'Anything else?' } },
        { you: { cue: 'Say: No, that’s all, thanks.', t: 'Non, c’est tout, merci.', en: 'No, that’s all, thanks.',
          alt: ['C’est tout, merci.', 'Non merci, c’est tout.', 'Non, ça va, merci.'],
          gloss: 'non = no · c’est = it is · tout = all · merci = thanks' } },
        { them: { t: 'Voilà, monsieur. Un café et un croissant.', en: 'Here you are, sir. A coffee and a croissant.' } },
        { you: { cue: 'Say: Thank you very much.', t: 'Merci beaucoup.', en: 'Thank you very much.',
          alt: ['Merci bien.', 'Merci!'],
          gloss: 'merci = thank you · beaucoup = a lot' } },
        { them: { t: 'Bonne journée!', en: 'Have a nice day!' } },
        { you: { cue: 'Say: Thanks, you too.', t: 'Merci, vous aussi.', en: 'Thanks, you too.',
          alt: ['Vous aussi!', 'Merci, à vous aussi.'],
          gloss: 'merci = thanks · vous = you (polite) · aussi = too' } }
      ]
    },
    {
      title: 'The bill, please',
      scene: 'You have finished your coffee and want to pay.',
      turns: [
        { you: { cue: 'Catch the waiter’s eye. Say: Excuse me, sir!', t: 'Excusez-moi, monsieur!', en: 'Excuse me, sir!',
          alt: ['Excusez-moi!', 'Monsieur, s’il vous plaît!', 'S’il vous plaît!'],
          gloss: 'excusez-moi = excuse me (excuser, polite command) · monsieur = sir' } },
        { them: { t: 'Oui?', en: 'Yes?' } },
        { you: { cue: 'Say: The bill, please.', t: 'L’addition, s’il vous plaît.', en: 'The bill, please.',
          alt: ['L’addition s’il vous plaît.', 'On peut avoir l’addition?'],
          gloss: 'l’addition = the bill (la + addition) · s’il vous plaît = please' } },
        { them: { t: 'Tout de suite. C’était bien?', en: 'Right away. Was it good?' } },
        { you: { cue: 'Say: Yes, very good, thanks.', t: 'Oui, très bon, merci.', en: 'Yes, very good, thanks.',
          alt: ['Très bon, merci.', 'Oui, c’était très bon.', 'Délicieux, merci.'],
          gloss: 'oui = yes · très = very · bon = good (for food and drink) · merci = thanks' } },
        { them: { t: 'Voilà. Trois euros cinquante.', en: 'Here you are. Three euros fifty.' } },
        { you: { cue: 'Ask: Can I pay by card?', t: 'Je peux payer par carte?', en: 'Can I pay by card?',
          alt: ['Par carte, c’est possible?', 'Je peux payer avec la carte?'],
          gloss: 'je = I · peux = can (pouvoir) · payer = to pay · par carte = by card' } },
        { them: { t: 'Oui, bien sûr.', en: 'Yes, of course.' } },
        { you: { cue: 'Say: Thanks, have a nice day!', t: 'Merci, bonne journée!', en: 'Thanks, have a nice day!',
          alt: ['Bonne journée!', 'Merci, bonne journée, monsieur.'],
          gloss: 'merci = thanks · bonne journée = have a good day' } }
      ]
    },
    {
      title: 'A table for two',
      scene: 'In the evening, you walk into a restaurant with a friend.',
      turns: [
        { them: { t: 'Bonsoir! Vous êtes combien?', en: 'Good evening! How many of you?' } },
        { you: { cue: 'Say: Good evening, for two people.', t: 'Bonsoir, pour deux personnes.', en: 'Good evening, for two people.',
          alt: ['Deux personnes, s’il vous plaît.', 'On est deux.', 'Bonsoir, pour 2 personnes.'],
          gloss: 'bonsoir = good evening · pour = for · deux = two · personnes = people' } },
        { them: { t: 'Vous avez réservé?', en: 'Have you booked?' } },
        { you: { cue: 'Say: No, we haven’t booked.', t: 'Non, on n’a pas réservé.', en: 'No, we haven’t booked.',
          alt: ['Non, on a pas réservé.', 'Non, pas de réservation.'],
          gloss: 'non = no · on = we (everyday speech) · n’a pas = haven’t (avoir + ne … pas) · réservé = booked (réserver, past)' } },
        { them: { t: 'Pas de problème. En terrasse ou à l’intérieur?', en: 'No problem. On the terrace or inside?' } },
        { you: { cue: 'Say: On the terrace, please.', t: 'En terrasse, s’il vous plaît.', en: 'On the terrace, please.',
          alt: ['La terrasse, s’il vous plaît.', 'Dehors, s’il vous plaît.'],
          gloss: 'en terrasse = on the terrace (outside) · s’il vous plaît = please' } },
        { them: { t: 'Voici la carte.', en: 'Here is the menu.' } },
        { you: { cue: 'Say: Thank you, madam.', t: 'Merci, madame.', en: 'Thank you, madam.',
          alt: ['Merci!', 'Merci beaucoup.'],
          gloss: 'merci = thank you · madame = madam' } },
        { them: { t: 'Et à boire?', en: 'And to drink?' } },
        { you: { cue: 'Say: A jug of water, please.', t: 'Une carafe d’eau, s’il vous plaît.', en: 'A jug of tap water, please.',
          alt: ['De l’eau, s’il vous plaît.', 'Une carafe d’eau.'],
          gloss: 'une carafe = a jug · d’eau = of water (de + eau; tap water is free) · s’il vous plaît = please' } }
      ]
    },
    {
      title: 'Ordering a meal',
      scene: 'The waiter comes back to take your order.',
      turns: [
        { them: { t: 'Vous avez choisi?', en: 'Have you decided?' } },
        { you: { cue: 'Say: Yes. I’d like the dish of the day.', t: 'Oui. Je voudrais le plat du jour.', en: 'Yes. I’d like the dish of the day.',
          alt: ['Le plat du jour, s’il vous plaît.', 'Je vais prendre le plat du jour.', 'Pour moi, le plat du jour.'],
          gloss: 'je voudrais = I would like (vouloir, conditional — the polite way to order) · le plat = the dish · du jour = of the day' } },
        { them: { t: 'C’est du poulet avec des frites.', en: 'It’s chicken with chips.' } },
        { you: { cue: 'Say: That’s perfect, thanks.', t: 'C’est parfait, merci.', en: 'That’s perfect, thanks.',
          alt: ['Parfait!', 'Très bien, merci.'],
          gloss: 'c’est = it is · parfait = perfect · merci = thanks' } },
        { them: { t: 'Et comme boisson?', en: 'And to drink?' } },
        { you: { cue: 'Say: A glass of red wine.', t: 'Un verre de vin rouge.', en: 'A glass of red wine.',
          alt: ['Un verre de rouge, s’il vous plaît.', 'Un verre de vin rouge, s’il vous plaît.'],
          gloss: 'un verre = a glass · de = of · vin = wine · rouge = red (colours come after the noun)' } },
        { them: { t: 'Et pour votre ami?', en: 'And for your friend?' } },
        { you: { cue: 'Say: The same thing, please.', t: 'La même chose, s’il vous plaît.', en: 'The same, please.',
          alt: ['Pareil, s’il vous plaît.', 'La même chose.'],
          gloss: 'la même chose = the same thing · s’il vous plaît = please' } },
        { them: { t: 'Très bien. Bon appétit!', en: 'Very good. Enjoy your meal!' } },
        { you: { cue: 'Say: Thanks!', t: 'Merci!', en: 'Thanks!',
          alt: ['Merci bien.', 'Merci beaucoup.'],
          gloss: 'merci = thank you' } }
      ]
    },
    {
      title: 'Dessert and the bill',
      scene: 'At the end of the meal, the waiter asks how it was.',
      turns: [
        { them: { t: 'Ça vous a plu?', en: 'Did you enjoy it?' } },
        { you: { cue: 'Say: Yes, it was delicious.', t: 'Oui, c’était délicieux.', en: 'Yes, it was delicious.',
          alt: ['C’était très bon.', 'Délicieux, merci.', 'Oui, très bon.'],
          gloss: 'oui = yes · c’était = it was (être, imperfect) · délicieux = delicious' } },
        { them: { t: 'Un dessert? Un café?', en: 'A dessert? A coffee?' } },
        { you: { cue: 'Ask: What do you have for dessert?', t: 'Qu’est-ce que vous avez comme desserts?', en: 'What do you have for dessert?',
          alt: ['Vous avez quoi comme desserts?', 'Qu’est-ce qu’il y a comme dessert?'],
          gloss: 'qu’est-ce que = what (question opener) · vous avez = you have (avoir) · comme = as, in the way of · desserts = desserts' } },
        { them: { t: 'Tarte aux pommes, crème brûlée ou glace.', en: 'Apple tart, crème brûlée or ice cream.' } },
        { you: { cue: 'Say: A crème brûlée, please.', t: 'Une crème brûlée, s’il vous plaît.', en: 'A crème brûlée, please.',
          alt: ['La crème brûlée, s’il vous plaît.', 'Je voudrais une crème brûlée.'],
          gloss: 'une = a (feminine) · crème brûlée = “burnt cream”, the custard dessert · s’il vous plaît = please' } },
        { them: { t: 'Et un café avec?', en: 'And a coffee with it?' } },
        { you: { cue: 'Say: No thanks, no coffee.', t: 'Non merci, pas de café.', en: 'No thanks, no coffee.',
          alt: ['Non, merci.', 'Pas de café pour moi, merci.'],
          gloss: 'non merci = no thanks · pas de = no, not any (after a negative, un/du become de) · café = coffee' } },
        { them: { t: 'Très bien. Autre chose?', en: 'Very good. Anything else?' } },
        { you: { cue: 'Say: The bill, please.', t: 'L’addition, s’il vous plaît.', en: 'The bill, please.',
          alt: ['L’addition s’il vous plaît.', 'On peut avoir l’addition?'],
          gloss: 'l’addition = the bill · s’il vous plaît = please' } }
      ]
    },

    /* ---------- 3. Numbers, prices & shopping ---------- */
    {
      title: 'At the market',
      scene: 'At an outdoor market, you want to buy some fruit and vegetables.',
      turns: [
        { them: { t: 'Bonjour! Je vous écoute.', en: 'Hello! What can I get you?' } },
        { you: { cue: 'Say hello and ask how much the tomatoes are.', t: 'Bonjour. Combien coûtent les tomates?', en: 'Hello. How much are the tomatoes?',
          alt: ['C’est combien, les tomates?', 'Les tomates, c’est combien?', 'Combien, les tomates?'],
          gloss: 'bonjour = hello · combien = how much · coûtent = cost (coûter, “they” form) · les tomates = the tomatoes' } },
        { them: { t: 'Trois euros le kilo.', en: 'Three euros a kilo.' } },
        { you: { cue: 'Ask for one kilo.', t: 'Un kilo, s’il vous plaît.', en: 'One kilo, please.',
          alt: ['Un kilo de tomates, s’il vous plaît.', 'Je voudrais un kilo.', '1 kilo, s’il vous plaît.'],
          gloss: 'un kilo = one kilo (un is both “a” and “one”) · s’il vous plaît = please' } },
        { them: { t: 'Et avec ceci?', en: 'Anything else with that?' } },
        { you: { cue: 'Ask for six apples as well.', t: 'Et six pommes, s’il vous plaît.', en: 'And six apples, please.',
          alt: ['Six pommes aussi.', 'Et 6 pommes, s’il vous plaît.', 'Je voudrais aussi six pommes.'],
          gloss: 'et = and · six = six · pommes = apples (une pomme) · s’il vous plaît = please' } },
        { them: { t: 'C’est tout?', en: 'Is that everything?' } },
        { you: { cue: 'Say yes, that’s all.', t: 'Oui, c’est tout.', en: 'Yes, that’s all.',
          alt: ['C’est tout, merci.', 'Oui, merci.'],
          gloss: 'oui = yes · c’est = it is · tout = all' } },
        { them: { t: 'Ça fait cinq euros.', en: 'That comes to five euros.' } },
        { you: { cue: 'Hand over the money, thank her and say goodbye.', t: 'Voilà. Merci, au revoir.', en: 'Here you are. Thanks, goodbye.',
          alt: ['Voilà, merci.', 'Tenez, merci. Au revoir.'],
          gloss: 'voilà = here you are / there · merci = thanks · au revoir = goodbye' } }
      ]
    },
    {
      title: 'Trying on a jacket',
      scene: 'In a clothes shop, you see a jacket you like.',
      turns: [
        { them: { t: 'Bonjour, je peux vous aider?', en: 'Hello, can I help you?' } },
        { you: { cue: 'Say yes, you’re looking for a jacket.', t: 'Oui, je cherche une veste.', en: 'Yes, I’m looking for a jacket.',
          alt: ['Je cherche une veste.', 'Oui, une veste, s’il vous plaît.'],
          gloss: 'oui = yes · je cherche = I’m looking for (chercher) · une veste = a jacket' } },
        { them: { t: 'Vous faites quelle taille?', en: 'What size are you?' } },
        { you: { cue: 'Say you’re a size forty.', t: 'Je fais du quarante.', en: 'I’m a forty.',
          alt: ['Du quarante.', 'Je fais du 40.', 'Taille quarante.'],
          gloss: 'je fais = I do/make (faire) → “I take” · du quarante = a forty (du = de + le)' } },
        { them: { t: 'Voilà. La cabine est là-bas. … Alors?', en: 'Here you are. The fitting room is over there. … So?' } },
        { you: { cue: 'Say it’s a bit big.', t: 'Elle est un peu grande.', en: 'It’s a bit big.',
          alt: ['C’est un peu grand.', 'Un peu grande.', 'Elle est trop grande.'],
          gloss: 'elle = it (la veste is feminine, so “she”) · est = is · un peu = a bit · grande = big (feminine)' } },
        { them: { t: 'Voilà la taille en dessous.', en: 'Here’s the size down.' } },
        { you: { cue: 'Say it’s perfect, and ask how much it costs.', t: 'C’est parfait. Elle coûte combien?', en: 'It’s perfect. How much is it?',
          alt: ['Parfait, c’est combien?', 'Elle fait combien?', 'Elle est à combien?'],
          gloss: 'c’est parfait = it’s perfect · elle coûte = it costs (coûter) · combien = how much' } },
        { them: { t: 'Soixante euros.', en: 'Sixty euros.' } },
        { you: { cue: 'Say OK, you’ll take it.', t: 'D’accord, je la prends.', en: 'OK, I’ll take it.',
          alt: ['Je la prends.', 'OK, je la prends.', 'D’accord, je prends.'],
          gloss: 'd’accord = OK, agreed · je = I · la = it (the jacket; object pronoun goes before the verb) · prends = take (prendre)' } }
      ]
    },
    {
      title: 'At the till',
      scene: 'At a small grocery till, the cashier tells you the total.',
      turns: [
        { them: { t: 'Ça fait douze euros quarante.', en: 'That’s twelve euros forty.' } },
        { you: { cue: 'You didn’t catch it: say sorry and ask how much.', t: 'Pardon, c’est combien?', en: 'Sorry, how much is it?',
          alt: ['Pardon, combien?', 'Combien?', 'Vous pouvez répéter?'],
          gloss: 'pardon = sorry · c’est = it is · combien = how much' } },
        { them: { t: 'Douze euros quarante.', en: 'Twelve euros forty.' } },
        { you: { cue: 'Ask if you can pay by card.', t: 'Je peux payer par carte?', en: 'Can I pay by card?',
          alt: ['Par carte, c’est possible?', 'Je peux payer avec la carte?'],
          gloss: 'je peux = I can (pouvoir) · payer = to pay · par carte = by card' } },
        { them: { t: 'Désolée, la machine ne marche pas.', en: 'Sorry, the card machine isn’t working.' } },
        { you: { cue: 'Say OK — you have a twenty-euro note.', t: 'D’accord. J’ai un billet de vingt.', en: 'OK. I have a twenty.',
          alt: ['J’ai un billet de 20.', 'D’accord, j’ai vingt euros.', 'Voilà vingt euros.'],
          gloss: 'd’accord = OK · j’ai = I have (avoir) · un billet = a banknote · de vingt = of twenty' } },
        { them: { t: 'Merci. Vous avez un sac?', en: 'Thanks. Do you have a bag?' } },
        { you: { cue: 'Say no, you don’t have a bag.', t: 'Non, je n’ai pas de sac.', en: 'No, I don’t have a bag.',
          alt: ['Non, j’ai pas de sac.', 'Non, pas de sac.'],
          gloss: 'non = no · je n’ai pas = I don’t have (avoir + ne … pas) · de sac = a bag (un becomes de after a negative)' } },
        { them: { t: 'Un sac, c’est dix centimes.', en: 'A bag is ten cents.' } },
        { you: { cue: 'Say yes, a bag please.', t: 'Oui, un sac, s’il vous plaît.', en: 'Yes, a bag, please.',
          alt: ['Un sac, s’il vous plaît.', 'D’accord, un sac.'],
          gloss: 'oui = yes · un sac = a bag · s’il vous plaît = please' } }
      ]
    },
    {
      title: 'Museum tickets',
      scene: 'You arrive at the door of a small museum with a friend and a child.',
      turns: [
        { you: { cue: 'Say hello and ask if it’s open today.', t: 'Bonjour, c’est ouvert aujourd’hui?', en: 'Hello, is it open today?',
          alt: ['C’est ouvert aujourd’hui?', 'Vous êtes ouverts aujourd’hui?', 'Bonjour, vous êtes ouvert?'],
          gloss: 'bonjour = hello · c’est = it is · ouvert = open · aujourd’hui = today' } },
        { them: { t: 'Oui, jusqu’à dix-huit heures.', en: 'Yes, until six p.m.' } },
        { you: { cue: 'Ask how much a ticket costs.', t: 'Combien coûte un billet?', en: 'How much is a ticket?',
          alt: ['C’est combien, un billet?', 'Le billet, c’est combien?', 'Un billet coûte combien?'],
          gloss: 'combien = how much · coûte = costs (coûter) · un billet = a ticket' } },
        { them: { t: 'Douze euros. C’est gratuit pour les enfants.', en: 'Twelve euros. It’s free for children.' } },
        { you: { cue: 'Ask for two adults and one child.', t: 'Deux adultes et un enfant, s’il vous plaît.', en: 'Two adults and one child, please.',
          alt: ['Deux adultes, un enfant.', '2 adultes et 1 enfant, s’il vous plaît.', 'Deux adultes et un enfant.'],
          gloss: 'deux = two · adultes = adults · et = and · un enfant = one child · s’il vous plaît = please' } },
        { them: { t: 'Ça fait vingt-quatre euros.', en: 'That’s twenty-four euros.' } },
        { you: { cue: 'Ask if it’s open tomorrow too.', t: 'Et c’est ouvert demain aussi?', en: 'And is it open tomorrow too?',
          alt: ['C’est ouvert demain?', 'Vous êtes ouverts demain aussi?'],
          gloss: 'et = and · c’est ouvert = it’s open · demain = tomorrow · aussi = too' } },
        { them: { t: 'Non, le lundi, c’est fermé.', en: 'No, on Mondays it’s closed.' } },
        { you: { cue: 'Say OK, and thank him very much.', t: 'D’accord, merci beaucoup.', en: 'OK, thank you very much.',
          alt: ['D’accord, merci.', 'Ah, d’accord. Merci.'],
          gloss: 'd’accord = OK · merci beaucoup = thank you very much' } }
      ]
    },
    {
      title: 'Taking something back',
      scene: 'You go back to a shop because the phone charger you bought yesterday doesn’t work.',
      turns: [
        { you: { cue: 'Say hello, and that you bought this yesterday.', t: 'Bonjour, j’ai acheté ça hier.', en: 'Hello, I bought this yesterday.',
          alt: ['J’ai acheté ça hier.', 'Bonjour, j’ai acheté ce chargeur hier.'],
          gloss: 'bonjour = hello · j’ai acheté = I bought (acheter, passé composé: avoir + past participle) · ça = this, that · hier = yesterday' } },
        { them: { t: 'Oui? Il y a un problème?', en: 'Yes? Is there a problem?' } },
        { you: { cue: 'Say yes — it doesn’t work.', t: 'Oui, il ne marche pas.', en: 'Yes, it doesn’t work.',
          alt: ['Oui, ça ne marche pas.', 'Il marche pas.', 'Ça marche pas.'],
          gloss: 'oui = yes · il = it (le chargeur, masculine) · ne … pas = not · marche = works (marcher, “to walk / to work”)' } },
        { them: { t: 'Vous avez le ticket de caisse?', en: 'Do you have the receipt?' } },
        { you: { cue: 'Say yes, here’s the receipt.', t: 'Oui, voilà le ticket.', en: 'Yes, here’s the receipt.',
          alt: ['Oui, le voilà.', 'Voilà le ticket.', 'Oui, voici le ticket.'],
          gloss: 'oui = yes · voilà = here is · le ticket = the receipt (short for ticket de caisse)' } },
        { them: { t: 'Vous voulez un échange ou un remboursement?', en: 'Do you want an exchange or a refund?' } },
        { you: { cue: 'Say you’d like a refund.', t: 'Je voudrais un remboursement, s’il vous plaît.', en: 'I’d like a refund, please.',
          alt: ['Un remboursement, s’il vous plaît.', 'Je préfère un remboursement.'],
          gloss: 'je voudrais = I would like · un remboursement = a refund · s’il vous plaît = please' } },
        { them: { t: 'Pas de problème. C’est fait.', en: 'No problem. It’s done.' } },
        { you: { cue: 'Thank him and say he’s very kind.', t: 'Merci, vous êtes très gentil.', en: 'Thanks, you’re very kind.',
          alt: ['Merci, c’est gentil.', 'Merci beaucoup, c’est très gentil.'],
          gloss: 'merci = thanks · vous êtes = you are (être) · très = very · gentil = kind (gentille to a woman)' } }
      ]
    },

    /* ---------- 4. Directions & transport ---------- */
    {
      title: 'Where is the metro?',
      scene: 'You are lost in the street and stop a woman to ask the way.',
      turns: [
        { you: { cue: 'Stop her politely and ask where the metro is.', t: 'Excusez-moi, madame. Où est le métro?', en: 'Excuse me, madam. Where is the metro?',
          alt: ['Excusez-moi, où est le métro?', 'Où est le métro, s’il vous plaît?', 'Pardon, madame, le métro, s’il vous plaît?'],
          gloss: 'excusez-moi = excuse me · madame = madam · où = where · est = is · le métro = the underground' } },
        { them: { t: 'Le métro? C’est tout droit, puis à gauche.', en: 'The metro? Straight on, then left.' } },
        { you: { cue: 'Check you got it: straight on, then left?', t: 'Tout droit, puis à gauche?', en: 'Straight on, then left?',
          alt: ['Tout droit et à gauche?', 'Tout droit puis à gauche, c’est ça?'],
          gloss: 'tout droit = straight on · puis = then · à gauche = to the left (à droite = to the right)' } },
        { them: { t: 'Oui, c’est ça. Au feu, à gauche.', en: 'Yes, that’s it. Left at the traffic lights.' } },
        { you: { cue: 'Ask if it’s far from here.', t: 'C’est loin d’ici?', en: 'Is it far from here?',
          alt: ['C’est loin?', 'Il est loin?'],
          gloss: 'c’est = it is · loin = far · d’ici = from here (de + ici)' } },
        { them: { t: 'Non, cinq minutes à pied.', en: 'No, five minutes on foot.' } },
        { you: { cue: 'Ask if there’s a chemist near here too.', t: 'Il y a une pharmacie près d’ici?', en: 'Is there a chemist near here?',
          alt: ['Il y a une pharmacie pas loin?', 'Une pharmacie, près d’ici?'],
          gloss: 'il y a = there is · une pharmacie = a chemist’s · près d’ici = near here' } },
        { them: { t: 'Oui, juste à côté du métro.', en: 'Yes, right next to the metro.' } },
        { you: { cue: 'Thank her warmly and wish her a nice day.', t: 'Merci beaucoup, madame. Bonne journée.', en: 'Thank you very much, madam. Have a nice day.',
          alt: ['Merci beaucoup, bonne journée!', 'Merci, madame, bonne journée.'],
          gloss: 'merci beaucoup = thank you very much · madame = madam · bonne journée = have a good day' } }
      ]
    },
    {
      title: 'A metro ticket',
      scene: 'At the metro ticket window, you want to get to the Eiffel Tower.',
      turns: [
        { you: { cue: 'Say hello and ask for one metro ticket.', t: 'Bonjour, un ticket de métro, s’il vous plaît.', en: 'Hello, one metro ticket, please.',
          alt: ['Un ticket, s’il vous plaît.', 'Un ticket de métro, s’il vous plaît.'],
          gloss: 'bonjour = hello · un ticket = a ticket (for metro and bus) · de métro = for the metro · s’il vous plaît = please' } },
        { them: { t: 'Un ticket, ou un carnet de dix?', en: 'One ticket, or a book of ten?' } },
        { you: { cue: 'Ask how much the book of ten is.', t: 'C’est combien, le carnet?', en: 'How much is the book of ten?',
          alt: ['Combien coûte le carnet?', 'Le carnet, c’est combien?'],
          gloss: 'c’est combien = how much is it · le carnet = the book (of tickets)' } },
        { them: { t: 'Dix-sept euros.', en: 'Seventeen euros.' } },
        { you: { cue: 'Say OK, you’ll take the book.', t: 'D’accord, je prends le carnet.', en: 'OK, I’ll take the book of ten.',
          alt: ['Je prends le carnet.', 'Un carnet, s’il vous plaît.'],
          gloss: 'd’accord = OK · je prends = I take (prendre) · le carnet = the book of tickets' } },
        { them: { t: 'Voilà. Autre chose?', en: 'There you go. Anything else?' } },
        { you: { cue: 'Ask which line goes to the Eiffel Tower.', t: 'Pour aller à la tour Eiffel, c’est quelle ligne?', en: 'Which line is it to get to the Eiffel Tower?',
          alt: ['C’est quelle ligne pour la tour Eiffel?', 'Quelle ligne pour la tour Eiffel?'],
          gloss: 'pour aller à = to go to · la tour Eiffel = the Eiffel Tower · c’est = it is · quelle ligne = which line' } },
        { them: { t: 'Ligne six. Descendez à Bir-Hakeim.', en: 'Line six. Get off at Bir-Hakeim.' } },
        { you: { cue: 'Thank him and wish him a nice day.', t: 'Merci, bonne journée!', en: 'Thanks, have a nice day!',
          alt: ['Merci beaucoup, bonne journée!', 'Bonne journée!'],
          gloss: 'merci = thanks · bonne journée = have a good day' } }
      ]
    },
    {
      title: 'In a taxi',
      scene: 'You get into a taxi outside the station with two suitcases.',
      turns: [
        { them: { t: 'Bonjour! Vous allez où?', en: 'Hello! Where are you going?' } },
        { you: { cue: 'Ask to go to the Hotel Bellevue.', t: 'À l’hôtel Bellevue, s’il vous plaît.', en: 'To the Hotel Bellevue, please.',
          alt: ['Hôtel Bellevue, s’il vous plaît.', 'Je vais à l’hôtel Bellevue.'],
          gloss: 'à = to · l’hôtel = the hotel · s’il vous plaît = please' } },
        { them: { t: 'Rue de la Paix?', en: 'On Rue de la Paix?' } },
        { you: { cue: 'Say that’s right, and ask if it’s far.', t: 'Oui, c’est ça. C’est loin?', en: 'Yes, that’s right. Is it far?',
          alt: ['Oui. C’est loin?', 'C’est ça. C’est loin d’ici?'],
          gloss: 'oui = yes · c’est ça = that’s it, that’s right · c’est loin = is it far' } },
        { them: { t: 'Dix minutes, s’il n’y a pas de bouchons.', en: 'Ten minutes, if there are no traffic jams.' } },
        { you: { cue: 'Ask if he can put your suitcases in the boot.', t: 'Vous pouvez mettre mes valises dans le coffre?', en: 'Can you put my suitcases in the boot?',
          alt: ['Vous pouvez mettre les valises dans le coffre?', 'Les valises dans le coffre, c’est possible?'],
          gloss: 'vous pouvez = you can (pouvoir) · mettre = to put · mes valises = my suitcases · dans = in · le coffre = the boot/trunk' } },
        { them: { t: 'Bien sûr. … Voilà, on est arrivés. Vingt-deux euros.', en: 'Of course. … Here we are. Twenty-two euros.' } },
        { you: { cue: 'Ask if you can pay by card.', t: 'Je peux payer par carte?', en: 'Can I pay by card?',
          alt: ['Par carte, c’est possible?', 'Je peux payer avec la carte?'],
          gloss: 'je peux = I can · payer = to pay · par carte = by card' } },
        { them: { t: 'Oui, pas de problème.', en: 'Yes, no problem.' } },
        { you: { cue: 'Thank him and say he’s very kind.', t: 'Merci, vous êtes très gentil.', en: 'Thanks, you’re very kind.',
          alt: ['Merci, c’est gentil.', 'Merci beaucoup, c’est très gentil.'],
          gloss: 'merci = thanks · vous êtes = you are · très gentil = very kind' } }
      ]
    },
    {
      title: 'A train to Lyon',
      scene: 'At the ticket office of a big station, you want to go to Lyon and come back on Sunday.',
      turns: [
        { you: { cue: 'Say hello and ask for a return ticket to Lyon.', t: 'Bonjour, un aller-retour pour Lyon, s’il vous plaît.', en: 'Hello, a return ticket to Lyon, please.',
          alt: ['Un aller-retour pour Lyon, s’il vous plaît.', 'Je voudrais un aller-retour pour Lyon.'],
          gloss: 'bonjour = hello · un aller-retour = a return ticket (literally “a go-return”) · pour = for, to · s’il vous plaît = please' } },
        { them: { t: 'Pour quand?', en: 'For when?' } },
        { you: { cue: 'Say tomorrow morning, around nine.', t: 'Pour demain matin, vers neuf heures.', en: 'For tomorrow morning, around nine.',
          alt: ['Demain matin, vers 9 heures.', 'Demain matin, vers neuf heures.', 'Pour demain, vers 9 heures.'],
          gloss: 'pour = for · demain matin = tomorrow morning · vers = around (a time) · neuf heures = nine o’clock' } },
        { them: { t: 'Il y a un train à neuf heures douze. Et le retour?', en: 'There’s a train at 9:12. And the return?' } },
        { you: { cue: 'Say you’re coming back on Sunday evening.', t: 'Le retour, c’est dimanche soir.', en: 'The return is Sunday evening.',
          alt: ['Dimanche soir.', 'Le retour dimanche soir.', 'Retour dimanche soir, s’il vous plaît.'],
          gloss: 'le retour = the return · c’est = it is · dimanche = Sunday · soir = evening' } },
        { them: { t: 'Ça fait quatre-vingt-dix euros.', en: 'That’s ninety euros.' } },
        { you: { cue: 'Ask which platform the train leaves from.', t: 'Il part de quel quai?', en: 'Which platform does it leave from?',
          alt: ['C’est quel quai?', 'Le train part de quel quai?', 'Quel quai, s’il vous plaît?'],
          gloss: 'il = it (le train) · part = leaves (partir) · de = from · quel quai = which platform' } },
        { them: { t: 'C’est affiché vingt minutes avant.', en: 'It’s shown on the board twenty minutes before.' } },
        { you: { cue: 'Say OK and thank her for her help.', t: 'D’accord, merci pour votre aide.', en: 'OK, thanks for your help.',
          alt: ['Merci pour votre aide.', 'D’accord, merci beaucoup.'],
          gloss: 'd’accord = OK · merci pour = thanks for · votre aide = your help' } }
      ]
    },
    {
      title: 'The train is late',
      scene: 'On the platform your train isn’t there, and you have a connection to catch.',
      turns: [
        { you: { cue: 'Ask a staff member if the train to Lyon is late.', t: 'Excusez-moi, le train pour Lyon est en retard?', en: 'Excuse me, is the train to Lyon late?',
          alt: ['Le train pour Lyon est en retard?', 'Pardon, le train de Lyon a du retard?'],
          gloss: 'excusez-moi = excuse me · le train pour Lyon = the train to Lyon · est = is · en retard = late' } },
        { them: { t: 'Oui, il a trente minutes de retard.', en: 'Yes, it’s thirty minutes late.' } },
        { you: { cue: 'Repeat “thirty minutes?” and say you have a connection.', t: 'Trente minutes? Mais j’ai une correspondance!', en: 'Thirty minutes? But I have a connection!',
          alt: ['Trente minutes? J’ai une correspondance.', '30 minutes? Mais j’ai une correspondance!'],
          gloss: 'trente = thirty · mais = but · j’ai = I have · une correspondance = a connection (train change)' } },
        { them: { t: 'Ne vous inquiétez pas. Vous pouvez prendre le train suivant.', en: 'Don’t worry. You can take the next train.' } },
        { you: { cue: 'Ask if your ticket is valid for the next train.', t: 'Mon billet est valable pour le train suivant?', en: 'Is my ticket valid for the next train?',
          alt: ['Le billet est valable pour le train suivant?', 'Mon billet marche pour le prochain train?'],
          gloss: 'mon billet = my ticket · est = is · valable = valid · pour = for · le train suivant = the next train' } },
        { them: { t: 'Oui, sans problème.', en: 'Yes, no problem.' } },
        { you: { cue: 'Ask if there’s a café in the station.', t: 'Et il y a un café dans la gare?', en: 'And is there a café in the station?',
          alt: ['Il y a un café dans la gare?', 'Il y a un café ici?'],
          gloss: 'et = and · il y a = there is · un café = a café · dans = in · la gare = the station' } },
        { them: { t: 'Oui, à côté du quai trois.', en: 'Yes, next to platform three.' } },
        { you: { cue: 'Say perfect, and thank him for his help.', t: 'Parfait, merci pour votre aide.', en: 'Perfect, thanks for your help.',
          alt: ['Merci pour votre aide.', 'Parfait, merci beaucoup.'],
          gloss: 'parfait = perfect · merci pour = thanks for · votre aide = your help' } }
      ]
    },

    /* ---------- 5. Hotel, travel & fixing problems ---------- */
    {
      title: 'Checking in',
      scene: 'You arrive at your hotel reception in the evening.',
      turns: [
        { them: { t: 'Bonsoir, bienvenue!', en: 'Good evening, welcome!' } },
        { you: { cue: 'Say good evening, and that you have a booking in the name of Martin.', t: 'Bonsoir, j’ai une réservation au nom de Martin.', en: 'Good evening, I have a booking in the name of Martin.',
          alt: ['J’ai une réservation au nom de Martin.', 'Bonsoir, une réservation au nom de Martin.'],
          gloss: 'bonsoir = good evening · j’ai = I have · une réservation = a booking · au nom de = in the name of' } },
        { them: { t: 'Oui, une chambre double pour trois nuits?', en: 'Yes, a double room for three nights?' } },
        { you: { cue: 'Confirm: three nights.', t: 'Oui, c’est ça, trois nuits.', en: 'Yes, that’s right, three nights.',
          alt: ['C’est ça, trois nuits.', 'Oui, 3 nuits.', 'Oui, c’est ça.'],
          gloss: 'oui = yes · c’est ça = that’s right · trois nuits = three nights' } },
        { them: { t: 'Votre passeport, s’il vous plaît.', en: 'Your passport, please.' } },
        { you: { cue: 'Hand it over and ask if breakfast is included.', t: 'Voilà. Le petit-déjeuner est compris?', en: 'Here you are. Is breakfast included?',
          alt: ['Le petit-déjeuner est inclus?', 'Le petit-déjeuner est compris?'],
          gloss: 'voilà = here you are · le petit-déjeuner = breakfast (“little lunch”) · est = is · compris = included' } },
        { them: { t: 'Oui, de sept heures à dix heures.', en: 'Yes, from seven to ten.' } },
        { you: { cue: 'Ask what the wifi password is.', t: 'Et quel est le code du wifi?', en: 'And what is the wifi password?',
          alt: ['C’est quoi le code wifi?', 'Le code du wifi, s’il vous plaît?', 'Quel est le mot de passe du wifi?'],
          gloss: 'et = and · quel est = what is · le code = the code, password · du wifi = of the wifi (du = de + le)' } },
        { them: { t: 'C’est sur la carte, avec votre clé. Chambre trente-deux.', en: 'It’s on the card, with your key. Room thirty-two.' } },
        { you: { cue: 'Thank her and ask where the lift is.', t: 'Merci. Où est l’ascenseur, s’il vous plaît?', en: 'Thanks. Where is the lift, please?',
          alt: ['Où est l’ascenseur?', 'Merci, l’ascenseur est où?', 'L’ascenseur, c’est où?'],
          gloss: 'merci = thanks · où est = where is · l’ascenseur = the lift/elevator · s’il vous plaît = please' } }
      ]
    },
    {
      title: 'A problem with the room',
      scene: 'You phone reception from your room: something isn’t working.',
      turns: [
        { you: { cue: 'Say good evening and give your room: thirty-two.', t: 'Bonsoir, c’est la chambre trente-deux.', en: 'Good evening, this is room thirty-two.',
          alt: ['Bonsoir, chambre trente-deux.', 'C’est la chambre 32.', 'Bonsoir, chambre 32.'],
          gloss: 'bonsoir = good evening · c’est = it is · la chambre = the room · trente-deux = thirty-two' } },
        { them: { t: 'Oui, bonsoir. Je vous écoute.', en: 'Yes, good evening. How can I help?' } },
        { you: { cue: 'Say there’s a problem: the shower doesn’t work.', t: 'Il y a un problème, la douche ne marche pas.', en: 'There’s a problem, the shower doesn’t work.',
          alt: ['La douche ne marche pas.', 'Il y a un problème avec la douche.', 'La douche marche pas.'],
          gloss: 'il y a = there is · un problème = a problem · la douche = the shower · ne marche pas = doesn’t work' } },
        { them: { t: 'Ah, je suis désolé. Il n’y a pas d’eau chaude?', en: 'Oh, I’m sorry. Is there no hot water?' } },
        { you: { cue: 'Say no, there’s no hot water.', t: 'Non, il n’y a pas d’eau chaude.', en: 'No, there’s no hot water.',
          alt: ['Il n’y a pas d’eau chaude.', 'Non, pas d’eau chaude.', 'Y a pas d’eau chaude.'],
          gloss: 'non = no · il n’y a pas = there isn’t (il y a + ne … pas) · d’eau = any water · chaude = hot' } },
        { them: { t: 'Je vous envoie quelqu’un tout de suite.', en: 'I’ll send someone right away.' } },
        { you: { cue: 'Add that the air conditioning is very noisy.', t: 'Et la climatisation fait beaucoup de bruit.', en: 'And the air conditioning makes a lot of noise.',
          alt: ['Et la clim fait beaucoup de bruit.', 'La climatisation est très bruyante.', 'Et la clim fait du bruit.'],
          gloss: 'et = and · la climatisation = the air conditioning (la clim for short) · fait = makes (faire) · beaucoup de bruit = a lot of noise' } },
        { them: { t: 'Vous voulez changer de chambre?', en: 'Would you like to change rooms?' } },
        { you: { cue: 'Say yes, you’d like that, if it’s possible.', t: 'Oui, si c’est possible, je veux bien.', en: 'Yes, if it’s possible, I’d like that.',
          alt: ['Oui, si c’est possible.', 'Oui, je veux bien.'],
          gloss: 'oui = yes · si = if · c’est possible = it’s possible · je veux bien = I’d like that, gladly (vouloir + bien)' } }
      ]
    },
    {
      title: 'Lost luggage',
      scene: 'At the airport, your suitcase hasn’t come out. You go to the lost-luggage desk.',
      turns: [
        { you: { cue: 'Say hello and that your suitcase hasn’t arrived.', t: 'Bonjour, ma valise n’est pas arrivée.', en: 'Hello, my suitcase hasn’t arrived.',
          alt: ['Ma valise n’est pas arrivée.', 'Bonjour, j’ai perdu ma valise.', 'Ma valise est pas arrivée.'],
          gloss: 'bonjour = hello · ma valise = my suitcase · n’est pas arrivée = hasn’t arrived (arriver takes être in the past; -e because valise is feminine)' } },
        { them: { t: 'Vous avez votre carte d’embarquement?', en: 'Do you have your boarding pass?' } },
        { you: { cue: 'Hand it over and say you were on the London flight.', t: 'Oui, voilà. J’étais sur le vol de Londres.', en: 'Yes, here. I was on the London flight.',
          alt: ['Voilà, le vol de Londres.', 'Oui, voilà, le vol de Londres.'],
          gloss: 'oui, voilà = yes, here you are · j’étais = I was (être, imperfect) · sur = on · le vol = the flight · de Londres = from London' } },
        { them: { t: 'Elle est comment, votre valise?', en: 'What does your suitcase look like?' } },
        { you: { cue: 'Describe it: big and black, with a red ribbon.', t: 'Elle est grande et noire, avec un ruban rouge.', en: 'It’s big and black, with a red ribbon.',
          alt: ['Grande et noire, avec un ruban rouge.', 'Elle est grande, noire, avec un ruban rouge.'],
          gloss: 'elle est = it is · grande = big · et = and · noire = black (feminine) · avec = with · un ruban = a ribbon · rouge = red' } },
        { them: { t: 'D’accord. On va la retrouver. Vous restez où?', en: 'All right. We’ll find it. Where are you staying?' } },
        { you: { cue: 'Say at the Hotel Bellevue, for three nights.', t: 'À l’hôtel Bellevue, pour trois nuits.', en: 'At the Hotel Bellevue, for three nights.',
          alt: ['Hôtel Bellevue, trois nuits.', 'À l’hôtel Bellevue, pour 3 nuits.', 'Je suis à l’hôtel Bellevue.'],
          gloss: 'à l’hôtel = at the hotel · pour = for · trois nuits = three nights' } },
        { them: { t: 'On vous l’apporte à l’hôtel demain.', en: 'We’ll bring it to your hotel tomorrow.' } },
        { you: { cue: 'Ask them to call you when they have it.', t: 'Vous pouvez m’appeler quand vous l’avez?', en: 'Can you call me when you have it?',
          alt: ['Vous pouvez m’appeler?', 'Appelez-moi quand vous l’avez, s’il vous plaît.', 'Vous m’appelez quand vous l’avez?'],
          gloss: 'vous pouvez = you can · m’appeler = call me (me + appeler) · quand = when · vous l’avez = you have it (le = it)' } }
      ]
    },
    {
      title: 'Renting a car',
      scene: 'At a car-hire desk, you want a small car for a few days.',
      turns: [
        { you: { cue: 'Say hello and that you’d like to rent a car for three days.', t: 'Bonjour, je voudrais louer une voiture pour trois jours.', en: 'Hello, I’d like to rent a car for three days.',
          alt: ['Je voudrais louer une voiture pour trois jours.', 'Je voudrais louer une voiture pour 3 jours.', 'Je voudrais louer une voiture.'],
          gloss: 'bonjour = hello · je voudrais = I would like · louer = to rent · une voiture = a car · pour trois jours = for three days' } },
        { them: { t: 'Petite ou grande? Manuelle ou automatique?', en: 'Small or big? Manual or automatic?' } },
        { you: { cue: 'Ask for a small automatic.', t: 'Une petite voiture automatique, s’il vous plaît.', en: 'A small automatic car, please.',
          alt: ['Une petite automatique, s’il vous plaît.', 'Petite et automatique.'],
          gloss: 'une petite voiture = a small car (petite goes before the noun) · automatique = automatic · s’il vous plaît = please' } },
        { them: { t: 'Ça fait cent vingt euros, assurance comprise.', en: 'That’s a hundred and twenty euros, insurance included.' } },
        { you: { cue: 'Ask if you have to bring it back with a full tank.', t: 'Je dois rendre la voiture avec le plein?', en: 'Do I have to return the car with a full tank?',
          alt: ['Je dois faire le plein?', 'Il faut faire le plein avant de la rendre?'],
          gloss: 'je dois = I must (devoir) · rendre = to give back · la voiture = the car · avec le plein = with a full tank' } },
        { them: { t: 'Oui, sinon on vous facture l’essence.', en: 'Yes, otherwise we charge you for the petrol.' } },
        { you: { cue: 'Ask if you can return it at the airport.', t: 'Et je peux la rendre à l’aéroport?', en: 'And can I return it at the airport?',
          alt: ['Je peux la rendre à l’aéroport?', 'On peut la rendre à l’aéroport?'],
          gloss: 'et = and · je peux = I can · la = it (the car) · rendre = return · à l’aéroport = at the airport' } },
        { them: { t: 'Oui, c’est possible. Signez ici, s’il vous plaît.', en: 'Yes, that’s possible. Sign here, please.' } },
        { you: { cue: 'Sign, and ask where the car is parked.', t: 'Voilà. Elle est garée où?', en: 'There. Where is it parked?',
          alt: ['Voilà. Où est la voiture?', 'Elle est où, la voiture?', 'Elle est garée où, la voiture?'],
          gloss: 'voilà = there you go · elle = it (la voiture) · est garée = is parked (garer) · où = where' } }
      ]
    },
    {
      title: 'A mistake on the bill',
      scene: 'You check out of the hotel, and the bill doesn’t look right.',
      turns: [
        { you: { cue: 'Say you’d like to pay the bill for room thirty-two.', t: 'Bonjour, je voudrais régler la note, chambre trente-deux.', en: 'Hello, I’d like to settle the bill, room thirty-two.',
          alt: ['Je voudrais payer, chambre trente-deux.', 'Bonjour, je voudrais payer la chambre 32.'],
          gloss: 'je voudrais = I would like · régler = to settle, to pay · la note = the hotel bill · chambre trente-deux = room 32' } },
        { them: { t: 'Voilà votre facture: quatre cent vingt euros.', en: 'Here’s your invoice: four hundred and twenty euros.' } },
        { you: { cue: 'Say you think there’s a mistake.', t: 'Je crois qu’il y a une erreur.', en: 'I think there’s a mistake.',
          alt: ['Il y a une erreur, je crois.', 'Je pense qu’il y a une erreur.', 'Il y a une erreur.'],
          gloss: 'je crois = I believe, I think (croire) · qu’il y a = that there is · une erreur = a mistake' } },
        { them: { t: 'Ah bon? Laquelle?', en: 'Really? What mistake?' } },
        { you: { cue: 'Explain you booked three nights, not four.', t: 'On a réservé trois nuits, pas quatre.', en: 'We booked three nights, not four.',
          alt: ['Trois nuits, pas quatre.', 'On a réservé 3 nuits, pas 4.', 'On est restés trois nuits, pas quatre.'],
          gloss: 'on a réservé = we booked (on = we; passé composé) · trois nuits = three nights · pas quatre = not four' } },
        { them: { t: 'Vous avez raison, excusez-moi. Voilà la bonne facture.', en: 'You’re right, I’m sorry. Here’s the correct bill.' } },
        { you: { cue: 'Ask if you can leave your bags here until noon.', t: 'Merci. Je peux laisser mes bagages ici jusqu’à midi?', en: 'Thanks. Can I leave my bags here until noon?',
          alt: ['Je peux laisser mes bagages ici?', 'Je peux laisser mes valises jusqu’à midi?'],
          gloss: 'merci = thanks · je peux = I can · laisser = to leave · mes bagages = my bags · ici = here · jusqu’à midi = until noon' } },
        { them: { t: 'Bien sûr, à la bagagerie.', en: 'Of course, in the luggage room.' } },
        { you: { cue: 'Thank them for everything and say it was a great stay.', t: 'Merci pour tout, c’était un très bon séjour.', en: 'Thanks for everything, it was a very good stay.',
          alt: ['Merci pour tout!', 'Merci pour tout, c’était très bien.', 'C’était un très bon séjour, merci.'],
          gloss: 'merci pour tout = thanks for everything · c’était = it was · un très bon séjour = a very good stay' } }
      ]
    },

    /* ---------- 6. Small talk: family, work, hobbies, weather (tu arrives) ---------- */
    {
      title: 'Family on the train',
      scene: 'On a train, a friendly older woman starts chatting with you. Use vous with her.',
      turns: [
        { them: { t: 'Vous êtes en vacances en France?', en: 'Are you on holiday in France?' } },
        { you: { cue: 'Say yes, you’re on holiday with your family.', t: 'Oui, je suis en vacances avec ma famille.', en: 'Yes, I’m on holiday with my family.',
          alt: ['Oui, en vacances avec ma famille.', 'Oui, je suis en vacances en famille.'],
          gloss: 'oui = yes · je suis = I am · en vacances = on holiday · avec = with · ma famille = my family' } },
        { them: { t: 'Ah, c’est bien! Vous avez des enfants?', en: 'Oh, how nice! Do you have children?' } },
        { you: { cue: 'Say yes: two children, a boy and a girl.', t: 'Oui, j’ai deux enfants, un garçon et une fille.', en: 'Yes, I have two children, a boy and a girl.',
          alt: ['J’ai deux enfants, un garçon et une fille.', 'Oui, deux enfants: un garçon et une fille.', 'Oui, j’ai 2 enfants.'],
          gloss: 'j’ai = I have · deux enfants = two children · un garçon = a boy · et = and · une fille = a girl' } },
        { them: { t: 'Ils ont quel âge?', en: 'How old are they?' } },
        { you: { cue: 'Say your son is eight and your daughter is five.', t: 'Mon fils a huit ans et ma fille a cinq ans.', en: 'My son is eight and my daughter is five.',
          alt: ['Mon fils a 8 ans et ma fille a 5 ans.', 'Mon fils a huit ans, ma fille cinq.', 'Huit ans et cinq ans.'],
          gloss: 'mon fils = my son · a huit ans = is eight (French “has” years: avoir + ans) · ma fille = my daughter · cinq = five' } },
        { them: { t: 'Moi, j’ai trois petits-enfants. Ils habitent à Marseille.', en: 'I have three grandchildren. They live in Marseille.' } },
        { you: { cue: 'Ask if she sees them often.', t: 'Vous les voyez souvent?', en: 'Do you see them often?',
          alt: ['Vous les voyez beaucoup?', 'Et vous les voyez souvent?'],
          gloss: 'vous = you · les = them (before the verb) · voyez = see (voir) · souvent = often' } },
        { them: { t: 'Pas assez! Seulement l’été.', en: 'Not enough! Only in summer.' } },
        { you: { cue: 'Say that’s a shame — but summer is nice.', t: 'Ah, c’est dommage. Mais l’été, c’est bien.', en: 'Oh, that’s a shame. But summer is nice.',
          alt: ['C’est dommage.', 'Dommage, mais l’été, c’est bien.'],
          gloss: 'c’est dommage = that’s a pity · mais = but · l’été = summer · c’est bien = it’s nice' } }
      ]
    },
    {
      title: 'What do you do?',
      scene: 'At a dinner party, another guest asks what you do for a living. You work in IT.',
      turns: [
        { them: { t: 'Et vous, qu’est-ce que vous faites dans la vie?', en: 'And you, what do you do for a living?' } },
        { you: { cue: 'Say you work in IT, at a big company.', t: 'Je travaille dans l’informatique, dans une grande entreprise.', en: 'I work in IT, at a big company.',
          alt: ['Je travaille dans l’informatique.', 'Je suis dans l’informatique, dans une grande boîte.'],
          gloss: 'je travaille = I work (travailler) · dans = in · l’informatique = IT, computing · une grande entreprise = a big company' } },
        { them: { t: 'Ah, intéressant! Ça vous plaît?', en: 'Oh, interesting! Do you like it?' } },
        { you: { cue: 'Say you quite like it, but you work a lot.', t: 'Oui, j’aime bien, mais je travaille beaucoup.', en: 'Yes, I like it, but I work a lot.',
          alt: ['Oui, ça me plaît, mais je travaille beaucoup.', 'J’aime bien, mais je travaille beaucoup.'],
          gloss: 'oui = yes · j’aime bien = I quite like it · mais = but · je travaille beaucoup = I work a lot' } },
        { them: { t: 'Moi, je suis prof de maths dans un lycée.', en: 'I’m a maths teacher at a high school.' } },
        { you: { cue: 'Say that must be hard with teenagers, no?', t: 'Ça doit être difficile avec les ados, non?', en: 'That must be hard with teenagers, no?',
          alt: ['Ça doit être dur avec les ados.', 'C’est difficile avec les ados, non?'],
          gloss: 'ça doit être = that must be (devoir + être) · difficile = hard · avec = with · les ados = teenagers (adolescents) · non? = right?' } },
        { them: { t: 'Parfois! Mais j’adore mon travail. Vous travaillez le week-end?', en: 'Sometimes! But I love my job. Do you work weekends?' } },
        { you: { cue: 'Say no, luckily never at weekends.', t: 'Non, heureusement, jamais le week-end.', en: 'No, luckily, never at weekends.',
          alt: ['Non, jamais le week-end.', 'Non, pas le week-end.'],
          gloss: 'non = no · heureusement = luckily · jamais = never · le week-end = at the weekend' } },
        { them: { t: 'Vous avez de la chance!', en: 'You’re lucky!' } },
        { you: { cue: 'Agree, and say that at weekends you do sport.', t: 'Oui, et le week-end, je fais du sport.', en: 'Yes, and at weekends I do sport.',
          alt: ['Le week-end, je fais du sport.', 'Oui, le week-end je fais du sport.'],
          gloss: 'oui = yes · et = and · le week-end = at weekends · je fais du sport = I do sport (faire + du)' } }
      ]
    },
    {
      title: 'Shall we say tu?',
      scene: 'At your friend Marc’s barbecue you chat with Léa, who is your age. She suggests switching to tu.',
      turns: [
        { them: { t: 'Vous connaissez Marc depuis longtemps?', en: 'Have you known Marc long?' } },
        { you: { cue: 'Say for three years — you work together.', t: 'Depuis trois ans, on travaille ensemble.', en: 'For three years, we work together.',
          alt: ['Depuis trois ans. On travaille ensemble.', 'Depuis 3 ans, on travaille ensemble.'],
          gloss: 'depuis = for, since (with the present tense: still true now) · trois ans = three years · on travaille = we work · ensemble = together' } },
        { them: { t: 'Ah, super. On peut se tutoyer, non?', en: 'Oh, great. We can say tu to each other, right?' } },
        { you: { cue: 'Say yes, of course — let’s say tu.', t: 'Oui, bien sûr, on peut se tutoyer.', en: 'Yes, of course, let’s say tu.',
          alt: ['Oui, bien sûr!', 'Oui, on se tutoie.', 'Avec plaisir, on se tutoie.'],
          gloss: 'oui = yes · bien sûr = of course · on peut = we can · se tutoyer = to say tu to each other (vouvoyer = to say vous)' } },
        { them: { t: 'Cool. Alors, tu fais quoi le week-end?', en: 'Cool. So, what do you do at weekends?' } },
        { you: { cue: 'Say you like cycling and cooking.', t: 'J’aime bien faire du vélo et cuisiner.', en: 'I like cycling and cooking.',
          alt: ['J’aime faire du vélo et cuisiner.', 'Du vélo, et j’aime cuisiner.'],
          gloss: 'j’aime bien = I like · faire du vélo = to cycle (“do bike”) · et = and · cuisiner = to cook' } },
        { them: { t: 'Moi aussi, j’adore cuisiner!', en: 'Me too, I love cooking!' } },
        { you: { cue: 'Ask her — with tu — what she likes to cook.', t: 'Ah oui? Qu’est-ce que tu aimes cuisiner?', en: 'Oh yeah? What do you like to cook?',
          alt: ['Qu’est-ce que tu aimes cuisiner?', 'Tu aimes cuisiner quoi?', 'Tu cuisines quoi?'],
          gloss: 'ah oui? = oh really? · qu’est-ce que = what · tu aimes = you like (tu form: -es, silent) · cuisiner = to cook' } },
        { them: { t: 'Surtout des plats italiens. Tu habites dans le quartier?', en: 'Mostly Italian dishes. Do you live in the neighbourhood?' } },
        { you: { cue: 'Say no, you live a bit further away, near the station.', t: 'Non, j’habite un peu plus loin, près de la gare.', en: 'No, I live a bit further away, near the station.',
          alt: ['Non, j’habite près de la gare.', 'Non, j’habite plus loin, près de la gare.'],
          gloss: 'non = no · j’habite = I live (habiter) · un peu plus loin = a bit further · près de = near · la gare = the station' } }
      ]
    },
    {
      title: 'Rain at the bus stop',
      scene: 'You wait for the bus in the rain with an older neighbour. Use vous.',
      turns: [
        { them: { t: 'Quel temps, hein! Il pleut depuis ce matin.', en: 'What weather, eh! It’s been raining since this morning.' } },
        { you: { cue: 'Agree, and say it’s really cold for the time of year.', t: 'Oui, il fait vraiment froid pour la saison.', en: 'Yes, it’s really cold for the time of year.',
          alt: ['Oui, il fait froid pour la saison.', 'Il fait vraiment froid pour la saison.'],
          gloss: 'oui = yes · il fait = it is (weather uses faire) · vraiment = really · froid = cold · pour la saison = for the season' } },
        { them: { t: 'Ils ont dit qu’il va faire beau demain.', en: 'They said it’s going to be nice tomorrow.' } },
        { you: { cue: 'Say good — you’d like to go to the beach.', t: 'Tant mieux, je voudrais aller à la plage.', en: 'Good, I’d like to go to the beach.',
          alt: ['Tant mieux! Je veux aller à la plage.', 'Super, je voudrais aller à la plage.'],
          gloss: 'tant mieux = good, so much the better · je voudrais = I would like · aller = to go · à la plage = to the beach' } },
        { them: { t: 'Vous avez de la chance. Moi, je travaille.', en: 'You’re lucky. I’m working.' } },
        { you: { cue: 'Ask if he likes summer or prefers winter.', t: 'Vous aimez l’été ou vous préférez l’hiver?', en: 'Do you like summer, or do you prefer winter?',
          alt: ['Vous préférez l’été ou l’hiver?', 'Vous aimez mieux l’été ou l’hiver?'],
          gloss: 'vous aimez = you like · l’été = summer · ou = or · vous préférez = you prefer (préférer) · l’hiver = winter' } },
        { them: { t: 'L’automne! Les couleurs, les champignons…', en: 'Autumn! The colours, the mushrooms…' } },
        { you: { cue: 'Say you prefer summer, because you like the heat.', t: 'Moi, je préfère l’été, parce que j’aime la chaleur.', en: 'I prefer summer, because I like the heat.',
          alt: ['Moi, je préfère l’été, j’aime la chaleur.', 'Je préfère l’été parce que j’aime quand il fait chaud.'],
          gloss: 'moi = me (for emphasis) · je préfère = I prefer · l’été = summer · parce que = because · j’aime = I like · la chaleur = the heat' } },
        { them: { t: 'Ah, voilà le bus, enfin!', en: 'Ah, here’s the bus, at last!' } },
        { you: { cue: 'Say “at last!”, and see you soon.', t: 'Enfin! Allez, bonne journée, à bientôt.', en: 'At last! Well, have a nice day, see you soon.',
          alt: ['Bonne journée, à bientôt!', 'Enfin! À bientôt.'],
          gloss: 'enfin = at last · allez = well then (literally “go”, a filler to close a chat) · bonne journée = have a good day · à bientôt = see you soon' } }
      ]
    },
    {
      title: 'How was your weekend?',
      scene: 'On Monday, a colleague you say tu to asks about your weekend.',
      turns: [
        { them: { t: 'Salut! Tu as passé un bon week-end?', en: 'Hi! Did you have a good weekend?' } },
        { you: { cue: 'Say very good, thanks — you went to the seaside.', t: 'Oui, très bon, merci. Je suis allé à la mer.', en: 'Yes, very good, thanks. I went to the seaside.',
          alt: ['Oui, je suis allé à la mer.', 'Oui, très bon, merci. Je suis allée à la mer.', 'Très bon, je suis allé à la mer.'],
          gloss: 'très bon = very good · merci = thanks · je suis allé = I went (aller takes être in the past; allée for a woman, same sound) · à la mer = to the sea' } },
        { them: { t: 'Super! Tu as fait quoi?', en: 'Great! What did you do?' } },
        { you: { cue: 'Say you swam, read, and ate well.', t: 'J’ai nagé, j’ai lu et j’ai bien mangé.', en: 'I swam, I read and I ate well.',
          alt: ['J’ai nagé et j’ai lu.', 'J’ai nagé, lu, et bien mangé.'],
          gloss: 'j’ai nagé = I swam (nager) · j’ai lu = I read (lire, irregular: lu) · et = and · j’ai bien mangé = I ate well (manger)' } },
        { them: { t: 'Moi, j’ai joué au foot avec mon club.', en: 'I played football with my club.' } },
        { you: { cue: 'Ask him how long he’s played football.', t: 'Tu joues au foot depuis combien de temps?', en: 'How long have you played football?',
          alt: ['Depuis combien de temps tu joues au foot?', 'Tu joues depuis quand?'],
          gloss: 'tu joues = you play (jouer) · au foot = football (jouer à + le) · depuis combien de temps = for how long (French uses the present)' } },
        { them: { t: 'Depuis que j’ai six ans! Et toi, tu fais du sport?', en: 'Since I was six! And you, do you do any sport?' } },
        { you: { cue: 'Say a bit — you run twice a week.', t: 'Un peu, je cours deux fois par semaine.', en: 'A bit, I run twice a week.',
          alt: ['Je cours deux fois par semaine.', 'Un peu, je cours 2 fois par semaine.'],
          gloss: 'un peu = a bit · je cours = I run (courir) · deux fois = two times · par semaine = per week' } },
        { them: { t: 'On pourrait courir ensemble un jour!', en: 'We could go running together some day!' } },
        { you: { cue: 'Say good idea — why not Saturday morning?', t: 'Oui, bonne idée, pourquoi pas samedi matin?', en: 'Yes, good idea, why not Saturday morning?',
          alt: ['Bonne idée! Samedi matin?', 'Pourquoi pas samedi matin?'],
          gloss: 'oui = yes · bonne idée = good idea · pourquoi pas = why not · samedi matin = Saturday morning' } }
      ]
    },

    /* ---------- 7. Plans, invitations & time ---------- */
    {
      title: 'An invitation to dinner',
      scene: 'Your friend Léa phones to invite you over. You say tu to each other now.',
      turns: [
        { them: { t: 'Salut! Tu es libre samedi soir?', en: 'Hi! Are you free on Saturday evening?' } },
        { you: { cue: 'Say Saturday evening? — yes, you think you’re free.', t: 'Samedi soir? Oui, je crois que je suis libre.', en: 'Saturday evening? Yes, I think I’m free.',
          alt: ['Oui, je suis libre samedi soir.', 'Samedi soir? Je crois que oui.'],
          gloss: 'samedi soir = Saturday evening · oui = yes · je crois que = I think that · je suis libre = I am free' } },
        { them: { t: 'Je fais un dîner à la maison. Tu veux venir?', en: 'I’m having a dinner at home. Do you want to come?' } },
        { you: { cue: 'Accept with pleasure and say it’s very kind of her to invite you.', t: 'Avec plaisir! C’est très gentil de m’inviter, merci.', en: 'With pleasure! It’s very kind of you to invite me, thanks.',
          alt: ['Avec plaisir, merci!', 'Avec plaisir! C’est gentil de m’inviter.'],
          gloss: 'avec plaisir = with pleasure · c’est très gentil = it’s very kind · de m’inviter = to invite me · merci = thanks' } },
        { them: { t: 'Génial! Vers vingt heures, ça te va?', en: 'Great! Around eight, does that suit you?' } },
        { you: { cue: 'Say eight is perfect, and ask if you should bring something.', t: 'Vingt heures, c’est parfait. J’apporte quelque chose?', en: 'Eight o’clock is perfect. Shall I bring something?',
          alt: ['C’est parfait. Je peux apporter quelque chose?', '20 heures, c’est parfait. J’apporte quelque chose?'],
          gloss: 'vingt heures = 8 p.m. (French uses the 24-hour clock) · c’est parfait = it’s perfect · j’apporte = I bring (apporter) · quelque chose = something' } },
        { them: { t: 'Si tu veux, un dessert!', en: 'If you like, a dessert!' } },
        { you: { cue: 'Say OK, you’ll make an apple tart.', t: 'D’accord, je vais faire une tarte aux pommes.', en: 'OK, I’ll make an apple tart.',
          alt: ['OK, j’apporte une tarte aux pommes.', 'D’accord, je fais une tarte aux pommes.'],
          gloss: 'd’accord = OK · je vais faire = I’m going to make (aller + infinitive = near future) · une tarte aux pommes = an apple tart' } },
        { them: { t: 'Miam! Tu te souviens de l’adresse?', en: 'Yum! Do you remember the address?' } },
        { you: { cue: 'Say no, and ask her to text you the address.', t: 'Non, tu peux m’envoyer l’adresse par message?', en: 'No, can you text me the address?',
          alt: ['Tu peux m’envoyer l’adresse?', 'Non, envoie-moi l’adresse par message.'],
          gloss: 'non = no · tu peux = you can · m’envoyer = send me (me + envoyer) · l’adresse = the address · par message = by text' } }
      ]
    },
    {
      title: 'Plans for Sunday',
      scene: 'You and your friend Tom are deciding what to do on Sunday.',
      turns: [
        { you: { cue: 'Ask Tom what he wants to do on Sunday.', t: 'Tom, qu’est-ce que tu veux faire dimanche?', en: 'Tom, what do you want to do on Sunday?',
          alt: ['Qu’est-ce que tu veux faire dimanche?', 'Tu veux faire quoi dimanche?', 'On fait quoi dimanche?'],
          gloss: 'qu’est-ce que = what · tu veux = you want (vouloir) · faire = to do · dimanche = on Sunday' } },
        { them: { t: 'Je ne sais pas. On pourrait aller au cinéma?', en: 'I don’t know. We could go to the cinema?' } },
        { you: { cue: 'Say meh — it’s going to be nice, so you could go for a walk instead.', t: 'Bof, il va faire beau, on pourrait plutôt faire une balade.', en: 'Meh, it’s going to be nice, we could go for a walk instead.',
          alt: ['Il va faire beau, on pourrait faire une balade.', 'On pourrait plutôt se promener, il va faire beau.'],
          gloss: 'bof = meh · il va faire beau = it’s going to be nice (aller + faire) · on pourrait = we could (pouvoir, conditional) · plutôt = instead · faire une balade = go for a walk' } },
        { them: { t: 'Bonne idée! Au bord du lac?', en: 'Good idea! By the lake?' } },
        { you: { cue: 'Say yes, and you could have a picnic there at lunchtime.', t: 'Oui, et on pourrait pique-niquer là-bas à midi.', en: 'Yes, and we could have a picnic there at noon.',
          alt: ['Oui, on pourrait pique-niquer à midi.', 'Oui, et on pique-nique là-bas à midi.'],
          gloss: 'oui = yes · et = and · on pourrait = we could · pique-niquer = to picnic · là-bas = over there · à midi = at noon' } },
        { them: { t: 'Parfait. On se retrouve où, et à quelle heure?', en: 'Perfect. Where shall we meet, and what time?' } },
        { you: { cue: 'Suggest meeting in front of the station at ten.', t: 'On se retrouve devant la gare à dix heures?', en: 'Shall we meet in front of the station at ten?',
          alt: ['Devant la gare à dix heures?', 'On se retrouve devant la gare à 10 heures?', 'Rendez-vous devant la gare à dix heures?'],
          gloss: 'on se retrouve = we meet up (se retrouver) · devant = in front of · la gare = the station · à dix heures = at ten' } },
        { them: { t: 'Un peu tôt, non? Dix heures et demie?', en: 'A bit early, no? Half past ten?' } },
        { you: { cue: 'Agree: half past ten works.', t: 'D’accord, dix heures et demie, ça marche.', en: 'OK, half past ten, that works.',
          alt: ['Ça marche, dix heures et demie.', 'D’accord, 10 heures et demie.', 'D’accord, 10 h 30, ça marche.'],
          gloss: 'd’accord = OK · dix heures et demie = half past ten · ça marche = that works (literally “that walks”)' } }
      ]
    },
    {
      title: 'Running late',
      scene: 'You are on your way to meet Léa at a café, and you’re going to be late. You call her.',
      turns: [
        { them: { t: 'Allô? Tu es où?', en: 'Hello? Where are you?' } },
        { you: { cue: 'Say sorry, you’re late — the bus didn’t come.', t: 'Je suis désolé, je suis en retard, le bus n’est pas passé.', en: 'I’m sorry, I’m late, the bus didn’t come.',
          alt: ['Désolé, je suis en retard.', 'Je suis désolée, je suis en retard, le bus n’est pas passé.', 'Désolé, le bus est pas passé.'],
          gloss: 'je suis désolé = I’m sorry · je suis en retard = I’m late · le bus = the bus · n’est pas passé = didn’t come by (passer, with être)' } },
        { them: { t: 'Ah, zut. Tu arrives dans combien de temps?', en: 'Oh, bother. How long until you get here?' } },
        { you: { cue: 'Say in about twenty minutes — you’re taking a taxi.', t: 'Dans vingt minutes, à peu près, je prends un taxi.', en: 'In about twenty minutes, I’m taking a taxi.',
          alt: ['Dans vingt minutes à peu près.', 'Dans 20 minutes, je prends un taxi.'],
          gloss: 'dans = in (time from now) · vingt minutes = twenty minutes · à peu près = about · je prends = I’m taking (prendre) · un taxi = a taxi' } },
        { them: { t: 'D’accord. Je t’attends au café, alors.', en: 'OK. I’ll wait for you at the café, then.' } },
        { you: { cue: 'Tell her to order something — it’s on you, to say sorry.', t: 'Commande quelque chose, je t’invite pour m’excuser.', en: 'Order something, it’s on me, to say sorry.',
          alt: ['Commande quelque chose, c’est moi qui paie.', 'Prends quelque chose, je t’invite.'],
          gloss: 'commande = order (commander, tu command) · quelque chose = something · je t’invite = it’s my treat (“I invite you”) · pour m’excuser = to apologise' } },
        { them: { t: 'Ha ha, d’accord! Un grand café, alors.', en: 'Ha ha, OK! A large coffee, then.' } },
        { you: { cue: 'Say perfect — you’ll text her when you arrive.', t: 'Parfait. Je t’envoie un message quand j’arrive.', en: 'Perfect. I’ll text you when I arrive.',
          alt: ['Je t’envoie un message quand j’arrive.', 'Parfait, je t’écris quand j’arrive.'],
          gloss: 'parfait = perfect · je t’envoie = I send you (envoyer) · un message = a text · quand = when · j’arrive = I arrive' } },
        { them: { t: 'À tout de suite!', en: 'See you in a bit!' } },
        { you: { cue: 'Say see you in a bit, and sorry again.', t: 'À tout de suite, et encore désolé!', en: 'See you in a bit, and sorry again!',
          alt: ['À tout de suite!', 'À tout de suite, et encore désolée!', 'À tout à l’heure, désolé!'],
          gloss: 'à tout de suite = see you very soon · et = and · encore = again · désolé = sorry' } }
      ]
    },
    {
      title: 'Booking a table by phone',
      scene: 'You phone a restaurant to book a table for Friday night for four people.',
      turns: [
        { them: { t: 'Restaurant Le Jardin, bonjour!', en: 'Le Jardin restaurant, hello!' } },
        { you: { cue: 'Say you’d like to book a table for Friday evening.', t: 'Bonjour, je voudrais réserver une table pour vendredi soir.', en: 'Hello, I’d like to book a table for Friday evening.',
          alt: ['Je voudrais réserver une table pour vendredi soir.', 'Bonjour, c’est pour réserver une table vendredi soir.'],
          gloss: 'je voudrais = I would like · réserver = to book · une table = a table · pour vendredi soir = for Friday evening' } },
        { them: { t: 'Pour combien de personnes, et à quelle heure?', en: 'For how many people, and at what time?' } },
        { you: { cue: 'Say four people, around half past eight if possible.', t: 'Pour quatre personnes, vers vingt heures trente, si possible.', en: 'For four people, around 8:30 if possible.',
          alt: ['Pour 4 personnes, vers 20 h 30.', 'Quatre personnes, vers vingt heures trente.', 'Pour quatre, vers huit heures et demie.'],
          gloss: 'pour quatre personnes = for four people · vers = around · vingt heures trente = 20:30 · si possible = if possible' } },
        { them: { t: 'Vingt heures trente, c’est complet. Vingt et une heures, ça vous va?', en: '8:30 is full. Would nine o’clock suit you?' } },
        { you: { cue: 'Accept nine o’clock — it suits you all very well.', t: 'Oui, vingt et une heures, ça nous va très bien.', en: 'Yes, nine o’clock suits us very well.',
          alt: ['Oui, 21 heures, ça nous va.', 'Vingt et une heures, ça va.', 'D’accord, 21 heures.'],
          gloss: 'vingt et une heures = 21:00 · ça nous va = that suits us (aller: “it goes for us”) · très bien = very well' } },
        { them: { t: 'C’est à quel nom?', en: 'What name is it under?' } },
        { you: { cue: 'Give the name Martin.', t: 'C’est au nom de Martin.', en: 'It’s under the name Martin.',
          alt: ['Au nom de Martin.', 'Martin.'],
          gloss: 'c’est = it is · au nom de = in the name of' } },
        { them: { t: 'Très bien, c’est noté.', en: 'Very good, that’s booked.' } },
        { you: { cue: 'Ask if there are vegetarian dishes on the menu.', t: 'Est-ce qu’il y a des plats végétariens sur la carte?', en: 'Are there vegetarian dishes on the menu?',
          alt: ['Il y a des plats végétariens?', 'Vous avez des plats végétariens?'],
          gloss: 'est-ce qu’ = question opener (“is it that”) · il y a = there are · des plats = dishes · végétariens = vegetarian · sur la carte = on the menu' } },
        { them: { t: 'Oui, plusieurs.', en: 'Yes, several.' } },
        { you: { cue: 'Say perfect, thanks, see you Friday then.', t: 'Parfait, merci beaucoup, à vendredi alors.', en: 'Perfect, thank you very much, see you Friday then.',
          alt: ['Merci, à vendredi!', 'Parfait, à vendredi.'],
          gloss: 'parfait = perfect · merci beaucoup = thanks a lot · à vendredi = see you Friday · alors = then' } }
      ]
    },
    {
      title: 'Changing plans',
      scene: 'Tom can’t make Saturday any more. You call him to find another day.',
      turns: [
        { them: { t: 'Salut! Désolé pour samedi, j’ai un problème avec ma voiture.', en: 'Hi! Sorry about Saturday, I’ve got a problem with my car.' } },
        { you: { cue: 'Say no worries, it happens — can you do it another day?', t: 'Pas de souci, ça arrive. On peut remettre à un autre jour?', en: 'No worries, it happens. Can we put it off to another day?',
          alt: ['Pas de problème. On peut faire ça un autre jour?', 'Pas de souci, on remet à un autre jour?'],
          gloss: 'pas de souci = no worries · ça arrive = it happens · on peut = we can · remettre = to postpone · à un autre jour = to another day' } },
        { them: { t: 'Oui! Tu es libre la semaine prochaine?', en: 'Yes! Are you free next week?' } },
        { you: { cue: 'Say Monday and Tuesday you work late, but Wednesday is fine.', t: 'Lundi et mardi, je travaille tard, mais mercredi, ça va.', en: 'Monday and Tuesday I work late, but Wednesday is fine.',
          alt: ['Lundi et mardi je travaille tard, mais mercredi ça va.', 'Je suis libre mercredi.'],
          gloss: 'lundi = Monday · mardi = Tuesday · je travaille tard = I work late · mais = but · mercredi = Wednesday · ça va = that’s fine' } },
        { them: { t: 'Mercredi, je ne peux pas. Jeudi soir?', en: 'Wednesday I can’t. Thursday evening?' } },
        { you: { cue: 'Say Thursday evening works, and invite him to your place.', t: 'Jeudi soir, c’est bon pour moi. Tu veux venir chez moi?', en: 'Thursday evening is good for me. Do you want to come to my place?',
          alt: ['Jeudi soir, c’est bon. Tu viens chez moi?', 'Jeudi, ça marche. Tu veux venir chez moi?'],
          gloss: 'jeudi soir = Thursday evening · c’est bon pour moi = that’s good for me · tu veux = you want · venir = to come · chez moi = to my place' } },
        { them: { t: 'Avec plaisir! J’apporte le vin.', en: 'With pleasure! I’ll bring the wine.' } },
        { you: { cue: 'Say great, and you’ll make something simple.', t: 'Super, et je vais préparer quelque chose de simple.', en: 'Great, and I’ll make something simple.',
          alt: ['Super, je fais quelque chose de simple.', 'Génial, je vais cuisiner quelque chose de simple.'],
          gloss: 'super = great · et = and · je vais préparer = I’m going to make · quelque chose de simple = something simple (quelque chose + de + adjective)' } },
        { them: { t: 'Parfait. À jeudi, alors!', en: 'Perfect. See you Thursday, then!' } },
        { you: { cue: 'Say see you Thursday, and good luck with his car.', t: 'À jeudi! Et bon courage avec ta voiture.', en: 'See you Thursday! And good luck with your car.',
          alt: ['À jeudi, bon courage pour la voiture!', 'À jeudi!'],
          gloss: 'à jeudi = see you Thursday · et = and · bon courage = good luck, hang in there · avec = with · ta voiture = your car (tu form: ta)' } }
      ]
    },

    /* ---------- 8. Past experiences, health & opinions — ending with a story ---------- */
    {
      title: 'At the doctor’s',
      scene: 'You fall ill on holiday and go to see a doctor.',
      turns: [
        { them: { t: 'Bonjour. Alors, qu’est-ce qui ne va pas?', en: 'Hello. So, what’s wrong?' } },
        { you: { cue: 'Say you’ve had a headache and a temperature since yesterday.', t: 'J’ai mal à la tête et j’ai de la fièvre depuis hier.', en: 'I’ve had a headache and a temperature since yesterday.',
          alt: ['J’ai mal à la tête et de la fièvre depuis hier.', 'J’ai mal à la tête et de la fièvre.'],
          gloss: 'j’ai mal à la tête = I have a headache (“I have pain at the head”) · et = and · j’ai de la fièvre = I have a fever · depuis hier = since yesterday' } },
        { them: { t: 'Vous avez mal à la gorge aussi?', en: 'Do you have a sore throat too?' } },
        { you: { cue: 'Say yes, a bit, and you’ve been very tired for two days.', t: 'Oui, un peu, et je suis très fatigué depuis deux jours.', en: 'Yes, a bit, and I’ve been very tired for two days.',
          alt: ['Oui, un peu, et je suis très fatiguée depuis deux jours.', 'Oui, un peu. Je suis très fatigué.'],
          gloss: 'oui = yes · un peu = a bit · et = and · je suis très fatigué = I am very tired (fatiguée for a woman, same sound) · depuis deux jours = for two days' } },
        { them: { t: 'Vous prenez des médicaments?', en: 'Are you taking any medicine?' } },
        { you: { cue: 'Say you took paracetamol this morning, but it didn’t work.', t: 'J’ai pris du paracétamol ce matin, mais ça n’a pas marché.', en: 'I took paracetamol this morning, but it didn’t work.',
          alt: ['J’ai pris du paracétamol ce matin.', 'Du paracétamol ce matin, mais ça a pas marché.'],
          gloss: 'j’ai pris = I took (prendre → pris) · du paracétamol = some paracetamol · ce matin = this morning · mais = but · ça n’a pas marché = it didn’t work' } },
        { them: { t: 'Vous êtes allergique à quelque chose?', en: 'Are you allergic to anything?' } },
        { you: { cue: 'Say no, you’re not allergic to anything, as far as you know.', t: 'Non, je ne suis allergique à rien, à ma connaissance.', en: 'No, I’m not allergic to anything, as far as I know.',
          alt: ['Non, je ne suis allergique à rien.', 'Non, je suis allergique à rien.', 'Non, à rien.'],
          gloss: 'non = no · je ne suis … à rien = I am … to nothing (ne … rien = nothing) · allergique = allergic · à ma connaissance = to my knowledge' } },
        { them: { t: 'Bon. C’est la grippe. Reposez-vous et buvez beaucoup d’eau.', en: 'Right. It’s flu. Rest and drink plenty of water.' } },
        { you: { cue: 'Ask roughly how many days you have to stay in bed.', t: 'Je dois rester au lit combien de jours, à peu près?', en: 'How many days do I have to stay in bed, roughly?',
          alt: ['Je dois rester au lit combien de temps?', 'Combien de jours au lit?'],
          gloss: 'je dois = I must (devoir) · rester = to stay · au lit = in bed · combien de jours = how many days · à peu près = roughly' } }
      ]
    },
    {
      title: 'Back from Provence',
      scene: 'Back home, your friend Léa asks about your holiday in Provence. Tell her in the past.',
      turns: [
        { them: { t: 'Alors, c’était comment, la Provence?', en: 'So, how was Provence?' } },
        { you: { cue: 'Say it was great — you visited lots of little villages.', t: 'C’était génial! On a visité plein de petits villages.', en: 'It was great! We visited lots of little villages.',
          alt: ['C’était super, on a visité beaucoup de villages.', 'Génial! On a visité plein de villages.'],
          gloss: 'c’était génial = it was great (imperfect: how it was) · on a visité = we visited (passé composé: what happened) · plein de = lots of · petits villages = little villages' } },
        { them: { t: 'Vous êtes restés combien de temps?', en: 'How long did you stay?' } },
        { you: { cue: 'Say ten days — you rented a house near Avignon.', t: 'Dix jours. On a loué une maison près d’Avignon.', en: 'Ten days. We rented a house near Avignon.',
          alt: ['Dix jours, dans une maison près d’Avignon.', '10 jours. On a loué une maison près d’Avignon.'],
          gloss: 'dix jours = ten days · on a loué = we rented (louer) · une maison = a house · près d’Avignon = near Avignon' } },
        { them: { t: 'Et il a fait beau?', en: 'And was the weather good?' } },
        { you: { cue: 'Say it was very hot — thirty-five degrees some days.', t: 'Oui, il a fait très chaud, trente-cinq degrés certains jours.', en: 'Yes, it was very hot, thirty-five degrees some days.',
          alt: ['Oui, très chaud, trente-cinq degrés.', 'Il a fait très chaud, 35 degrés certains jours.'],
          gloss: 'il a fait très chaud = it was very hot (faire, passé composé) · trente-cinq degrés = 35 degrees · certains jours = some days' } },
        { them: { t: 'Qu’est-ce que tu as préféré?', en: 'What did you like best?' } },
        { you: { cue: 'Say you loved the Saturday-morning market, with all the cheeses.', t: 'J’ai adoré le marché le samedi matin, avec tous les fromages.', en: 'I loved the market on Saturday morning, with all the cheeses.',
          alt: ['J’ai adoré le marché du samedi matin.', 'J’ai adoré le marché, avec tous les fromages.'],
          gloss: 'j’ai adoré = I loved (adorer) · le marché = the market · le samedi matin = on Saturday mornings · avec = with · tous les fromages = all the cheeses' } },
        { them: { t: 'Ça donne envie! Tu y retournerais?', en: 'That makes me want to go! Would you go back?' } },
        { you: { cue: 'Say yes, without hesitating — but maybe in spring, when it’s less hot.', t: 'Oui, sans hésiter, mais peut-être au printemps, quand il fait moins chaud.', en: 'Yes, without hesitation, but maybe in spring, when it’s less hot.',
          alt: ['Oui, sans hésiter, mais au printemps.', 'Oui, mais plutôt au printemps, quand il fait moins chaud.'],
          gloss: 'oui = yes · sans hésiter = without hesitating · mais = but · peut-être = maybe · au printemps = in spring · quand = when · il fait moins chaud = it’s less hot' } }
      ]
    },
    {
      title: 'What did you think of the film?',
      scene: 'Coming out of the cinema, your friend asks what you thought of the film.',
      turns: [
        { them: { t: 'Alors, tu as aimé le film?', en: 'So, did you like the film?' } },
        { you: { cue: 'Say honestly you liked it, but you found it a bit long.', t: 'Franchement, j’ai bien aimé, mais je l’ai trouvé un peu long.', en: 'Honestly, I liked it, but I found it a bit long.',
          alt: ['J’ai bien aimé, mais c’était un peu long.', 'Franchement, pas mal, mais un peu long.'],
          gloss: 'franchement = honestly · j’ai bien aimé = I liked it · mais = but · je l’ai trouvé = I found it (le + avoir + trouvé) · un peu long = a bit long' } },
        { them: { t: 'Ah bon? Moi, je l’ai trouvé super du début à la fin.', en: 'Really? I found it great from start to finish.' } },
        { you: { cue: 'Say the actors were very good, especially the lead actress.', t: 'Les acteurs étaient très bons, surtout l’actrice principale.', en: 'The actors were very good, especially the lead actress.',
          alt: ['Les acteurs étaient très bons.', 'Les acteurs étaient super, surtout l’actrice principale.'],
          gloss: 'les acteurs = the actors · étaient = were (être, imperfect: describing) · très bons = very good · surtout = especially · l’actrice principale = the lead actress' } },
        { them: { t: 'Oui, elle est incroyable. Et la fin, tu l’as comprise?', en: 'Yes, she’s amazing. And the ending — did you understand it?' } },
        { you: { cue: 'Say not really — you didn’t understand why he left.', t: 'Pas vraiment, je n’ai pas compris pourquoi il est parti.', en: 'Not really, I didn’t understand why he left.',
          alt: ['Pas vraiment, j’ai pas compris pourquoi il est parti.', 'Non, je n’ai pas compris la fin.'],
          gloss: 'pas vraiment = not really · je n’ai pas compris = I didn’t understand (comprendre → compris) · pourquoi = why · il est parti = he left (partir takes être)' } },
        { them: { t: 'Moi non plus! Je pense qu’il avait peur.', en: 'Me neither! I think he was scared.' } },
        { you: { cue: 'Give your view: you think he mainly wanted to protect his family.', t: 'À mon avis, il voulait surtout protéger sa famille.', en: 'In my opinion, he mainly wanted to protect his family.',
          alt: ['À mon avis, il voulait protéger sa famille.', 'Je pense qu’il voulait protéger sa famille.'],
          gloss: 'à mon avis = in my opinion · il voulait = he wanted (vouloir, imperfect) · surtout = above all · protéger = to protect · sa famille = his family' } },
        { them: { t: 'Ah, c’est possible. On va boire un verre pour en parler?', en: 'Oh, could be. Shall we get a drink and talk about it?' } },
        { you: { cue: 'Say with pleasure — you know a nice bar not far from here.', t: 'Avec plaisir, je connais un bar sympa pas loin d’ici.', en: 'With pleasure, I know a nice bar not far from here.',
          alt: ['Avec plaisir, je connais un bar sympa.', 'Oui, je connais un bar sympa pas loin.'],
          gloss: 'avec plaisir = with pleasure · je connais = I know (connaître: people and places) · un bar sympa = a nice bar · pas loin d’ici = not far from here' } }
      ]
    },
    {
      title: 'What happened to your hand?',
      scene: 'A friend sees the bandage on your hand and asks what happened.',
      turns: [
        { them: { t: 'Oh là là! Qu’est-ce qui t’est arrivé à la main?', en: 'Oh dear! What happened to your hand?' } },
        { you: { cue: 'Say you fell off your bike on Saturday, coming home from work.', t: 'Je suis tombé à vélo samedi, en rentrant du travail.', en: 'I fell off my bike on Saturday, coming home from work.',
          alt: ['Je suis tombée à vélo samedi, en rentrant du travail.', 'Je suis tombé à vélo samedi.', 'Je suis tombé de vélo samedi.'],
          gloss: 'je suis tombé = I fell (tomber takes être; tombée for a woman) · à vélo = on my bike · samedi = on Saturday · en rentrant = while going home · du travail = from work' } },
        { them: { t: 'Aïe! Comment c’est arrivé?', en: 'Ouch! How did it happen?' } },
        { you: { cue: 'Explain: it was raining, the road was slippery, and a car braked in front of you.', t: 'Il pleuvait, la route était glissante, et une voiture a freiné devant moi.', en: 'It was raining, the road was slippery, and a car braked in front of me.',
          alt: ['Il pleuvait, et une voiture a freiné devant moi.', 'Il pleuvait, la route était glissante et une voiture a freiné.'],
          gloss: 'il pleuvait = it was raining (imperfect: the background) · la route était glissante = the road was slippery · une voiture a freiné = a car braked (passé composé: the event) · devant moi = in front of me' } },
        { them: { t: 'Tu es allé à l’hôpital?', en: 'Did you go to hospital?' } },
        { you: { cue: 'Say yes, you waited three hours in A&E — it was long.', t: 'Oui, j’ai attendu trois heures aux urgences, c’était long.', en: 'Yes, I waited three hours in A&E, it was long.',
          alt: ['Oui, j’ai attendu trois heures aux urgences.', 'Oui, j’ai attendu 3 heures aux urgences.'],
          gloss: 'oui = yes · j’ai attendu = I waited (attendre) · trois heures = three hours · aux urgences = in A&E, the emergency room · c’était long = it was long' } },
        { them: { t: 'Et c’est cassé?', en: 'And is it broken?' } },
        { you: { cue: 'Say luckily it’s not broken — it’s just a sprain.', t: 'Non, heureusement, ce n’est pas cassé, c’est juste une entorse.', en: 'No, luckily it’s not broken, it’s just a sprain.',
          alt: ['Non, c’est juste une entorse.', 'Heureusement, c’est pas cassé, c’est juste une entorse.'],
          gloss: 'non = no · heureusement = luckily · ce n’est pas cassé = it isn’t broken · c’est juste = it’s just · une entorse = a sprain' } },
        { them: { t: 'Ouf! Tu as besoin d’aide pour quelque chose?', en: 'Phew! Do you need help with anything?' } },
        { you: { cue: 'Say that’s kind — maybe with the shopping this week.', t: 'C’est gentil, peut-être pour faire les courses cette semaine.', en: 'That’s kind, maybe for the shopping this week.',
          alt: ['C’est gentil, peut-être pour les courses.', 'Merci, peut-être pour faire les courses cette semaine.'],
          gloss: 'c’est gentil = that’s kind · peut-être = maybe · pour faire les courses = to do the (food) shopping · cette semaine = this week' } }
      ]
    },
    {
      title: 'The story of my first trip',
      scene: 'At dinner, your friends ask you to tell the story of your first trip to France.',
      turns: [
        { them: { t: 'Allez, raconte-nous ton premier voyage en France!', en: 'Come on, tell us about your first trip to France!' } },
        { you: { cue: 'Start the story: the first time was ten years ago, in Paris, with friends.', t: 'La première fois, c’était il y a dix ans, à Paris, avec des amis.', en: 'The first time was ten years ago, in Paris, with friends.',
          alt: ['C’était il y a dix ans, à Paris, avec des amis.', 'La première fois, c’était il y a 10 ans, à Paris.'],
          gloss: 'la première fois = the first time · c’était = it was · il y a dix ans = ten years ago · à Paris = in Paris · avec des amis = with friends' } },
        { them: { t: 'Et alors, ça s’est bien passé?', en: 'And so, did it go well?' } },
        { you: { cue: 'Say not at all — on the first day you lost your passport on the metro.', t: 'Pas du tout! Le premier jour, j’ai perdu mon passeport dans le métro.', en: 'Not at all! On the first day, I lost my passport on the metro.',
          alt: ['Le premier jour, j’ai perdu mon passeport dans le métro.', 'Pas du tout, j’ai perdu mon passeport le premier jour.'],
          gloss: 'pas du tout = not at all · le premier jour = on the first day · j’ai perdu = I lost (perdre) · mon passeport = my passport · dans le métro = on the metro' } },
        { them: { t: 'Non! Qu’est-ce que tu as fait?', en: 'No! What did you do?' } },
        { you: { cue: 'Say you went to the police station, but you didn’t speak any French.', t: 'Je suis allé au commissariat, mais je ne parlais pas du tout français.', en: 'I went to the police station, but I didn’t speak any French at all.',
          alt: ['Je suis allée au commissariat, mais je ne parlais pas du tout français.', 'Je suis allé au commissariat, mais je parlais pas français.'],
          gloss: 'je suis allé = I went (être + allé) · au commissariat = to the police station · mais = but · je ne parlais pas = I didn’t speak (imperfect: a state) · du tout = at all · français = French' } },
        { them: { t: 'Oh là là! Et on l’a retrouvé?', en: 'Oh dear! And did they find it?' } },
        { you: { cue: 'Say yes: the next day a very kind man brought it back to the hotel.', t: 'Oui, le lendemain, un monsieur très gentil l’a rapporté à l’hôtel.', en: 'Yes, the next day a very kind man brought it back to the hotel.',
          alt: ['Oui, le lendemain, quelqu’un l’a rapporté à l’hôtel.', 'Oui, un monsieur l’a rapporté à l’hôtel le lendemain.'],
          gloss: 'le lendemain = the next day · un monsieur très gentil = a very kind man · l’a rapporté = brought it back (le + a + rapporté) · à l’hôtel = to the hotel' } },
        { them: { t: 'Quelle chance! C’est pour ça que tu as appris le français?', en: 'How lucky! Is that why you learned French?' } },
        { you: { cue: 'Say exactly — you wanted to be able to thank him in his own language.', t: 'Exactement, je voulais pouvoir le remercier dans sa langue.', en: 'Exactly, I wanted to be able to thank him in his language.',
          alt: ['Oui, je voulais pouvoir le remercier en français.', 'Exactement, je voulais le remercier dans sa langue.'],
          gloss: 'exactement = exactly · je voulais = I wanted (imperfect) · pouvoir = to be able to · le remercier = to thank him · dans sa langue = in his language' } }
      ]
    }
  ]
};
