/* Talk mode — Spanish: 40 spoken dialogs, from greetings to telling a story.
   8 themes of 5 levels: greetings → café & restaurant → numbers & shopping → directions & transport →
   hotel & problems → small talk → plans & invitations → past, health & opinions.
   Spain’s everyday forms in `t`; the Latin American form in `alt` where they differ.
   Usted with strangers and older people, tú with friends (introduced in level 3). */
HS.talk = HS.talk || {};
HS.talk.spanish = {
  lang: 'es-ES',
  levels: [
    /* ---------- 1. Greetings & introductions ---------- */
    {
      title: 'Good morning',
      scene: 'You walk into a small shop in the morning and greet the shopkeeper.',
      turns: [
        { them: { t: '¡Buenos días!', en: 'Good morning!' } },
        { you: { cue: 'Say: Good morning!', t: '¡Buenos días!', en: 'Good morning!',
          alt: ['Hola, buenos días', 'Buen día'],
          gloss: 'buenos = good (plural) · días = days — said until lunchtime, about 2 pm in Spain · in Argentina and Uruguay people also say “buen día”' } },
        { them: { t: '¿Qué tal?', en: 'How’s it going?' } },
        { you: { cue: 'Say: Fine, thanks.', t: 'Bien, gracias.', en: 'Fine, thanks.',
          alt: ['Muy bien, gracias', 'Bien'],
          gloss: 'bien = well / fine · gracias = thank you' } },
        { them: { t: 'Aquí tiene.', en: 'Here you are.' } },
        { you: { cue: 'Say: Thank you very much.', t: 'Muchas gracias.', en: 'Thank you very much.',
          alt: ['Gracias', 'Mil gracias'],
          gloss: 'muchas = many (feminine plural, agreeing with gracias) · gracias = thanks' } },
        { them: { t: 'De nada. ¡Adiós!', en: 'You’re welcome. Bye!' } },
        { you: { cue: 'Say: See you later!', t: '¡Hasta luego!', en: 'See you later!',
          alt: ['Adiós, hasta luego', 'Adiós'],
          gloss: 'hasta = until · luego = later — the everyday “bye”, even if you won’t see them again' } }
      ]
    },
    {
      title: 'Good afternoon, señora',
      scene: 'An older neighbour greets you in the afternoon; with her you use the polite “usted”.',
      turns: [
        { them: { t: 'Buenas tardes.', en: 'Good afternoon.' } },
        { you: { cue: 'Say: Good afternoon, madam.', t: 'Buenas tardes, señora.', en: 'Good afternoon, madam.',
          alt: ['Buenas tardes', 'Hola, buenas tardes'],
          gloss: 'buenas = good (feminine plural) · tardes = afternoons — from lunch until dark · señora = madam / Mrs' } },
        { them: { t: '¿Cómo está usted?', en: 'How are you?' } },
        { you: { cue: 'Say: Very well. And you?', t: 'Muy bien. ¿Y usted?', en: 'Very well. And you?',
          alt: ['Muy bien, gracias. ¿Y usted?', 'Bien, ¿y usted?'],
          gloss: 'muy = very · bien = well · y = and · usted = you (polite form, for strangers and older people)' } },
        { them: { t: 'Bien, gracias. ¿Cómo se llama?', en: 'Fine, thanks. What’s your name?' } },
        { you: { cue: 'Say: My name is Alex.', t: 'Me llamo Alex.', en: 'My name is Alex.',
          alt: ['Soy Alex', 'Alex'],
          gloss: 'me = myself · llamo = I call (llamar, “to call”) — literally “I call myself Alex”' } },
        { them: { t: 'Yo soy Carmen. Encantada.', en: 'I’m Carmen. Pleased to meet you.' } },
        { you: { cue: 'Say: Pleased to meet you.', t: 'Encantado.', en: 'Pleased to meet you.',
          alt: ['Encantada', 'Mucho gusto'],
          gloss: 'encantado = delighted — a man says encantado, a woman encantada · “mucho gusto” (much pleasure) means the same and is more common in Latin America' } }
      ]
    },
    {
      title: 'Hi, I’m Alex',
      scene: 'At a party, someone your age says hello; with people your age you use the friendly “tú”.',
      turns: [
        { them: { t: '¡Hola! ¿Qué tal?', en: 'Hi! How’s it going?' } },
        { you: { cue: 'Say: Fine. And you? — using the friendly “tú”.', t: 'Bien, ¿y tú?', en: 'Fine, and you?',
          alt: ['Bien, gracias, ¿y tú?', 'Muy bien, ¿y tú?'],
          gloss: 'bien = fine · y = and · tú = you (informal: friends, family, people your age; usted is the polite form)' } },
        { them: { t: 'Genial. ¿Cómo te llamas?', en: 'Great. What’s your name?' } },
        { you: { cue: 'Say: I’m Alex. And you?', t: 'Soy Alex. ¿Y tú?', en: 'I’m Alex. And you?',
          alt: ['Me llamo Alex, ¿y tú?', 'Alex, ¿y tú?'],
          gloss: 'soy = I am (ser, “to be”) · y = and · tú = you (informal)' } },
        { them: { t: 'Me llamo Javi.', en: 'My name is Javi.' } },
        { you: { cue: 'Say: Pleased to meet you.', t: 'Encantado.', en: 'Pleased to meet you.',
          alt: ['Encantada', 'Mucho gusto'],
          gloss: 'encantado = delighted (a woman says encantada) · mucho gusto = much pleasure, the same thing' } },
        { them: { t: '¿De dónde eres?', en: 'Where are you from?' } },
        { you: { cue: 'Say: I’m from London.', t: 'Soy de Londres.', en: 'I’m from London.',
          alt: ['De Londres'],
          gloss: 'soy = I am (ser, used for origin) · de = from · Londres = London' } }
      ]
    },
    {
      title: 'Sorry, I don’t understand',
      scene: 'A stranger in the street asks you something very fast.',
      turns: [
        { them: { t: 'Perdone, ¿tiene hora?', en: 'Excuse me, do you have the time?' } },
        { you: { cue: 'Say: Sorry, I don’t understand.', t: 'Lo siento, no entiendo.', en: 'Sorry, I don’t understand.',
          alt: ['Perdone, no entiendo', 'No entiendo'],
          gloss: 'lo = it · siento = I feel (sentir) — “lo siento” = I’m sorry · no = not · entiendo = I understand (entender)' } },
        { them: { t: '¿Tiene hora?', en: 'Do you have the time?' } },
        { you: { cue: 'Ask: Do you speak English?', t: '¿Habla inglés?', en: 'Do you speak English?',
          alt: ['¿Habla usted inglés?', 'Perdone, ¿habla inglés?'],
          gloss: 'habla = you speak (hablar, usted form — also “he/she speaks”) · inglés = English' } },
        { them: { t: 'No, lo siento.', en: 'No, sorry.' } },
        { you: { cue: 'Say: More slowly, please.', t: 'Más despacio, por favor.', en: 'More slowly, please.',
          alt: ['Más despacio', 'Despacio, por favor'],
          gloss: 'más = more · despacio = slowly · por favor = please (literally “for favour”)' } },
        { them: { t: '¿Qué... hora... es?', en: 'What... time... is it?' } },
        { you: { cue: 'Say: Ah, one moment.', t: 'Ah, un momento.', en: 'Ah, one moment.',
          alt: ['Un momento', 'Ah, sí, un momento'],
          gloss: 'ah = oh · un = one / a · momento = moment' } },
        { them: { t: 'Vale, gracias.', en: 'OK, thanks.' } },
        { you: { cue: 'Say: You’re welcome.', t: 'De nada.', en: 'You’re welcome.',
          alt: ['No hay de qué'],
          gloss: 'de = of · nada = nothing — “it’s nothing”' } }
      ]
    },
    {
      title: 'See you tomorrow',
      scene: 'On your first day at a language school, the teacher says hello.',
      turns: [
        { them: { t: 'Buenos días. Soy Lucía, la profesora.', en: 'Good morning. I’m Lucía, the teacher.' } },
        { you: { cue: 'Say: Good morning, I’m Alex.', t: 'Buenos días, soy Alex.', en: 'Good morning, I’m Alex.',
          alt: ['Buenos días, me llamo Alex', 'Hola, soy Alex'],
          gloss: 'buenos días = good morning · soy = I am (ser)' } },
        { them: { t: 'Encantada. ¿De dónde eres?', en: 'Pleased to meet you. Where are you from?' } },
        { you: { cue: 'Say: I’m from London.', t: 'Soy de Londres.', en: 'I’m from London.',
          alt: ['De Londres'],
          gloss: 'soy = I am · de = from · Londres = London' } },
        { them: { t: '¿Hablas español?', en: 'Do you speak Spanish?' } },
        { you: { cue: 'Say: Yes, a little.', t: 'Sí, un poco.', en: 'Yes, a little.',
          alt: ['Un poco', 'Sí, un poquito'],
          gloss: 'sí = yes · un = a · poco = little (un poquito = a tiny bit)' } },
        { them: { t: '¡Muy bien! Hasta mañana.', en: 'Very good! See you tomorrow.' } },
        { you: { cue: 'Say: See you tomorrow!', t: '¡Hasta mañana!', en: 'See you tomorrow!',
          alt: ['Adiós, hasta mañana'],
          gloss: 'hasta = until · mañana = tomorrow (la mañana = the morning)' } }
      ]
    },

    /* ---------- 2. Café & restaurant ---------- */
    {
      title: 'A coffee, please',
      scene: 'You walk up to the bar of a busy café.',
      turns: [
        { them: { t: 'Hola, buenos días. ¿Qué le pongo?', en: 'Hi, good morning. What can I get you?' } },
        { you: { cue: 'Say: A coffee with milk, please.', t: 'Un café con leche, por favor.', en: 'A coffee with milk, please.',
          alt: ['Un café con leche', 'Café con leche, por favor'],
          gloss: 'un = a · café = coffee · con = with · leche = milk · por favor = please' } },
        { them: { t: '¿Algo más?', en: 'Anything else?' } },
        { you: { cue: 'Say: No, nothing else, thanks.', t: 'No, nada más, gracias.', en: 'No, nothing else, thanks.',
          alt: ['Nada más, gracias', 'No, gracias'],
          gloss: 'no = no · nada = nothing · más = more · gracias = thanks' } },
        { them: { t: 'Aquí tiene.', en: 'Here you are.' } },
        { you: { cue: 'Ask: How much is it?', t: '¿Cuánto es?', en: 'How much is it?',
          alt: ['¿Cuánto le debo?', '¿Qué le debo?'],
          gloss: 'cuánto = how much · es = is (ser)' } },
        { them: { t: 'Un euro con ochenta.', en: 'One euro eighty.' } },
        { you: { cue: 'Say: Here. Thanks!', t: 'Tome. ¡Gracias!', en: 'Here. Thanks!',
          alt: ['Tome, gracias', 'Gracias'],
          gloss: 'tome = take (it) — polite command of tomar, said when handing over money · gracias = thanks' } }
      ]
    },
    {
      title: 'A table for two',
      scene: 'You arrive at a small restaurant with a friend at lunchtime.',
      turns: [
        { them: { t: 'Buenas tardes. ¿Cuántos son?', en: 'Good afternoon. How many are you?' } },
        { you: { cue: 'Say: We are two.', t: 'Somos dos.', en: 'We are two.',
          alt: ['Dos', 'Somos 2', 'Para dos'],
          gloss: 'somos = we are (ser) · dos = two' } },
        { them: { t: '¿Dentro o fuera?', en: 'Inside or outside?' } },
        { you: { cue: 'Say: Outside, please.', t: 'Fuera, por favor.', en: 'Outside, please.',
          alt: ['Afuera, por favor', 'En la terraza, por favor'],
          gloss: 'fuera = outside (Latin America usually says afuera) · por favor = please' } },
        { them: { t: 'Muy bien. Aquí tienen la carta.', en: 'Very good. Here’s the menu.' } },
        { you: { cue: 'Say: Thanks. Do you have a set menu of the day?', t: 'Gracias. ¿Tienen menú del día?', en: 'Thanks. Do you have a set menu of the day?',
          alt: ['¿Tienen menú del día?', 'Gracias, ¿hay menú del día?'],
          gloss: 'gracias = thanks · tienen = you have (tener, ustedes form — the restaurant) · menú del día = set lunch menu (literally “menu of the day”)' } },
        { them: { t: 'Sí, son doce euros.', en: 'Yes, it’s twelve euros.' } },
        { you: { cue: 'Say: Perfect, thank you very much.', t: 'Perfecto, muchas gracias.', en: 'Perfect, thank you very much.',
          alt: ['Perfecto, gracias', 'Muy bien, muchas gracias'],
          gloss: 'perfecto = perfect · muchas gracias = thank you very much' } }
      ]
    },
    {
      title: 'Ordering lunch',
      scene: 'The waiter comes to take your order.',
      turns: [
        { them: { t: '¿Qué van a tomar?', en: 'What will you have?' } },
        { you: { cue: 'Say: For me, the soup, please.', t: 'Para mí, la sopa, por favor.', en: 'For me, the soup, please.',
          alt: ['La sopa, por favor', 'Para mí la sopa'],
          gloss: 'para = for · mí = me · la = the · sopa = soup · por favor = please' } },
        { them: { t: '¿Y de segundo?', en: 'And for the main course?' } },
        { you: { cue: 'Say: The chicken with potatoes.', t: 'El pollo con patatas.', en: 'The chicken with potatoes.',
          alt: ['Pollo con patatas', 'El pollo con papas'],
          gloss: 'el = the · pollo = chicken · con = with · patatas = potatoes (Spain; papas in Latin America)' } },
        { them: { t: '¿Y para beber?', en: 'And to drink?' } },
        { you: { cue: 'Say: Water, please.', t: 'Agua, por favor.', en: 'Water, please.',
          alt: ['Un agua, por favor', 'Agua'],
          gloss: 'agua = water · por favor = please' } },
        { them: { t: '¿Con gas o sin gas?', en: 'Sparkling or still?' } },
        { you: { cue: 'Say: Still, thanks.', t: 'Sin gas, gracias.', en: 'Still, thanks.',
          alt: ['Sin gas', 'Natural, gracias'],
          gloss: 'sin = without · gas = gas (fizz) · gracias = thanks — “con gas” would be sparkling' } }
      ]
    },
    {
      title: 'The bill, please',
      scene: 'You’ve finished eating and want to pay.',
      turns: [
        { them: { t: '¿Todo bien?', en: 'Everything OK?' } },
        { you: { cue: 'Say: Yes, all very tasty.', t: 'Sí, todo muy rico.', en: 'Yes, all very tasty.',
          alt: ['Sí, todo muy bueno', 'Sí, estaba todo muy rico'],
          gloss: 'sí = yes · todo = everything · muy = very · rico = tasty (of food; also “rich”)' } },
        { them: { t: '¿Quieren postre o café?', en: 'Would you like dessert or coffee?' } },
        { you: { cue: 'Say: No, thanks. The bill, please.', t: 'No, gracias. La cuenta, por favor.', en: 'No, thanks. The bill, please.',
          alt: ['La cuenta, por favor', 'No, gracias, la cuenta'],
          gloss: 'no, gracias = no, thanks · la = the · cuenta = bill (also “account”) · por favor = please' } },
        { them: { t: 'Ahora mismo.', en: 'Right away.' } },
        { you: { cue: 'Ask: Can I pay by card?', t: '¿Puedo pagar con tarjeta?', en: 'Can I pay by card?',
          alt: ['¿Se puede pagar con tarjeta?', '¿Aceptan tarjeta?'],
          gloss: 'puedo = I can (poder) · pagar = to pay · con = with · tarjeta = card' } },
        { them: { t: 'Sí, claro.', en: 'Yes, of course.' } },
        { you: { cue: 'Say: Thanks a lot. Goodbye!', t: 'Muchas gracias. ¡Adiós!', en: 'Thanks a lot. Goodbye!',
          alt: ['Gracias, adiós', 'Muchas gracias, hasta luego'],
          gloss: 'muchas gracias = thank you very much · adiós = goodbye' } }
      ]
    },
    {
      title: 'Coffee with Javi',
      scene: 'Your friend Javi meets you at a café; with a friend you use “tú”.',
      turns: [
        { them: { t: '¡Hola! ¿Qué tal estás?', en: 'Hi! How are you?' } },
        { you: { cue: 'Say: Very well. And you?', t: 'Muy bien. ¿Y tú?', en: 'Very well. And you?',
          alt: ['Muy bien, ¿y tú?', 'Bien, ¿y tú?'],
          gloss: 'muy = very · bien = well · y = and · tú = you (informal, to a friend)' } },
        { them: { t: 'Bien. ¿Qué quieres tomar?', en: 'Good. What do you want to have?' } },
        { you: { cue: 'Say: A coffee with milk, please.', t: 'Un café con leche, por favor.', en: 'A coffee with milk, please.',
          alt: ['Un café con leche', 'Café con leche'],
          gloss: 'un = a · café = coffee · con = with · leche = milk · por favor = please' } },
        { them: { t: '¿Quieres algo de comer?', en: 'Do you want something to eat?' } },
        { you: { cue: 'Say: No, thanks. I’m not hungry.', t: 'No, gracias. No tengo hambre.', en: 'No, thanks. I’m not hungry.',
          alt: ['No tengo hambre', 'No, gracias'],
          gloss: 'no = no / not · gracias = thanks · tengo = I have (tener) · hambre = hunger — Spanish “has hunger” instead of “is hungry”' } },
        { them: { t: 'Vale. Pago yo.', en: 'OK. I’ll pay.' } },
        { you: { cue: 'Say: No, no, I’ll pay!', t: '¡No, no, pago yo!', en: 'No, no, I’ll pay!',
          alt: ['No, pago yo', 'Pago yo'],
          gloss: 'no = no · pago = I pay (pagar) · yo = I — putting “yo” last stresses it: “I’m the one paying”' } },
        { them: { t: 'Bueno, la próxima vez pagas tú.', en: 'Fine, next time you pay.' } },
        { you: { cue: 'Say: OK, thanks!', t: '¡Vale, gracias!', en: 'OK, thanks!',
          alt: ['Bueno, gracias', 'Está bien, gracias'],
          gloss: 'vale = OK (Spain; in Latin America “bueno” or “está bien”) · gracias = thanks' } }
      ]
    },

    /* ---------- 3. Numbers, prices & shopping ---------- */
    {
      title: 'At the market',
      scene: 'You buy fruit and vegetables at a market stall.',
      turns: [
        { them: { t: 'Hola, ¿qué le pongo?', en: 'Hello, what can I get you?' } },
        { you: { cue: 'Ask for a kilo of tomatoes.', t: 'Un kilo de tomates, por favor.', en: 'A kilo of tomatoes, please.',
          alt: ['Un kilo de tomates', '1 kilo de tomates, por favor'],
          gloss: 'un = a / one · kilo = kilo · de = of · tomates = tomatoes · por favor = please' } },
        { them: { t: '¿Algo más?', en: 'Anything else?' } },
        { you: { cue: 'Ask how much the oranges are.', t: '¿A cuánto están las naranjas?', en: 'How much are the oranges?',
          alt: ['¿Cuánto cuestan las naranjas?', '¿A cuánto las naranjas?'],
          gloss: 'a cuánto = at how much (for prices that change day to day) · están = are (estar) · las = the · naranjas = oranges' } },
        { them: { t: 'A dos euros el kilo.', en: 'Two euros a kilo.' } },
        { you: { cue: 'Ask for two kilos of them.', t: 'Pues dos kilos, por favor.', en: 'Two kilos, then, please.',
          alt: ['Dos kilos, por favor', '2 kilos, por favor'],
          gloss: 'pues = well / then · dos = two · kilos = kilos · por favor = please' } },
        { them: { t: 'Muy bien. ¿Algo más?', en: 'Very good. Anything else?' } },
        { you: { cue: 'Say that’s everything.', t: 'No, nada más, gracias.', en: 'No, nothing else, thanks.',
          alt: ['Nada más, gracias', 'Nada más'],
          gloss: 'no = no · nada = nothing · más = more · gracias = thanks' } },
        { them: { t: 'Son siete euros.', en: 'That’s seven euros.' } },
        { you: { cue: 'Hand over the money: “Here you are.”', t: 'Aquí tiene.', en: 'Here you are.',
          alt: ['Tome', 'Aquí tiene, gracias'],
          gloss: 'aquí = here · tiene = you have (tener, usted form) — “here you have it”' } }
      ]
    },
    {
      title: 'Trying on a jacket',
      scene: 'You’re looking at jackets in a clothes shop.',
      turns: [
        { them: { t: 'Hola, ¿le puedo ayudar?', en: 'Hello, can I help you?' } },
        { you: { cue: 'Say you’re just looking.', t: 'Solo estoy mirando, gracias.', en: 'I’m just looking, thanks.',
          alt: ['Solo miro, gracias', 'Estoy mirando, gracias'],
          gloss: 'solo = only · estoy = I am (estar) · mirando = looking (mirar, -ando form) · gracias = thanks' } },
        { them: { t: 'Muy bien. Si necesita algo, me dice.', en: 'Very good. If you need something, tell me.' } },
        { you: { cue: 'Call her back and ask how much this jacket costs.', t: 'Perdone, ¿cuánto cuesta esta chaqueta?', en: 'Excuse me, how much is this jacket?',
          alt: ['¿Cuánto cuesta esta chaqueta?', '¿Cuánto vale esta chaqueta?', 'Perdone, ¿cuánto cuesta esta chamarra?'],
          gloss: 'perdone = excuse me (usted form) · cuánto = how much · cuesta = costs (costar) · esta = this · chaqueta = jacket (chamarra in Mexico, campera in Argentina)' } },
        { them: { t: 'Cuarenta y cinco euros.', en: 'Forty-five euros.' } },
        { you: { cue: 'Ask if you can try it on.', t: '¿Me la puedo probar?', en: 'Can I try it on?',
          alt: ['¿Puedo probármela?', '¿Me la pruebo?'],
          gloss: 'me = on myself · la = it (la chaqueta) · puedo = I can (poder) · probar = to try' } },
        { them: { t: 'Claro, el probador está allí.', en: 'Sure, the fitting room is over there.' } },
        { you: { cue: 'Say it’s big on you, and ask for another size.', t: 'Me queda grande. ¿Tiene otra talla?', en: 'It’s big on me. Do you have another size?',
          alt: ['Me queda grande, ¿tiene otra talla?', 'Es grande. ¿Tiene otra talla?'],
          gloss: 'me = on me · queda = fits (quedar) · grande = big · tiene = do you have (tener, usted) · otra = another · talla = size' } },
        { them: { t: 'Sí, aquí tiene la M.', en: 'Yes, here’s the medium.' } },
        { you: { cue: 'Say it’s perfect and you’ll take it.', t: 'Perfecta. Me la llevo.', en: 'Perfect. I’ll take it.',
          alt: ['Me la llevo', 'Perfecto, me la llevo'],
          gloss: 'perfecta = perfect (feminine, for la chaqueta) · me = for myself · la = it · llevo = I take (llevar)' } }
      ]
    },
    {
      title: 'Joining the gym',
      scene: 'You sign up at a gym and the receptionist takes your details.',
      turns: [
        { them: { t: '¿Su nombre, por favor?', en: 'Your name, please?' } },
        { you: { cue: 'Give your name: Alex Smith.', t: 'Me llamo Alex Smith.', en: 'My name is Alex Smith.',
          alt: ['Alex Smith', 'Soy Alex Smith'],
          gloss: 'me llamo = my name is (literally “I call myself”)' } },
        { them: { t: '¿Cuántos años tiene?', en: 'How old are you?' } },
        { you: { cue: 'Say you’re thirty-four.', t: 'Tengo treinta y cuatro años.', en: 'I’m thirty-four.',
          alt: ['Tengo 34 años', 'Treinta y cuatro', '34'],
          gloss: 'tengo = I have (tener) · treinta y cuatro = thirty-four (thirty and four) · años = years — Spanish “has” years' } },
        { them: { t: '¿Y su número de teléfono?', en: 'And your phone number?' } },
        { you: { cue: 'Give the number: six, one, two, four, five, eight.', t: 'Seis, uno, dos, cuatro, cinco, ocho.', en: 'Six, one, two, four, five, eight.',
          alt: ['612458', '6 1 2 4 5 8', '612 458'],
          gloss: 'seis = six · uno = one · dos = two · cuatro = four · cinco = five · ocho = eight' } },
        { them: { t: 'Perfecto, gracias.', en: 'Perfect, thanks.' } },
        { you: { cue: 'Ask how much it costs per month.', t: '¿Cuánto cuesta al mes?', en: 'How much is it per month?',
          alt: ['¿Cuánto es al mes?', '¿Cuánto cuesta por mes?'],
          gloss: 'cuánto = how much · cuesta = costs (costar) · al = per the (a + el) · mes = month' } },
        { them: { t: 'Treinta euros al mes.', en: 'Thirty euros a month.' } },
        { you: { cue: 'Ask what time the gym opens.', t: '¿A qué hora abre el gimnasio?', en: 'What time does the gym open?',
          alt: ['¿A qué hora abre?', '¿A qué hora abren?'],
          gloss: 'a = at · qué = what · hora = hour / time · abre = opens (abrir) · el = the · gimnasio = gym' } },
        { them: { t: 'A las siete de la mañana.', en: 'At seven in the morning.' } }
      ]
    },
    {
      title: 'At the checkout',
      scene: 'You’re paying at the supermarket till.',
      turns: [
        { them: { t: 'Hola. ¿Necesita bolsa?', en: 'Hi. Do you need a bag?' } },
        { you: { cue: 'Say yes, one bag, please.', t: 'Sí, una bolsa, por favor.', en: 'Yes, one bag, please.',
          alt: ['Una bolsa, por favor', 'Sí, por favor'],
          gloss: 'sí = yes · una = a / one (feminine) · bolsa = bag · por favor = please' } },
        { them: { t: 'Son veintitrés con cincuenta.', en: 'That’s twenty-three fifty.' } },
        { you: { cue: 'Say sorry, you didn’t catch that — how much is it?', t: 'Perdone, no he entendido. ¿Cuánto es?', en: 'Sorry, I didn’t understand. How much is it?',
          alt: ['Perdone, no entendí, ¿cuánto es?', 'Perdón, ¿cuánto es?'],
          gloss: 'perdone = sorry / excuse me · no he entendido = I haven’t understood (present perfect, usual in Spain; Latin America says “no entendí”) · cuánto es = how much is it' } },
        { them: { t: 'Veintitrés euros con cincuenta.', en: 'Twenty-three euros fifty.' } },
        { you: { cue: 'Ask if you can pay by card.', t: '¿Puedo pagar con tarjeta?', en: 'Can I pay by card?',
          alt: ['¿Se puede pagar con tarjeta?', '¿Con tarjeta?'],
          gloss: 'puedo = I can (poder) · pagar = to pay · con = with · tarjeta = card' } },
        { them: { t: 'Sí, claro. Acerque la tarjeta aquí.', en: 'Yes, of course. Hold the card here.' } },
        { you: { cue: 'Ask her for the receipt.', t: '¿Me da el tique, por favor?', en: 'Could you give me the receipt, please?',
          alt: ['¿Me da el recibo, por favor?', '¿Me da el ticket, por favor?', 'El tique, por favor'],
          gloss: 'me = to me · da = you give (dar, usted form) · el = the · tique = receipt (also written ticket; recibo is understood everywhere) · por favor = please' } },
        { them: { t: 'Aquí tiene. ¡Que tenga un buen día!', en: 'Here you are. Have a good day!' } },
        { you: { cue: 'Thank her, wish her the same, and say bye.', t: 'Gracias, igualmente. ¡Hasta luego!', en: 'Thanks, same to you. See you!',
          alt: ['Gracias, igualmente', 'Igualmente, hasta luego'],
          gloss: 'gracias = thanks · igualmente = equally — “same to you” · hasta luego = see you / bye' } }
      ]
    },
    {
      title: 'A present for a friend',
      scene: 'You’re buying a birthday present in a little gift shop.',
      turns: [
        { them: { t: 'Buenas tardes. ¿Qué busca?', en: 'Good afternoon. What are you looking for?' } },
        { you: { cue: 'Say you’re looking for a present for a (female) friend.', t: 'Busco un regalo para una amiga.', en: 'I’m looking for a present for a friend.',
          alt: ['Estoy buscando un regalo para una amiga', 'Un regalo para una amiga'],
          gloss: 'busco = I look for (buscar — no “for” needed) · un = a · regalo = present · para = for · una = a (feminine) · amiga = (female) friend' } },
        { them: { t: '¿Y qué le gusta?', en: 'And what does she like?' } },
        { you: { cue: 'Say she likes books and music.', t: 'Le gustan los libros y la música.', en: 'She likes books and music.',
          alt: ['Le gustan los libros y la música', 'Los libros y la música'],
          gloss: 'le = to her · gustan = are pleasing (gustar, plural because “books” is the subject) · los libros = the books · y = and · la música = music' } },
        { them: { t: 'Este libro es muy bonito.', en: 'This book is very nice.' } },
        { you: { cue: 'Ask how much it is.', t: '¿Cuánto cuesta?', en: 'How much is it?',
          alt: ['¿Cuánto vale?', '¿Cuánto es?'],
          gloss: 'cuánto = how much · cuesta = it costs (costar, o → ue)' } },
        { them: { t: 'Quince euros.', en: 'Fifteen euros.' } },
        { you: { cue: 'Say OK, and ask her to gift-wrap it.', t: 'Vale. ¿Me lo envuelve para regalo?', en: 'OK. Could you gift-wrap it for me?',
          alt: ['¿Me lo puede envolver para regalo?', 'Bueno. ¿Me lo envuelve para regalo?'],
          gloss: 'vale = OK · me = for me · lo = it (el libro) · envuelve = you wrap (envolver, usted form) · para = for · regalo = present' } },
        { them: { t: 'Por supuesto. Un momento.', en: 'Of course. One moment.' } },
        { you: { cue: 'Say: Great, thank you very much.', t: 'Estupendo, muchas gracias.', en: 'Great, thank you very much.',
          alt: ['Genial, muchas gracias', 'Perfecto, muchas gracias'],
          gloss: 'estupendo = great / wonderful · muchas gracias = thank you very much' } }
      ]
    },

    /* ---------- 4. Directions & transport ---------- */
    {
      title: 'Where is the station?',
      scene: 'You’re lost in town and stop a woman in the street.',
      turns: [
        { you: { cue: 'Politely stop her and ask where the train station is.', t: 'Perdone, ¿dónde está la estación de tren?', en: 'Excuse me, where is the train station?',
          alt: ['¿Dónde está la estación de tren?', 'Perdone, ¿la estación de tren?'],
          gloss: 'perdone = excuse me (usted) · dónde = where · está = is (estar, for location) · la estación = the station · de = of · tren = train' } },
        { them: { t: 'Siga todo recto y luego a la derecha.', en: 'Go straight on and then turn right.' } },
        { you: { cue: 'Ask if it’s far from here.', t: '¿Está lejos de aquí?', en: 'Is it far from here?',
          alt: ['¿Está lejos?', '¿Queda lejos de aquí?'],
          gloss: 'está = is (estar) · lejos = far · de = from · aquí = here' } },
        { them: { t: 'No, está a cinco minutos andando.', en: 'No, it’s five minutes on foot.' } },
        { you: { cue: 'Check the way: straight on, then right?', t: 'Todo recto y luego a la derecha, ¿verdad?', en: 'Straight on and then right, right?',
          alt: ['Todo recto y a la derecha, ¿no?', 'Todo derecho y luego a la derecha, ¿verdad?'],
          gloss: 'todo recto = straight on (Latin America often says “todo derecho”) · y = and · luego = then · a la derecha = to the right · ¿verdad? = right? (literally “truth?”)' } },
        { them: { t: 'Eso es.', en: 'That’s it.' } },
        { you: { cue: 'Thank her — she’s been very kind.', t: 'Muchas gracias, muy amable.', en: 'Thank you very much, that’s very kind.',
          alt: ['Gracias, muy amable', 'Muchas gracias'],
          gloss: 'muchas gracias = thank you very much · muy = very · amable = kind — “(you are) very kind”' } },
        { them: { t: 'De nada. ¡Buen viaje!', en: 'You’re welcome. Have a good trip!' } }
      ]
    },
    {
      title: 'A ticket to Toledo',
      scene: 'You’re at the ticket office of the train station.',
      turns: [
        { them: { t: 'Buenos días. ¿Adónde va?', en: 'Good morning. Where are you going?' } },
        { you: { cue: 'Ask for a ticket to Toledo.', t: 'Un billete para Toledo, por favor.', en: 'A ticket to Toledo, please.',
          alt: ['Un boleto para Toledo, por favor', 'Quería un billete para Toledo', 'Uno para Toledo, por favor'],
          gloss: 'un = a · billete = ticket (Spain; boleto in Latin America) · para = for / to · por favor = please' } },
        { them: { t: '¿De ida o de ida y vuelta?', en: 'One way or return?' } },
        { you: { cue: 'Say return, please.', t: 'De ida y vuelta, por favor.', en: 'Return, please.',
          alt: ['Ida y vuelta', 'Ida y vuelta, por favor'],
          gloss: 'de = of · ida = going · y = and · vuelta = return — “going and coming back”' } },
        { them: { t: '¿Para hoy?', en: 'For today?' } },
        { you: { cue: 'Say yes, and ask when the next train leaves.', t: 'Sí. ¿A qué hora sale el próximo tren?', en: 'Yes. What time does the next train leave?',
          alt: ['¿A qué hora sale el próximo tren?', 'Sí, ¿cuándo sale el próximo tren?'],
          gloss: 'sí = yes · a qué hora = at what time · sale = leaves (salir) · el = the · próximo = next · tren = train' } },
        { them: { t: 'A las diez y cuarto.', en: 'At a quarter past ten.' } },
        { you: { cue: 'Ask which platform it leaves from.', t: '¿De qué andén sale?', en: 'Which platform does it leave from?',
          alt: ['¿De qué vía sale?', '¿Qué andén es?'],
          gloss: 'de = from · qué = which · andén = platform (vía = track, also used) · sale = it leaves (salir)' } },
        { them: { t: 'Del andén tres. Son veinte euros.', en: 'From platform three. That’s twenty euros.' } },
        { you: { cue: 'Hand over the money.', t: 'Aquí tiene.', en: 'Here you are.',
          alt: ['Tome', 'Aquí tiene, gracias'],
          gloss: 'aquí = here · tiene = you have (tener, usted form)' } }
      ]
    },
    {
      title: 'Taking a taxi',
      scene: 'You get into a taxi at the airport in Madrid.',
      turns: [
        { them: { t: 'Buenas tardes. ¿Adónde vamos?', en: 'Good afternoon. Where are we going?' } },
        { you: { cue: 'Ask to go to the Hotel Sol, on Calle Mayor.', t: 'Al hotel Sol, calle Mayor, por favor.', en: 'To the Hotel Sol, Calle Mayor, please.',
          alt: ['Al hotel Sol, en la calle Mayor, por favor', 'Al hotel Sol, por favor'],
          gloss: 'al = to the (a + el) · hotel = hotel · calle = street · por favor = please' } },
        { them: { t: 'Muy bien. ¿Es su primera vez aquí?', en: 'Very good. Is it your first time here?' } },
        { you: { cue: 'Say yes, it’s your first time in Madrid.', t: 'Sí, es mi primera vez en Madrid.', en: 'Yes, it’s my first time in Madrid.',
          alt: ['Sí, es la primera vez', 'Sí, primera vez en Madrid'],
          gloss: 'sí = yes · es = it is (ser) · mi = my · primera = first · vez = time (occasion) · en = in' } },
        { them: { t: '¡Le va a encantar!', en: 'You’re going to love it!' } },
        { you: { cue: 'Ask how long it takes to get there.', t: '¿Cuánto tiempo se tarda?', en: 'How long does it take?',
          alt: ['¿Cuánto se tarda?', '¿Cuánto tardamos?', '¿Cuánto se demora?'],
          gloss: 'cuánto = how much · tiempo = time · se tarda = one takes (tardar; much of Latin America says “se demora”)' } },
        { them: { t: 'Unos veinte minutos, si no hay tráfico.', en: 'About twenty minutes, if there’s no traffic.' } },
        { you: { cue: 'Ask roughly how much it will cost.', t: '¿Cuánto va a costar, más o menos?', en: 'How much will it cost, more or less?',
          alt: ['¿Cuánto cuesta, más o menos?', 'Más o menos, ¿cuánto va a costar?'],
          gloss: 'cuánto = how much · va a costar = is going to cost (ir a + infinitive = near future) · más o menos = more or less' } },
        { them: { t: 'Unos treinta euros.', en: 'About thirty euros.' } },
        { you: { cue: 'Say that’s fine.', t: 'Vale, perfecto.', en: 'OK, perfect.',
          alt: ['Muy bien', 'Está bien', 'Perfecto'],
          gloss: 'vale = OK (Spain; “está bien” everywhere) · perfecto = perfect' } }
      ]
    },
    {
      title: 'On the bus',
      scene: 'You get on a city bus and talk to the driver.',
      turns: [
        { you: { cue: 'Ask the driver if this bus goes to the city centre.', t: 'Perdone, ¿este autobús va al centro?', en: 'Excuse me, does this bus go to the centre?',
          alt: ['¿Este autobús va al centro?', '¿Este bus va al centro?'],
          gloss: 'perdone = excuse me · este = this · autobús = bus (bus in much of Latin America, camión in Mexico, colectivo in Argentina) · va = goes (ir) · al = to the · centro = centre' } },
        { them: { t: 'Sí, va al centro.', en: 'Yes, it goes to the centre.' } },
        { you: { cue: 'Ask how much a ticket is.', t: '¿Cuánto cuesta el billete?', en: 'How much is the ticket?',
          alt: ['¿Cuánto es el billete?', '¿Cuánto cuesta el boleto?', '¿Cuánto es?'],
          gloss: 'cuánto = how much · cuesta = costs · el = the · billete = ticket (boleto in Latin America)' } },
        { them: { t: 'Un euro cincuenta.', en: 'One euro fifty.' } },
        { you: { cue: 'Ask him to tell you when you get to the museum.', t: '¿Me avisa cuando lleguemos al museo?', en: 'Will you tell me when we get to the museum?',
          alt: ['¿Me avisa en el museo?', '¿Me avisa para el museo?'],
          gloss: 'me = me · avisa = you let know (avisar, usted) · cuando = when · lleguemos = we arrive (llegar — subjunctive, used after “cuando” about the future) · al = at the · museo = museum' } },
        { them: { t: 'Claro. Es la cuarta parada.', en: 'Sure. It’s the fourth stop.' } },
        { you: { cue: 'Check: the fourth stop? Then say thanks.', t: '¿La cuarta parada? Muy bien, gracias.', en: 'The fourth stop? Great, thanks.',
          alt: ['La cuarta parada, muy bien, gracias', '¿La cuarta? Gracias'],
          gloss: 'la = the · cuarta = fourth · parada = stop · muy bien = very good · gracias = thanks' } },
        { them: { t: 'Oiga, esta es su parada.', en: 'Hey, this is your stop.' } },
        { you: { cue: 'Thank him and wish him a good day.', t: 'Muchas gracias. ¡Que tenga un buen día!', en: 'Thank you very much. Have a good day!',
          alt: ['Gracias, que tenga un buen día', 'Muchas gracias, buen día'],
          gloss: 'muchas gracias = thanks a lot · que tenga = may you have (tener, subjunctive, usted) · un = a · buen = good · día = day' } }
      ]
    },
    {
      title: 'Getting to the Prado',
      scene: 'In the metro, you ask a woman how to get to the Prado Museum.',
      turns: [
        { you: { cue: 'Ask her how to get to the Prado Museum.', t: 'Perdone, ¿cómo llego al Museo del Prado?', en: 'Excuse me, how do I get to the Prado Museum?',
          alt: ['¿Cómo llego al Museo del Prado?', '¿Cómo voy al Museo del Prado?'],
          gloss: 'perdone = excuse me · cómo = how · llego = I arrive / get (llegar) · al = to the · museo = museum · del = of the (de + el)' } },
        { them: { t: 'Tome la línea uno y baje en Atocha.', en: 'Take line one and get off at Atocha.' } },
        { you: { cue: 'Check which line and which stop.', t: '¿La línea uno, y bajo en Atocha?', en: 'Line one, and I get off at Atocha?',
          alt: ['¿La línea 1 y bajo en Atocha?', 'Línea uno, y bajo en Atocha'],
          gloss: 'la = the · línea = line · uno = one · y = and · bajo = I get off (bajar, “to go down”) · en = at' } },
        { them: { t: 'Sí. Luego son cinco minutos andando.', en: 'Yes. Then it’s a five-minute walk.' } },
        { you: { cue: 'Ask where you can buy a ticket.', t: '¿Dónde puedo comprar un billete?', en: 'Where can I buy a ticket?',
          alt: ['¿Dónde compro el billete?', '¿Dónde puedo comprar un boleto?'],
          gloss: 'dónde = where · puedo = I can (poder) · comprar = to buy · un = a · billete = ticket (boleto in Latin America)' } },
        { them: { t: 'En las máquinas, allí a la izquierda.', en: 'At the machines, over there on the left.' } },
        { you: { cue: 'Ask if you can pay by card at the machines.', t: '¿Se puede pagar con tarjeta en las máquinas?', en: 'Can you pay by card at the machines?',
          alt: ['¿Las máquinas aceptan tarjeta?', '¿Se puede pagar con tarjeta?'],
          gloss: 'se puede = one can (poder, impersonal “se”) · pagar = to pay · con tarjeta = by card · en = at · las máquinas = the machines' } },
        { them: { t: 'Sí, sin problema.', en: 'Yes, no problem.' } },
        { you: { cue: 'Thank her — she’s been very kind.', t: 'Muchas gracias, muy amable.', en: 'Thank you very much, that’s very kind.',
          alt: ['Gracias, muy amable', 'Muchas gracias'],
          gloss: 'muchas gracias = thank you very much · muy amable = very kind' } }
      ]
    },

    /* ---------- 5. Hotel, travel & fixing problems ---------- */
    {
      title: 'Checking in',
      scene: 'You arrive at the hotel reception late in the evening.',
      turns: [
        { them: { t: 'Buenas noches. ¿En qué le puedo ayudar?', en: 'Good evening. How can I help you?' } },
        { you: { cue: 'Say you have a booking in the name of Alex Smith.', t: 'Tengo una reserva a nombre de Alex Smith.', en: 'I have a booking in the name of Alex Smith.',
          alt: ['Tengo una reservación a nombre de Alex Smith', 'Una reserva a nombre de Alex Smith'],
          gloss: 'tengo = I have (tener) · una = a · reserva = booking (reservación in Mexico) · a nombre de = in the name of' } },
        { them: { t: 'Sí, aquí está. Una habitación doble para tres noches.', en: 'Yes, here it is. A double room for three nights.' } },
        { you: { cue: 'Confirm, and ask if breakfast is included.', t: 'Sí, eso es. ¿El desayuno está incluido?', en: 'Yes, that’s right. Is breakfast included?',
          alt: ['¿El desayuno está incluido?', 'Sí. ¿Está incluido el desayuno?'],
          gloss: 'sí = yes · eso es = that’s it · el desayuno = breakfast · está = is (estar) · incluido = included' } },
        { them: { t: 'Sí, de siete a diez, en el primer piso.', en: 'Yes, from seven to ten, on the first floor.' } },
        { you: { cue: 'Ask what the wifi password is.', t: '¿Cuál es la contraseña del wifi?', en: 'What’s the wifi password?',
          alt: ['¿Me da la contraseña del wifi?', '¿Cuál es la clave del wifi?'],
          gloss: 'cuál = which / what · es = is · la contraseña = the password (clave is common in Latin America) · del = of the · wifi = wifi (said “wee-fee”)' } },
        { them: { t: 'Está en la tarjeta de la habitación.', en: 'It’s on the room card.' } },
        { you: { cue: 'Ask what time you have to leave the room on the last day.', t: '¿A qué hora hay que dejar la habitación?', en: 'What time do we have to leave the room?',
          alt: ['¿A qué hora hay que salir de la habitación?', '¿A qué hora es la salida?'],
          gloss: 'a qué hora = at what time · hay que = one has to · dejar = to leave (something) · la habitación = the room' } },
        { them: { t: 'Antes de las doce.', en: 'Before twelve.' } },
        { you: { cue: 'Thank him and say good night.', t: 'Perfecto, gracias. Buenas noches.', en: 'Perfect, thanks. Good night.',
          alt: ['Gracias, buenas noches', 'Muchas gracias, buenas noches'],
          gloss: 'perfecto = perfect · gracias = thanks · buenas noches = good evening / good night' } }
      ]
    },
    {
      title: 'The air conditioning',
      scene: 'You phone reception from your room because something isn’t working.',
      turns: [
        { them: { t: 'Recepción, dígame.', en: 'Reception, go ahead.' } },
        { you: { cue: 'Say hello, and that you’re calling from room two hundred and fourteen.', t: 'Hola, llamo de la habitación doscientos catorce.', en: 'Hello, I’m calling from room two hundred and fourteen.',
          alt: ['Hola, llamo de la habitación 214', 'Llamo de la habitación doscientos catorce'],
          gloss: 'hola = hello · llamo = I call (llamar) · de = from · la habitación = the room · doscientos = two hundred · catorce = fourteen' } },
        { them: { t: 'Sí, dígame.', en: 'Yes, go ahead.' } },
        { you: { cue: 'Say the air conditioning doesn’t work.', t: 'El aire acondicionado no funciona.', en: 'The air conditioning doesn’t work.',
          alt: ['No funciona el aire acondicionado', 'El aire no funciona'],
          gloss: 'el = the · aire acondicionado = air conditioning · no = not · funciona = works (funcionar)' } },
        { them: { t: 'Vaya, lo siento. ¿Ha probado con el mando?', en: 'Oh, I’m sorry. Have you tried the remote?' } },
        { you: { cue: 'Say yes, you’ve tried, but it still doesn’t work.', t: 'Sí, lo he probado, pero sigue sin funcionar.', en: 'Yes, I’ve tried it, but it still doesn’t work.',
          alt: ['Sí, lo probé, pero sigue sin funcionar', 'Sí, pero sigue sin funcionar'],
          gloss: 'sí = yes · lo = it · he probado = I have tried (present perfect of probar; Latin America: “lo probé”) · pero = but · sigue = it goes on (seguir) · sin funcionar = without working' } },
        { them: { t: 'Ahora mismo subo a verlo.', en: 'I’ll come up and look at it right now.' } },
        { you: { cue: 'Ask if he can also bring another towel.', t: '¿Me puede traer también otra toalla?', en: 'Can you also bring me another towel?',
          alt: ['¿Puede traer otra toalla también?', '¿Me trae otra toalla, por favor?'],
          gloss: 'me = to me · puede = you can (poder, usted) · traer = to bring · también = also · otra = another · toalla = towel' } },
        { them: { t: 'Claro, no hay problema.', en: 'Sure, no problem.' } },
        { you: { cue: 'Thank him politely.', t: 'Gracias, es usted muy amable.', en: 'Thanks, you’re very kind.',
          alt: ['Gracias, muy amable', 'Muchas gracias, es muy amable'],
          gloss: 'gracias = thanks · es = you are (ser, usted form) · usted = you (polite) · muy = very · amable = kind' } }
      ]
    },
    {
      title: 'Lost luggage',
      scene: 'Your suitcase didn’t come out at the airport, so you go to the airline desk.',
      turns: [
        { you: { cue: 'Say hello, and that your suitcase hasn’t arrived.', t: 'Hola, mi maleta no ha llegado.', en: 'Hello, my suitcase hasn’t arrived.',
          alt: ['Hola, mi maleta no llegó', 'Mi maleta no ha llegado'],
          gloss: 'hola = hello · mi = my · maleta = suitcase (valija in Argentina) · no ha llegado = hasn’t arrived (present perfect, Spain; Latin America: “no llegó”)' } },
        { them: { t: 'Lo siento. ¿De qué vuelo viene?', en: 'I’m sorry. Which flight are you coming from?' } },
        { you: { cue: 'Say it’s the flight from London that landed an hour ago.', t: 'Del vuelo de Londres, que llegó hace una hora.', en: 'The flight from London, which arrived an hour ago.',
          alt: ['Del vuelo de Londres', 'Del vuelo de Londres, llegó hace una hora'],
          gloss: 'del = from the · vuelo = flight · de = from · que = which · llegó = arrived (llegar, preterite) · hace una hora = an hour ago (literally “it makes one hour”)' } },
        { them: { t: '¿Cómo es la maleta?', en: 'What does the suitcase look like?' } },
        { you: { cue: 'Describe it: big and black, with a red ribbon.', t: 'Es grande y negra, con una cinta roja.', en: 'It’s big and black, with a red ribbon.',
          alt: ['Grande y negra, con una cinta roja', 'Es negra y grande, con una cinta roja'],
          gloss: 'es = it is (ser, for description) · grande = big · y = and · negra = black (feminine, like maleta) · con = with · una = a · cinta = ribbon · roja = red' } },
        { them: { t: 'Vale. Rellene este formulario, por favor.', en: 'OK. Fill in this form, please.' } },
        { you: { cue: 'Ask when they think they’ll find it.', t: '¿Cuándo cree que la van a encontrar?', en: 'When do you think you’ll find it?',
          alt: ['¿Cuándo la van a encontrar?', '¿Cuándo cree que la encuentran?'],
          gloss: 'cuándo = when · cree = you think (creer, usted) · que = that · la = it (la maleta) · van a encontrar = are going to find (ir a + infinitive)' } },
        { them: { t: 'Normalmente en uno o dos días.', en: 'Usually in one or two days.' } },
        { you: { cue: 'Ask if they can send it to your hotel.', t: '¿Me la pueden mandar al hotel?', en: 'Can you send it to my hotel?',
          alt: ['¿Me la pueden enviar al hotel?', '¿La pueden mandar al hotel?'],
          gloss: 'me = to me · la = it · pueden = you (plural / the company) can (poder) · mandar = to send · al = to the · hotel = hotel' } }
      ]
    },
    {
      title: 'Changing a booking',
      scene: 'You phone a hotel to change the date you arrive.',
      turns: [
        { them: { t: 'Hotel Mirador, buenos días.', en: 'Hotel Mirador, good morning.' } },
        { you: { cue: 'Say good morning, and that you’d like to change a booking.', t: 'Buenos días, quería cambiar una reserva.', en: 'Good morning, I’d like to change a booking.',
          alt: ['Quería cambiar una reserva', 'Buenos días, quería cambiar una reservación'],
          gloss: 'buenos días = good morning · quería = I wanted (querer, imperfect — the polite “I’d like”) · cambiar = to change · una reserva = a booking' } },
        { them: { t: 'Muy bien. ¿A nombre de quién?', en: 'Very good. In whose name?' } },
        { you: { cue: 'Give your name: Alex Smith, for the fifth of May.', t: 'A nombre de Alex Smith, para el cinco de mayo.', en: 'In the name of Alex Smith, for the fifth of May.',
          alt: ['A nombre de Alex Smith, para el 5 de mayo', 'Alex Smith, para el cinco de mayo'],
          gloss: 'a nombre de = in the name of · para = for · el cinco = the fifth (Spanish uses plain numbers for dates) · de mayo = of May' } },
        { them: { t: 'Sí, lo tengo. ¿Qué quiere cambiar?', en: 'Yes, I have it. What do you want to change?' } },
        { you: { cue: 'Say you’d like to arrive one day later, on the sixth.', t: 'Quería llegar un día más tarde, el día seis.', en: 'I’d like to arrive one day later, on the sixth.',
          alt: ['Quería llegar un día más tarde, el 6', 'Quería llegar el día seis'],
          gloss: 'quería = I’d like · llegar = to arrive · un día = one day · más tarde = later · el día seis = on the sixth' } },
        { them: { t: 'Un momento... Sí, hay habitación.', en: 'One moment... Yes, there is a room.' } },
        { you: { cue: 'Ask if you have to pay anything extra.', t: '¿Hay que pagar algo más?', en: 'Do I have to pay anything more?',
          alt: ['¿Tengo que pagar algo más?', '¿Cuesta más?'],
          gloss: 'hay que = one has to · pagar = to pay · algo = something · más = more' } },
        { them: { t: 'No, el precio es el mismo.', en: 'No, the price is the same.' } },
        { you: { cue: 'Say great, thank you very much, bye.', t: 'Estupendo. Muchas gracias, hasta luego.', en: 'Great. Thank you very much, bye.',
          alt: ['Genial, muchas gracias, hasta luego', 'Perfecto, muchas gracias, adiós'],
          gloss: 'estupendo = great · muchas gracias = thank you very much · hasta luego = bye' } }
      ]
    },
    {
      title: 'A mistake on the bill',
      scene: 'You’re checking out and see something on the bill you never had.',
      turns: [
        { you: { cue: 'Say good morning, and that you’d like to pay and check out.', t: 'Buenos días, quería pagar y dejar la habitación.', en: 'Good morning, I’d like to pay and check out.',
          alt: ['Quería pagar y dejar la habitación', 'Buenos días, quería pagar la cuenta'],
          gloss: 'buenos días = good morning · quería = I’d like · pagar = to pay · y = and · dejar = to leave · la habitación = the room' } },
        { them: { t: 'Claro. Aquí tiene la factura.', en: 'Of course. Here’s the bill.' } },
        { you: { cue: 'Say politely that you think there’s a mistake here.', t: 'Perdone, creo que hay un error aquí.', en: 'Sorry, I think there’s a mistake here.',
          alt: ['Creo que hay un error', 'Perdone, hay un error aquí'],
          gloss: 'perdone = sorry · creo = I think (creer) · que = that · hay = there is · un error = a mistake · aquí = here' } },
        { them: { t: '¿Dónde?', en: 'Where?' } },
        { you: { cue: 'Say you haven’t had anything from the minibar.', t: 'No he tomado nada del minibar.', en: 'I haven’t had anything from the minibar.',
          alt: ['No tomé nada del minibar', 'Yo no tomé nada del minibar'],
          gloss: 'no he tomado = I haven’t had (present perfect of tomar; Latin America: “no tomé”) · nada = nothing (Spanish doubles the negative) · del = from the · minibar = minibar' } },
        { them: { t: 'Ah, tiene razón. Lo siento mucho. Ya está corregido.', en: 'Ah, you’re right. I’m very sorry. It’s corrected now.' } },
        { you: { cue: 'Say no problem, and ask if you can leave your suitcase here until the afternoon.', t: 'No pasa nada. ¿Puedo dejar la maleta aquí hasta la tarde?', en: 'No problem. Can I leave my suitcase here until the afternoon?',
          alt: ['¿Puedo dejar la maleta aquí hasta la tarde?', 'No pasa nada. ¿Puedo dejar aquí la maleta?'],
          gloss: 'no pasa nada = no problem (literally “nothing happens”) · puedo = can I · dejar = to leave · la maleta = the suitcase · aquí = here · hasta = until · la tarde = the afternoon' } },
        { them: { t: 'Sí, por supuesto.', en: 'Yes, of course.' } },
        { you: { cue: 'Thank her for everything and say goodbye.', t: 'Muchas gracias por todo. ¡Adiós!', en: 'Thank you very much for everything. Goodbye!',
          alt: ['Gracias por todo, adiós', 'Muchas gracias por todo'],
          gloss: 'muchas gracias = thank you very much · por = for · todo = everything · adiós = goodbye' } }
      ]
    },

    /* ---------- 6. Small talk: where you live, family, work, hobbies, weather ---------- */
    {
      title: 'What do you do?',
      scene: 'At a friend’s barbecue you chat with someone your age, using “tú”.',
      turns: [
        { them: { t: 'Oye, ¿y tú de dónde eres?', en: 'Hey, and where are you from?' } },
        { you: { cue: 'Say you’re from London, but live in Madrid now.', t: 'Soy de Londres, pero ahora vivo en Madrid.', en: 'I’m from London, but now I live in Madrid.',
          alt: ['Soy de Londres, pero vivo en Madrid', 'De Londres, pero ahora vivo en Madrid'],
          gloss: 'soy = I am · de = from · pero = but · ahora = now · vivo = I live (vivir) · en = in' } },
        { them: { t: '¡Qué bien! ¿Y cuánto tiempo llevas aquí?', en: 'Great! And how long have you been here?' } },
        { you: { cue: 'Say you’ve been here six months, since March.', t: 'Llevo seis meses aquí, desde marzo.', en: 'I’ve been here six months, since March.',
          alt: ['Llevo 6 meses aquí', 'Seis meses, desde marzo'],
          gloss: 'llevo = I’ve been (llevar + time = how long you’ve been doing something) · seis = six · meses = months · aquí = here · desde = since · marzo = March' } },
        { them: { t: '¿Y te gusta Madrid?', en: 'And do you like Madrid?' } },
        { you: { cue: 'Say you love it — people are very friendly.', t: 'Me encanta. La gente es muy simpática.', en: 'I love it. People are very friendly.',
          alt: ['Me encanta, la gente es muy maja', 'Sí, me encanta'],
          gloss: 'me encanta = I love it (encantar, like gustar: “it delights me”) · la gente = people (singular in Spanish) · es = is · muy = very · simpática = friendly, nice' } },
        { them: { t: '¿Y a qué te dedicas?', en: 'And what do you do for a living?' } },
        { you: { cue: 'Say you work for a marketing company, in the centre.', t: 'Trabajo en una empresa de marketing, en el centro.', en: 'I work for a marketing company, in the centre.',
          alt: ['Trabajo en una empresa de marketing', 'Trabajo en marketing'],
          gloss: 'trabajo = I work (trabajar) · en = in / at · una = a · empresa = company · de = of · marketing = marketing · el centro = the centre' } },
        { them: { t: 'Ah, qué interesante. Yo soy enfermera.', en: 'Oh, how interesting. I’m a nurse.' } },
        { you: { cue: 'Ask her if she likes her job.', t: '¿Y te gusta tu trabajo?', en: 'And do you like your job?',
          alt: ['¿Te gusta tu trabajo?', '¿Y te gusta?'],
          gloss: 'y = and · te = to you (informal) · gusta = pleases (gustar) · tu = your (informal) · trabajo = job' } }
      ]
    },
    {
      title: 'Family photos',
      scene: 'A colleague shows you photos on her phone and asks about your family.',
      turns: [
        { them: { t: 'Mira, estos son mis hijos.', en: 'Look, these are my children.' } },
        { you: { cue: 'Say how lovely they are, and ask how old they are.', t: '¡Qué guapos! ¿Cuántos años tienen?', en: 'How lovely! How old are they?',
          alt: ['¡Qué lindos! ¿Cuántos años tienen?', '¿Cuántos años tienen?'],
          gloss: 'qué = how · guapos = good-looking (Spain; lindos in Latin America) · cuántos = how many · años = years · tienen = they have (tener)' } },
        { them: { t: 'Pablo tiene ocho y Lucía cinco. ¿Tú tienes hijos?', en: 'Pablo is eight and Lucía five. Do you have children?' } },
        { you: { cue: 'Say no, you don’t have children, but you have two sisters.', t: 'No, no tengo hijos, pero tengo dos hermanas.', en: 'No, I don’t have children, but I have two sisters.',
          alt: ['No tengo hijos, pero tengo dos hermanas', 'No, pero tengo dos hermanas'],
          gloss: 'no = no / not · tengo = I have · hijos = children (sons and daughters) · pero = but · dos = two · hermanas = sisters' } },
        { them: { t: '¿Y viven en Inglaterra?', en: 'And do they live in England?' } },
        { you: { cue: 'Say one lives in London and the other in Scotland.', t: 'Una vive en Londres y la otra en Escocia.', en: 'One lives in London and the other in Scotland.',
          alt: ['Una en Londres y la otra en Escocia', 'Una vive en Londres y otra en Escocia'],
          gloss: 'una = one (feminine) · vive = lives (vivir) · en = in · y = and · la otra = the other · Escocia = Scotland' } },
        { them: { t: '¿Y las ves mucho?', en: 'And do you see them a lot?' } },
        { you: { cue: 'Say not much, but you video-call on Sundays.', t: 'No mucho, pero hablamos por videollamada los domingos.', en: 'Not much, but we video-call on Sundays.',
          alt: ['No mucho, pero hablamos los domingos', 'No mucho, pero hacemos videollamada los domingos'],
          gloss: 'no mucho = not much · pero = but · hablamos = we talk (hablar) · por = by · videollamada = video call · los domingos = on Sundays' } },
        { them: { t: '¡Qué bien!', en: 'How nice!' } },
        { you: { cue: 'Say your parents are coming to see you next month.', t: 'Mis padres vienen a verme el mes que viene.', en: 'My parents are coming to see me next month.',
          alt: ['Mis padres vienen a verme el próximo mes', 'Mis padres me visitan el mes que viene'],
          gloss: 'mis = my (plural) · padres = parents · vienen = are coming (venir) · a verme = to see me · el mes que viene = next month (literally “the month that comes”)' } }
      ]
    },
    {
      title: 'What do you do at weekends?',
      scene: 'At lunch, a colleague asks what you like doing in your free time.',
      turns: [
        { them: { t: '¿Qué haces normalmente los fines de semana?', en: 'What do you usually do at weekends?' } },
        { you: { cue: 'Say you usually go running in the park on Saturdays.', t: 'Normalmente los sábados voy a correr al parque.', en: 'On Saturdays I usually go running in the park.',
          alt: ['Los sábados voy a correr al parque', 'Normalmente voy a correr al parque'],
          gloss: 'normalmente = usually · los sábados = on Saturdays · voy = I go (ir) · a correr = to run · al = to the · parque = park' } },
        { them: { t: '¡Qué deportista! Yo prefiero leer.', en: 'How sporty! I prefer reading.' } },
        { you: { cue: 'Say you like reading too, especially novels.', t: 'A mí también me gusta leer, sobre todo novelas.', en: 'I like reading too, especially novels.',
          alt: ['A mí también me gusta leer', 'También me gusta leer, sobre todo novelas'],
          gloss: 'a mí también = me too · me gusta = I like · leer = to read / reading · sobre todo = above all, especially · novelas = novels' } },
        { them: { t: '¿Y tocas algún instrumento?', en: 'And do you play an instrument?' } },
        { you: { cue: 'Say you play the guitar a bit, but very badly.', t: 'Toco un poco la guitarra, pero muy mal.', en: 'I play the guitar a bit, but very badly.',
          alt: ['Toco la guitarra, pero muy mal', 'Un poco la guitarra, pero muy mal'],
          gloss: 'toco = I play (tocar, for instruments; jugar is for games and sports) · un poco = a bit · la guitarra = the guitar · pero = but · muy mal = very badly' } },
        { them: { t: 'Ja, ja. ¿Y te gusta cocinar?', en: 'Ha ha. And do you like cooking?' } },
        { you: { cue: 'Say you love cooking, especially Spanish food.', t: 'Me encanta cocinar, sobre todo comida española.', en: 'I love cooking, especially Spanish food.',
          alt: ['Me encanta cocinar', 'Sí, me encanta cocinar, sobre todo comida española'],
          gloss: 'me encanta = I love · cocinar = to cook / cooking · sobre todo = especially · comida = food · española = Spanish' } },
        { them: { t: 'Pues un día tienes que hacer una paella.', en: 'Then one day you have to make a paella.' } },
        { you: { cue: 'Say OK, but your paella isn’t very good yet.', t: 'Vale, pero mi paella todavía no es muy buena.', en: 'OK, but my paella isn’t very good yet.',
          alt: ['Vale, pero mi paella no es muy buena', 'Bueno, pero mi paella todavía no es muy buena'],
          gloss: 'vale = OK · pero = but · mi = my · todavía no = not yet · es = is · muy = very · buena = good (feminine)' } }
      ]
    },
    {
      title: 'Hot, isn’t it?',
      scene: 'Waiting at a bus stop in August, an older man comments on the weather; you use “usted”.',
      turns: [
        { them: { t: '¡Qué calor hace hoy!', en: 'It’s so hot today!' } },
        { you: { cue: 'Agree, and ask if it’s always like this in summer.', t: 'Sí, hace muchísimo calor. ¿Siempre es así en verano?', en: 'Yes, it’s really hot. Is it always like this in summer?',
          alt: ['Sí, mucho calor. ¿Siempre es así en verano?', '¿Siempre es así en verano?'],
          gloss: 'sí = yes · hace calor = it’s hot (hacer, “it makes heat”) · muchísimo = very much · siempre = always · es = is · así = like this · en verano = in summer' } },
        { them: { t: 'En agosto, sí. Pero en invierno hace frío.', en: 'In August, yes. But in winter it’s cold.' } },
        { you: { cue: 'Say in London it rains a lot and it’s never this hot.', t: 'En Londres llueve mucho y nunca hace tanto calor.', en: 'In London it rains a lot and it’s never this hot.',
          alt: ['En Londres llueve mucho', 'En Londres nunca hace tanto calor'],
          gloss: 'en = in · llueve = it rains (llover) · mucho = a lot · y = and · nunca = never · hace = it makes · tanto = so much · calor = heat' } },
        { them: { t: '¿Y usted qué prefiere, el calor o el frío?', en: 'And what do you prefer, heat or cold?' } },
        { you: { cue: 'Say you prefer spring: not too hot, not too cold.', t: 'Prefiero la primavera, ni mucho calor ni mucho frío.', en: 'I prefer spring, neither too hot nor too cold.',
          alt: ['Prefiero la primavera', 'La primavera, ni mucho calor ni mucho frío'],
          gloss: 'prefiero = I prefer (preferir, e → ie) · la primavera = spring · ni… ni… = neither… nor… · mucho = much · calor = heat · frío = cold' } },
        { them: { t: 'Dicen que mañana va a llover.', en: 'They say it’s going to rain tomorrow.' } },
        { you: { cue: 'Say thank goodness, because the plants need water.', t: 'Menos mal, porque las plantas necesitan agua.', en: 'Thank goodness, because the plants need water.',
          alt: ['Menos mal, las plantas necesitan agua', 'Qué bien, porque las plantas necesitan agua'],
          gloss: 'menos mal = thank goodness (literally “less bad”) · porque = because · las plantas = the plants · necesitan = need (necesitar) · agua = water' } },
        { them: { t: 'Mire, ya viene el autobús.', en: 'Look, here comes the bus.' } },
        { you: { cue: 'Say “at last!”, and wish him a good day.', t: '¡Por fin! Que tenga un buen día.', en: 'At last! Have a good day.',
          alt: ['Por fin. Que tenga buen día', '¡Por fin! Buen día'],
          gloss: 'por fin = at last · que tenga = may you have (tener, subjunctive, usted) · un buen día = a good day' } }
      ]
    },
    {
      title: 'Language exchange',
      scene: 'At a language exchange, Marta asks you about yourself; you use “tú”.',
      turns: [
        { them: { t: 'Bueno, cuéntame un poco de ti.', en: 'So, tell me a bit about yourself.' } },
        { you: { cue: 'Say your name, that you’re thirty-four, and from London.', t: 'Pues me llamo Alex, tengo treinta y cuatro años y soy de Londres.', en: 'Well, my name is Alex, I’m thirty-four and I’m from London.',
          alt: ['Me llamo Alex, tengo 34 años y soy de Londres', 'Soy Alex, tengo treinta y cuatro años y soy de Londres'],
          gloss: 'pues = well · me llamo = my name is · tengo = I have · treinta y cuatro = thirty-four · años = years · y = and · soy de = I’m from' } },
        { them: { t: '¿Y por qué aprendes español?', en: 'And why are you learning Spanish?' } },
        { you: { cue: 'Say because you love travelling and want to talk to people.', t: 'Porque me encanta viajar y quiero hablar con la gente.', en: 'Because I love travelling and I want to talk to people.',
          alt: ['Porque me encanta viajar', 'Porque quiero hablar con la gente'],
          gloss: 'porque = because · me encanta = I love · viajar = to travel · y = and · quiero = I want (querer) · hablar = to talk · con = with · la gente = people' } },
        { them: { t: '¡Pues hablas muy bien!', en: 'Well, you speak very well!' } },
        { you: { cue: 'Thank her, but say you still make lots of mistakes.', t: 'Gracias, pero todavía cometo muchos errores.', en: 'Thanks, but I still make lots of mistakes.',
          alt: ['Gracias, pero todavía hago muchos errores', 'Gracias, pero cometo muchos errores'],
          gloss: 'gracias = thanks · pero = but · todavía = still · cometo = I make (cometer, used with mistakes) · muchos = many · errores = mistakes' } },
        { them: { t: 'Es normal. ¿Y qué haces en tu tiempo libre?', en: 'That’s normal. And what do you do in your free time?' } },
        { you: { cue: 'Say you like cooking, reading and walking your dog.', t: 'Me gusta cocinar, leer y pasear con mi perro.', en: 'I like cooking, reading and walking with my dog.',
          alt: ['Me gusta cocinar, leer y pasear al perro', 'Cocinar, leer y pasear con mi perro'],
          gloss: 'me gusta = I like · cocinar = to cook · leer = to read · y = and · pasear = to go for a walk · con = with · mi = my · perro = dog' } },
        { them: { t: '¡Yo también tengo perro!', en: 'I have a dog too!' } },
        { you: { cue: 'Say “really?” and ask what her dog is called.', t: '¿Ah, sí? ¿Y cómo se llama tu perro?', en: 'Oh really? And what’s your dog called?',
          alt: ['¿Cómo se llama tu perro?', '¿Ah, sí? ¿Cómo se llama?'],
          gloss: 'ah, sí = oh, really · y = and · cómo = how · se llama = is called (llamarse) · tu = your (informal) · perro = dog' } }
      ]
    },

    /* ---------- 7. Plans, invitations & time ---------- */
    {
      title: 'Are you free on Saturday?',
      scene: 'You phone your friend Javi to invite him out.',
      turns: [
        { them: { t: '¿Sí? ¡Hola, Alex!', en: 'Hello? Hi, Alex!' } },
        { you: { cue: 'Say hi, and ask if he’s free on Saturday night.', t: '¡Hola, Javi! Oye, ¿estás libre el sábado por la noche?', en: 'Hi, Javi! Listen, are you free on Saturday night?',
          alt: ['Hola, Javi, ¿estás libre el sábado por la noche?', '¿Estás libre el sábado por la noche?'],
          gloss: 'hola = hi · oye = listen / hey (oír, tú command) · estás = you are (estar) · libre = free · el sábado = on Saturday · por la noche = at night' } },
        { them: { t: 'Creo que sí. ¿Por qué?', en: 'I think so. Why?' } },
        { you: { cue: 'Ask if he wants to come to the cinema to see the new film.', t: '¿Quieres venir al cine a ver la nueva película?', en: 'Do you want to come to the cinema to see the new film?',
          alt: ['¿Quieres ir al cine a ver la nueva película?', '¿Vienes al cine?'],
          gloss: 'quieres = you want (querer, tú) · venir = to come · al cine = to the cinema · a ver = to see · la = the · nueva = new · película = film' } },
        { them: { t: '¡Vale! ¿A qué hora?', en: 'OK! What time?' } },
        { you: { cue: 'Suggest meeting at eight at the cinema door.', t: '¿Quedamos a las ocho en la puerta del cine?', en: 'Shall we meet at eight at the cinema door?',
          alt: ['¿Nos vemos a las ocho en la puerta del cine?', '¿Quedamos a las 8 en la puerta del cine?'],
          gloss: 'quedamos = we meet up (quedar — Spain; Latin America says “¿nos vemos…?”) · a las ocho = at eight · en = at · la puerta = the door · del cine = of the cinema' } },
        { them: { t: 'Mejor a las ocho y media, que salgo tarde del trabajo.', en: 'Better half past eight, because I finish work late.' } },
        { you: { cue: 'Say no problem, half past eight then.', t: 'No hay problema, entonces a las ocho y media.', en: 'No problem, half past eight then.',
          alt: ['Vale, a las ocho y media', 'No hay problema, a las 8:30'],
          gloss: 'no hay problema = no problem · entonces = then · a las ocho y media = at half past eight (eight and a half)' } },
        { them: { t: 'Perfecto. ¡Hasta el sábado!', en: 'Perfect. See you Saturday!' } },
        { you: { cue: 'Say see you Saturday, and to call you if anything comes up.', t: '¡Hasta el sábado! Si pasa algo, me llamas.', en: 'See you Saturday! If anything comes up, call me.',
          alt: ['Hasta el sábado, si pasa algo me llamas', 'Hasta el sábado'],
          gloss: 'hasta el sábado = until Saturday · si = if · pasa = happens (pasar) · algo = something · me llamas = you call me (present used as a friendly request)' } }
      ]
    },
    {
      title: 'Sorry, I can’t',
      scene: 'A colleague invites you to dinner, but you already have plans.',
      turns: [
        { them: { t: 'Oye, el viernes hacemos una cena en casa. ¿Te vienes?', en: 'Hey, on Friday we’re having a dinner at home. Are you coming?' } },
        { you: { cue: 'Thank her, and say you’re sorry but you can’t on Friday.', t: 'Muchas gracias, pero lo siento, el viernes no puedo.', en: 'Thanks a lot, but I’m sorry, I can’t on Friday.',
          alt: ['Gracias, pero el viernes no puedo', 'Lo siento, el viernes no puedo'],
          gloss: 'muchas gracias = thanks a lot · pero = but · lo siento = I’m sorry · el viernes = on Friday · no puedo = I can’t (poder)' } },
        { them: { t: '¡Qué pena! ¿Tienes planes?', en: 'What a shame! Do you have plans?' } },
        { you: { cue: 'Say you’re going to your cousin’s wedding in Seville.', t: 'Sí, voy a la boda de mi prima en Sevilla.', en: 'Yes, I’m going to my cousin’s wedding in Seville.',
          alt: ['Voy a la boda de mi prima en Sevilla', 'Sí, voy a una boda en Sevilla'],
          gloss: 'sí = yes · voy = I go (ir) · a la = to the · boda = wedding · de = of · mi = my · prima = (female) cousin · en = in · Sevilla = Seville' } },
        { them: { t: '¡Qué bonito! Bueno, otro día.', en: 'How lovely! Well, another day.' } },
        { you: { cue: 'Suggest having lunch together next week instead.', t: '¿Y si comemos juntos la semana que viene?', en: 'What if we have lunch together next week?',
          alt: ['¿Comemos juntos la semana que viene?', '¿Y si comemos juntos la próxima semana?'],
          gloss: 'y si = what if · comemos = we eat / have lunch (comer) · juntos = together · la semana que viene = next week' } },
        { them: { t: '¡Me parece genial! ¿El martes?', en: 'Sounds great! Tuesday?' } },
        { you: { cue: 'Say Tuesday suits you perfectly, at two.', t: 'El martes me viene perfecto, a las dos.', en: 'Tuesday is perfect for me, at two.',
          alt: ['El martes me va perfecto, a las dos', 'El martes está perfecto, a las 2'],
          gloss: 'el martes = (on) Tuesday · me viene = suits me (venir, “comes to me”) · perfecto = perfect · a las dos = at two' } },
        { them: { t: 'Hecho.', en: 'Done.' } },
        { you: { cue: 'Say great, and hope they all have a good time on Friday.', t: 'Genial. Y que lo paséis muy bien el viernes.', en: 'Great. And have a great time on Friday, all of you.',
          alt: ['Genial. Y que lo pasen muy bien el viernes', 'Que lo paséis muy bien'],
          gloss: 'genial = great · y = and · que lo paséis bien = have a good time (pasarlo bien, subjunctive, vosotros = you all — Spain only; Latin America uses ustedes: “que lo pasen bien”) · muy = very · el viernes = on Friday' } }
      ]
    },
    {
      title: 'Booking a table',
      scene: 'You phone a restaurant to book a table for a birthday dinner.',
      turns: [
        { them: { t: 'Restaurante La Plaza, dígame.', en: 'La Plaza restaurant, go ahead.' } },
        { you: { cue: 'Say hello, and that you’d like to book a table for six on Saturday.', t: 'Hola, quería reservar una mesa para seis personas el sábado.', en: 'Hello, I’d like to book a table for six people on Saturday.',
          alt: ['Quería reservar una mesa para seis el sábado', 'Hola, quería reservar una mesa para 6 personas el sábado'],
          gloss: 'hola = hello · quería = I’d like · reservar = to book · una mesa = a table · para = for · seis = six · personas = people · el sábado = on Saturday' } },
        { them: { t: '¿Para comer o para cenar?', en: 'For lunch or for dinner?' } },
        { you: { cue: 'Say for dinner, around half past nine if possible.', t: 'Para cenar, sobre las nueve y media, si es posible.', en: 'For dinner, around half past nine, if possible.',
          alt: ['Para cenar, a las nueve y media', 'Para cenar, sobre las 9:30'],
          gloss: 'para cenar = for dinner (cenar = to have dinner) · sobre las = around (time) · nueve y media = half past nine · si = if · es = it is · posible = possible' } },
        { them: { t: 'A las nueve y media está completo. ¿Le va bien a las diez?', en: 'At half past nine we’re full. Is ten OK for you?' } },
        { you: { cue: 'Say ten is fine, and that it’s for a birthday.', t: 'Sí, a las diez está bien. Es para un cumpleaños.', en: 'Yes, ten is fine. It’s for a birthday.',
          alt: ['A las diez está bien, es para un cumpleaños', 'Sí, a las 10 está bien. Es un cumpleaños'],
          gloss: 'sí = yes · a las diez = at ten · está bien = is fine · es = it is · para = for · un cumpleaños = a birthday' } },
        { them: { t: '¡Qué bien! ¿Quieren que les preparemos una tarta?', en: 'Lovely! Would you like us to make you a cake?' } },
        { you: { cue: 'Say yes please — a chocolate cake would be perfect.', t: 'Sí, por favor, una tarta de chocolate sería perfecta.', en: 'Yes, please, a chocolate cake would be perfect.',
          alt: ['Sí, una tarta de chocolate, por favor', 'Sí, por favor, un pastel de chocolate sería perfecto', 'Sí, una torta de chocolate sería perfecta'],
          gloss: 'sí, por favor = yes please · una tarta = a cake (Spain; pastel in Mexico, torta in Argentina) · de chocolate = chocolate · sería = would be (ser, conditional) · perfecta = perfect' } },
        { them: { t: 'Muy bien. ¿A nombre de quién?', en: 'Very good. In whose name?' } },
        { you: { cue: 'Give the name Alex, and ask if they need your phone number.', t: 'A nombre de Alex. ¿Necesita mi número de teléfono?', en: 'In the name of Alex. Do you need my phone number?',
          alt: ['A nombre de Alex. ¿Necesita mi teléfono?', 'De Alex. ¿Necesita mi número?'],
          gloss: 'a nombre de = in the name of · necesita = do you need (necesitar, usted) · mi = my · número de teléfono = phone number' } }
      ]
    },
    {
      title: 'A day in the mountains',
      scene: 'On Friday afternoon, a friend asks what you’re doing this weekend.',
      turns: [
        { them: { t: '¿Qué vas a hacer este fin de semana?', en: 'What are you going to do this weekend?' } },
        { you: { cue: 'Say on Saturday morning you’re going to clean the house — how boring.', t: 'El sábado por la mañana voy a limpiar la casa, qué aburrido.', en: 'On Saturday morning I’m going to clean the house, how boring.',
          alt: ['El sábado voy a limpiar la casa, qué aburrido', 'El sábado por la mañana voy a limpiar la casa'],
          gloss: 'el sábado = on Saturday · por la mañana = in the morning · voy a limpiar = I’m going to clean (ir a + infinitive) · la casa = the house · qué aburrido = how boring' } },
        { them: { t: '¡Ja, ja! ¿Y el domingo?', en: 'Ha ha! And on Sunday?' } },
        { you: { cue: 'Say on Sunday you’re going to the mountains with some friends, if it doesn’t rain.', t: 'El domingo voy a la montaña con unos amigos, si no llueve.', en: 'On Sunday I’m going to the mountains with some friends, if it doesn’t rain.',
          alt: ['El domingo voy a la montaña con unos amigos', 'Voy a la montaña con unos amigos, si no llueve'],
          gloss: 'el domingo = on Sunday · voy = I go · a la montaña = to the mountains · con = with · unos amigos = some friends · si = if · no llueve = it doesn’t rain (llover)' } },
        { them: { t: '¡Qué envidia! ¿A qué hora salís?', en: 'I’m so jealous! What time are you leaving?' } },
        { you: { cue: 'Say you’re leaving very early, at seven in the morning.', t: 'Salimos muy temprano, a las siete de la mañana.', en: 'We’re leaving very early, at seven in the morning.',
          alt: ['Muy temprano, a las siete de la mañana', 'Salimos a las 7 de la mañana'],
          gloss: 'salimos = we leave (salir; present used for plans) · muy temprano = very early · a las siete = at seven · de la mañana = in the morning' } },
        { them: { t: 'Uf, yo a esa hora estoy durmiendo.', en: 'Ugh, at that time I’m asleep.' } },
        { you: { cue: 'Ask why he doesn’t come with you — there’s room in the car.', t: '¿Por qué no vienes con nosotros? Hay sitio en el coche.', en: 'Why don’t you come with us? There’s room in the car.',
          alt: ['¿Por qué no vienes con nosotros? Hay lugar en el carro', '¿Por qué no vienes? Hay sitio en el coche', '¿Por qué no vienes con nosotros? Hay lugar en el auto'],
          gloss: 'por qué no = why not · vienes = you come (venir, tú) · con nosotros = with us · hay = there is · sitio = room, space (lugar in Latin America) · en = in · el coche = the car (carro in Mexico, Colombia and Central America; auto in Argentina and Chile)' } },
        { them: { t: 'Mmm... ¡Vale, me apunto!', en: 'Hmm... OK, count me in!' } },
        { you: { cue: 'Say great — you’ll pick him up at a quarter to seven.', t: '¡Genial! Te recojo a las siete menos cuarto.', en: 'Great! I’ll pick you up at a quarter to seven.',
          alt: ['Genial, te recojo a las siete menos cuarto', 'Te paso a buscar a las siete menos cuarto', 'Te recojo a las 6:45'],
          gloss: 'genial = great · te = you (informal object) · recojo = I pick up (recoger; “te paso a buscar” in Argentina) · a las siete menos cuarto = at seven minus a quarter (6:45)' } }
      ]
    },
    {
      title: 'Stuck in traffic',
      scene: 'You’re stuck in traffic and phone your friend, who’s waiting at the restaurant.',
      turns: [
        { them: { t: '¡Hola! ¿Dónde estás? Ya estoy en el restaurante.', en: 'Hi! Where are you? I’m already at the restaurant.' } },
        { you: { cue: 'Apologise and say you’re stuck in a huge traffic jam in the centre.', t: 'Lo siento mucho, estoy en un atasco enorme en el centro.', en: 'I’m really sorry, I’m in a huge traffic jam in the centre.',
          alt: ['Lo siento, estoy en un atasco', 'Lo siento mucho, hay muchísimo tráfico en el centro', 'Lo siento mucho, estoy en un embotellamiento en el centro'],
          gloss: 'lo siento mucho = I’m really sorry · estoy = I am (estar) · en un atasco = in a traffic jam (Spain; embotellamiento or tráfico elsewhere, trancón in Colombia) · enorme = huge · en el centro = in the centre' } },
        { them: { t: 'Vaya. ¿Vas a tardar mucho?', en: 'Oh dear. Are you going to be long?' } },
        { you: { cue: 'Say you think you’ll get there in about twenty minutes.', t: 'Creo que llego en unos veinte minutos, más o menos.', en: 'I think I’ll get there in about twenty minutes, more or less.',
          alt: ['Llego en unos veinte minutos', 'Creo que llego en 20 minutos, más o menos'],
          gloss: 'creo que = I think that · llego = I arrive (present used for the near future) · en = in · unos = about · veinte = twenty · minutos = minutes · más o menos = more or less' } },
        { them: { t: 'Vale, no pasa nada. ¿Pido algo mientras?', en: 'OK, no worries. Shall I order something meanwhile?' } },
        { you: { cue: 'Tell her to order a drink and start without you.', t: 'Sí, pide algo de beber y empieza sin mí.', en: 'Yes, order something to drink and start without me.',
          alt: ['Pide algo de beber y empieza sin mí', 'Sí, pide algo y empieza sin mí'],
          gloss: 'sí = yes · pide = order (pedir, tú command) · algo de beber = something to drink · y = and · empieza = start (empezar, tú command) · sin mí = without me' } },
        { them: { t: '¿Quieres que te pida algo a ti también?', en: 'Do you want me to order something for you too?' } },
        { you: { cue: 'Ask her to order you a sparkling water and the fish.', t: 'Sí, pídeme un agua con gas y el pescado, por favor.', en: 'Yes, order me a sparkling water and the fish, please.',
          alt: ['Pídeme un agua con gas y el pescado', 'Sí, un agua con gas y el pescado, por favor'],
          gloss: 'sí = yes · pídeme = order for me (pide + me) · un agua con gas = a sparkling water · y = and · el pescado = the fish (as food; a live fish is pez) · por favor = please' } },
        { them: { t: 'Hecho. ¡Conduce con cuidado!', en: 'Done. Drive carefully!' } },
        { you: { cue: 'Thank her and say you’ll see her in a little while.', t: 'Gracias. Nos vemos en un ratito, ¡hasta ahora!', en: 'Thanks. See you in a little while — see you soon!',
          alt: ['Gracias, nos vemos en un ratito', 'Gracias, hasta ahora'],
          gloss: 'gracias = thanks · nos vemos = we see each other (verse) · en un ratito = in a little while (rato + -ito, “little”) · hasta ahora = see you in a bit (literally “until now”)' } }
      ]
    },

    /* ---------- 8. Past experiences, health & opinions ---------- */
    {
      title: 'How was your holiday?',
      scene: 'Back at work, a colleague asks about your holiday.',
      turns: [
        { them: { t: '¡Hola! ¿Qué tal las vacaciones?', en: 'Hi! How was your holiday?' } },
        { you: { cue: 'Say it was great — you spent two weeks in the south of Spain, in Andalusia.', t: 'Genial. Estuve dos semanas en el sur de España, en Andalucía.', en: 'Great. I spent two weeks in the south of Spain, in Andalusia.',
          alt: ['Genial, estuve dos semanas en Andalucía', 'Estuve dos semanas en el sur de España'],
          gloss: 'genial = great · estuve = I was (estar, preterite) · dos semanas = two weeks · en = in · el sur = the south · de España = of Spain · Andalucía = Andalusia' } },
        { them: { t: '¡Qué bien! ¿Y qué hiciste?', en: 'How nice! And what did you do?' } },
        { you: { cue: 'Say you visited Seville and Granada, and went to the beach a lot.', t: 'Visité Sevilla y Granada, y fui mucho a la playa.', en: 'I visited Seville and Granada, and I went to the beach a lot.',
          alt: ['Visité Sevilla y Granada', 'Visité Sevilla y Granada y fui mucho a la playa'],
          gloss: 'visité = I visited (visitar, preterite) · y = and · fui = I went (ir, preterite) · mucho = a lot · a la playa = to the beach' } },
        { them: { t: '¿Y qué tal la comida?', en: 'And how was the food?' } },
        { you: { cue: 'Say the food was delicious — you ate fish every day.', t: 'La comida estaba buenísima. Comí pescado todos los días.', en: 'The food was delicious. I ate fish every day.',
          alt: ['La comida estaba buenísima', 'Buenísima, comí pescado todos los días'],
          gloss: 'la comida = the food · estaba = was (estar, imperfect — describing) · buenísima = really good · comí = I ate (comer, preterite) · pescado = fish · todos los días = every day' } },
        { them: { t: '¿Hizo mucho calor?', en: 'Was it very hot?' } },
        { you: { cue: 'Say yes — one day it was forty degrees and you didn’t leave the hotel.', t: 'Sí, un día hizo cuarenta grados y no salí del hotel.', en: 'Yes, one day it was forty degrees and I didn’t leave the hotel.',
          alt: ['Sí, un día hizo 40 grados y no salí del hotel', 'Un día hizo cuarenta grados'],
          gloss: 'sí = yes · un día = one day · hizo = it made (hacer, preterite — weather) · cuarenta = forty · grados = degrees · y = and · no salí = I didn’t go out (salir, preterite) · del hotel = of the hotel' } },
        { them: { t: '¡Madre mía!', en: 'Good grief!' } },
        { you: { cue: 'Say it was a fantastic trip, and you want to go back next year.', t: 'Fue un viaje fantástico. Quiero volver el año que viene.', en: 'It was a fantastic trip. I want to go back next year.',
          alt: ['Fue un viaje fantástico', 'Fue un viaje fantástico, quiero volver el próximo año'],
          gloss: 'fue = it was (ser, preterite — the trip as a whole) · un viaje = a trip · fantástico = fantastic · quiero = I want · volver = to go back · el año que viene = next year' } }
      ]
    },
    {
      title: 'At the doctor’s',
      scene: 'You feel ill and go to see a doctor; you use “usted”.',
      turns: [
        { them: { t: 'Buenos días. Siéntese. ¿Qué le pasa?', en: 'Good morning. Sit down. What’s the matter?' } },
        { you: { cue: 'Say you’ve felt unwell since yesterday: your head hurts and you have a fever.', t: 'Desde ayer me encuentro mal. Me duele la cabeza y tengo fiebre.', en: 'I’ve felt unwell since yesterday. I have a headache and a fever.',
          alt: ['Me siento mal desde ayer. Me duele la cabeza y tengo fiebre', 'Me duele la cabeza y tengo fiebre'],
          gloss: 'desde ayer = since yesterday · me encuentro mal = I feel unwell (encontrarse; “me siento mal” everywhere) · me duele = hurts me (doler, like gustar) · la cabeza = the head · y = and · tengo fiebre = I have a fever' } },
        { them: { t: '¿Le duele también la garganta?', en: 'Does your throat hurt too?' } },
        { you: { cue: 'Say yes, quite a lot, especially when you eat or drink.', t: 'Sí, bastante, sobre todo cuando como o bebo algo.', en: 'Yes, quite a lot, especially when I eat or drink something.',
          alt: ['Sí, bastante, sobre todo cuando como', 'Sí, sobre todo cuando como o bebo'],
          gloss: 'sí = yes · bastante = quite a lot · sobre todo = especially · cuando = when · como = I eat (comer) · o = or · bebo = I drink (beber) · algo = something' } },
        { them: { t: '¿Toma algún medicamento?', en: 'Are you taking any medicine?' } },
        { you: { cue: 'Say no, you only took one paracetamol last night before bed.', t: 'No, solo me tomé un paracetamol anoche antes de dormir.', en: 'No, I only took a paracetamol last night before sleeping.',
          alt: ['Solo un paracetamol anoche', 'No, solo tomé un paracetamol anoche'],
          gloss: 'no = no · solo = only · me tomé = I took (tomarse, preterite) · un paracetamol = a paracetamol · anoche = last night · antes de = before · dormir = to sleep' } },
        { them: { t: '¿Es alérgico a algo?', en: 'Are you allergic to anything?' } },
        { you: { cue: 'Say yes, you’re allergic to penicillin.', t: 'Sí, soy alérgico a la penicilina.', en: 'Yes, I’m allergic to penicillin.',
          alt: ['Sí, soy alérgica a la penicilina', 'Soy alérgico a la penicilina'],
          gloss: 'sí = yes · soy = I am (ser) · alérgico = allergic (a woman says alérgica) · a = to · la penicilina = penicillin' } },
        { them: { t: 'Es una gripe. Tómese esto cada ocho horas y descanse.', en: 'It’s flu. Take this every eight hours and rest.' } },
        { you: { cue: 'Ask if you can go to work tomorrow, or if it’s better to stay at home.', t: '¿Puedo ir a trabajar mañana o es mejor quedarme en casa?', en: 'Can I go to work tomorrow, or is it better to stay at home?',
          alt: ['¿Puedo ir a trabajar mañana?', '¿Es mejor quedarme en casa?'],
          gloss: 'puedo = can I · ir a trabajar = go to work · mañana = tomorrow · o = or · es mejor = is it better · quedarme = to stay (quedarse) · en casa = at home' } },
        { them: { t: 'Mejor quédese en casa dos o tres días.', en: 'Better stay at home for two or three days.' } }
      ]
    },
    {
      title: 'What did you think?',
      scene: 'Leaving the cinema, you and Javi share your opinions of the film.',
      turns: [
        { them: { t: 'Bueno, ¿qué te ha parecido la película?', en: 'So, what did you think of the film?' } },
        { you: { cue: 'Say you liked it a lot, especially the ending, which you didn’t expect.', t: 'Me ha gustado mucho, sobre todo el final, que no me esperaba.', en: 'I really liked it, especially the ending, which I didn’t expect.',
          alt: ['Me gustó mucho, sobre todo el final', 'Me ha gustado mucho, sobre todo el final'],
          gloss: 'me ha gustado = I liked it (present perfect, Spain; Latin America: “me gustó”) · mucho = a lot · sobre todo = especially · el final = the ending · que = which · no me esperaba = I wasn’t expecting (esperarse, imperfect)' } },
        { them: { t: '¿Sí? A mí me ha parecido un poco larga.', en: 'Really? I thought it was a bit long.' } },
        { you: { cue: 'Agree it was a bit long, but say the actors were very good.', t: 'Sí, un poco larga, pero los actores eran muy buenos.', en: 'Yes, a bit long, but the actors were very good.',
          alt: ['Un poco larga, pero los actores eran muy buenos', 'Sí, pero los actores eran muy buenos'],
          gloss: 'sí = yes · un poco = a bit · larga = long (feminine, for la película) · pero = but · los actores = the actors · eran = were (ser, imperfect) · muy buenos = very good' } },
        { them: { t: 'Eso sí. La protagonista es increíble.', en: 'That’s true. The lead actress is incredible.' } },
        { you: { cue: 'Give your opinion: for you, she’s the best actress in Spain right now.', t: 'Para mí, es la mejor actriz de España ahora mismo.', en: 'For me, she’s the best actress in Spain right now.',
          alt: ['Creo que es la mejor actriz de España', 'Para mí es la mejor actriz de España'],
          gloss: 'para mí = for me, in my opinion · es = she is · la mejor = the best · actriz = actress · de España = in Spain (Spanish says “of”) · ahora mismo = right now' } },
        { them: { t: '¿Tú crees? Yo prefiero a Penélope Cruz.', en: 'You think so? I prefer Penélope Cruz.' } },
        { you: { cue: 'Say you don’t agree, but it’s a matter of taste.', t: 'No estoy de acuerdo, pero bueno, para gustos, los colores.', en: 'I don’t agree, but hey, each to their own.',
          alt: ['No estoy de acuerdo, pero es cuestión de gustos', 'No estoy de acuerdo, pero para gustos, colores'],
          gloss: 'no estoy de acuerdo = I don’t agree (estar de acuerdo = to agree) · pero bueno = but hey · para gustos, los colores = “for tastes, the colours” — a saying: everyone has their own taste' } },
        { them: { t: '¡Ja, ja! ¿Tomamos algo y lo discutimos?', en: 'Ha ha! Shall we get a drink and argue about it?' } },
        { you: { cue: 'Say good idea, and suggest your usual bar on the corner.', t: 'Buena idea. ¿Vamos al bar de la esquina, el de siempre?', en: 'Good idea. Shall we go to the bar on the corner, our usual one?',
          alt: ['Buena idea, ¿vamos al bar de la esquina?', '¿Vamos al bar de siempre?'],
          gloss: 'buena idea = good idea · vamos = let’s go / shall we go (ir) · al bar = to the bar · de la esquina = on the corner · el de siempre = the usual one (literally “the one of always”)' } }
      ]
    },
    {
      title: 'A terrible day',
      scene: 'Your friend sees you look tired and asks what happened.',
      turns: [
        { them: { t: '¿Qué te pasa? Tienes mala cara.', en: 'What’s wrong? You look awful.' } },
        { you: { cue: 'Say you’ve had a horrible day — everything went wrong.', t: 'Uf, he tenido un día horrible. Todo me ha salido mal.', en: 'Ugh, I’ve had a horrible day. Everything went wrong.',
          alt: ['Tuve un día horrible. Todo me salió mal', 'He tenido un día horrible'],
          gloss: 'uf = ugh · he tenido = I’ve had (tener, present perfect — Spain for today; Latin America: “tuve”) · un día = a day · horrible = horrible · todo = everything · me ha salido mal = has turned out badly for me (salir)' } },
        { them: { t: '¿Por qué? ¿Qué ha pasado?', en: 'Why? What happened?' } },
        { you: { cue: 'Say first, you got up late because the alarm didn’t go off.', t: 'Primero, me levanté tarde porque no sonó el despertador.', en: 'First, I got up late because the alarm didn’t go off.',
          alt: ['Me levanté tarde porque no sonó el despertador', 'Primero me levanté tarde, no sonó el despertador'],
          gloss: 'primero = first · me levanté = I got up (levantarse, preterite) · tarde = late · porque = because · no sonó = didn’t ring (sonar, preterite) · el despertador = the alarm clock' } },
        { them: { t: '¡Vaya!', en: 'Oh no!' } },
        { you: { cue: 'Say then you missed the bus and got to work an hour late.', t: 'Luego perdí el autobús y llegué una hora tarde al trabajo.', en: 'Then I missed the bus and got to work an hour late.',
          alt: ['Luego perdí el bus y llegué una hora tarde al trabajo', 'Perdí el autobús y llegué una hora tarde'],
          gloss: 'luego = then · perdí = I missed / lost (perder, preterite) · el autobús = the bus · y = and · llegué = I arrived (llegar, preterite) · una hora = an hour · tarde = late · al trabajo = to work' } },
        { them: { t: '¿Y tu jefe qué dijo?', en: 'And what did your boss say?' } },
        { you: { cue: 'Say he got very angry — and on top of that you left your phone at home.', t: 'Se enfadó mucho, y encima me dejé el móvil en casa.', en: 'He got really angry, and on top of that I left my phone at home.',
          alt: ['Se enojó mucho, y encima dejé el celular en casa', 'Se enfadó mucho, y encima me dejé el móvil'],
          gloss: 'se enfadó = he got angry (enfadarse, Spain; enojarse in Latin America) · mucho = a lot · y encima = and on top of that · me dejé = I left (behind) · el móvil = the mobile phone (celular in Latin America) · en casa = at home' } },
        { them: { t: '¡Pobre! Bueno, ahora a descansar.', en: 'Poor you! Well, time to rest now.' } },
        { you: { cue: 'Say yes, tonight you’ll have a bit of dinner and go to bed early.', t: 'Sí, esta noche voy a cenar algo y me acuesto pronto.', en: 'Yes, tonight I’m going to have something for dinner and go to bed early.',
          alt: ['Sí, esta noche ceno algo y me acuesto temprano', 'Esta noche me acuesto pronto'],
          gloss: 'sí = yes · esta noche = tonight · voy a cenar = I’m going to have dinner · algo = something · y = and · me acuesto = I go to bed (acostarse) · pronto = early (Spain; temprano everywhere)' } }
      ]
    },
    {
      title: 'How we met',
      scene: 'At a dinner, a friend asks how you met Javi, and you tell the story.',
      turns: [
        { them: { t: 'Oye, ¿y cómo conociste a Javi?', en: 'Hey, and how did you meet Javi?' } },
        { you: { cue: 'Say you met him three years ago, on your first day in Madrid.', t: 'Lo conocí hace tres años, mi primer día en Madrid.', en: 'I met him three years ago, on my first day in Madrid.',
          alt: ['Lo conocí hace tres años, en mi primer día en Madrid', 'Lo conocí hace 3 años, mi primer día en Madrid'],
          gloss: 'lo = him · conocí = I met (conocer, preterite = got to know) · hace tres años = three years ago · mi = my · primer = first · día = day · en = in' } },
        { them: { t: '¡No me digas! ¿Cómo fue?', en: 'No way! How did it happen?' } },
        { you: { cue: 'Set the scene: you were lost in the metro and didn’t understand a thing.', t: 'Estaba perdido en el metro y no entendía nada de nada.', en: 'I was lost in the metro and didn’t understand a single thing.',
          alt: ['Estaba perdida en el metro y no entendía nada', 'Estaba perdido en el metro y no entendía nada'],
          gloss: 'estaba = I was (estar, imperfect — background of a story) · perdido = lost (a woman says perdida) · en el metro = in the metro · y = and · no entendía = I didn’t understand (imperfect) · nada de nada = nothing at all' } },
        { them: { t: '¿Y él te ayudó?', en: 'And he helped you?' } },
        { you: { cue: 'Say yes: he asked if you needed help, and took you to your hotel.', t: 'Sí, me preguntó si necesitaba ayuda y me llevó al hotel.', en: 'Yes, he asked me if I needed help and took me to the hotel.',
          alt: ['Me preguntó si necesitaba ayuda y me llevó al hotel', 'Sí, me ayudó y me llevó al hotel'],
          gloss: 'sí = yes · me preguntó = he asked me (preguntar, preterite) · si = if · necesitaba = I needed (imperfect) · ayuda = help · y = and · me llevó = he took me (llevar, preterite) · al hotel = to the hotel' } },
        { them: { t: '¡Qué majo!', en: 'How nice of him!' } },
        { you: { cue: 'Say afterwards you went for a coffee and talked for two hours.', t: 'Después fuimos a tomar un café y hablamos durante dos horas.', en: 'Afterwards we went for a coffee and talked for two hours.',
          alt: ['Después fuimos a tomar un café y hablamos dos horas', 'Fuimos a tomar un café y hablamos durante 2 horas'],
          gloss: 'después = afterwards · fuimos = we went (ir, preterite) · a tomar un café = to have a coffee · y = and · hablamos = we talked (hablar, preterite — same form as present) · durante = for (a length of time) · dos horas = two hours' } },
        { them: { t: '¿Y en qué idioma hablabais?', en: 'And what language did you two speak?' } },
        { you: { cue: 'Say in Spanish — very slowly, but in Spanish. That’s how you learned!', t: 'En español, muy despacio, pero en español. ¡Así aprendí!', en: 'In Spanish, very slowly, but in Spanish. That’s how I learned!',
          alt: ['En español, muy despacio, pero en español', 'En español, muy despacio. Así aprendí'],
          gloss: 'en español = in Spanish · muy despacio = very slowly · pero = but · así = like that, that’s how · aprendí = I learned (aprender, preterite)' } },
        { them: { t: '¡Qué historia tan bonita!', en: 'What a lovely story!' } },
        { you: { cue: 'Say since then he’s been your best friend here in Spain.', t: 'Y desde entonces, es mi mejor amigo aquí en España.', en: 'And since then, he’s my best friend here in Spain.',
          alt: ['Desde entonces es mi mejor amigo', 'Y desde entonces es mi mejor amigo aquí'],
          gloss: 'y = and · desde entonces = since then · es = he is (ser) · mi = my · mejor = best · amigo = friend · aquí = here · en España = in Spain' } }
      ]
    }
  ]
};
